MIGRATING.md, README.md
This PR updates the links to the CDK CLI now that it has been rename (as of https://github.com/guardian/cdk-cli/pull/9)
No
1) Click the link in the README or MIGRATING.md docs
2) Marvel at the power of the internet
The links to CDK CLI send us to the correct repository
=> Update cdk cli repository url

README.md
Updates the usage instructions now that the library is published to npm.
Existing projects will no be able to install via npm but this change is not required.
=> Update README now that the library is published

src/constructs/autoscaling/asg.test.ts, src/constructs/autoscaling/asg.ts
When testing the `GuAutoscalingGroup` component, it was noted that providing more than one target group produced an error. This PR updates the `targetGroups` prop to be `targetGroup` which is now a singular item and updates the implementation logic accordingly.
Yes. Any projects using the `targetGroups` prop will need to be updated. This is currently only one project.
Run `yarn test` and see the updated tests pass.
A user can no longer pass an array of target groups into the `GuAutoscalingGroup` component, triggering a runtime error.
=> update asg to only take singular target group

src/constructs/core/stack.test.ts, src/constructs/core/stack.ts
This PR updates the GuStack to take a new `GuStackProps` interface which allows for an app value to be set. This app value is added as a tag to all resources on the stack and a getter is added to return either the string or throw an error if the app is not set.
This change means existing stacks can pass the app prop through instead of setting the tags themselves. It is a non-breaking change. 
Create a new stack with the `app` prop set and check that the tag is correctly applied to all resources. 
Resources are all tagged with the relevant app with less effort for users. 
n/a
n/a
=> Add an optional app prop to GuStack

src/constructs/ec2/security-group.test.ts
This PR adds tests for the security group constructs. The GuVpc static functions are _not_ tested as they can't be asserted directly and indirect/implicit testing predominantly tests the behaviour of the aws cdk library. 
No.
Run the test suite and see the new tests pass.
Good coverage of the ec2 module.
n/a
n/a
=> Add tests for security group constructs

src/constructs/core/stack.ts
This PR adds getters for the `stack` and `stage` values in `GuStack` so that it is possible to use `this.stack` or `this.stage` directory rather than having to add `valueAsString` everywhere. This also means that once #30 is merged, the `GuStack` will have a consistent interface for accessing stack, stage and app.
Yes, everything that uses `this.stage.valueAsString` or `this.stack.valueAsString` at the moment will need to be updated.
n/a
Slightly less typing is required to use the stack and stage values.
n/a
n/a
=> Add getters for stack and stage values

src/constructs/autoscaling/asg.test.ts, src/constructs/autoscaling/asg.ts, src/constructs/core/parameters.ts, src/constructs/iam/policies.ts
This addresses a number of TODOs in the repository, specifically:
1. Adds an `overrideId` prop to `GuAutoScalingGroup`, rather than overriding by default
2. Extracts the SSM run command policy statement to its own variable so it can be used elsewhere in the future
3. Extracts the allowGetObjectPolicyStatement to its own variable for same reasons as above
Yes, it looks like [a few repositories](https://github.com/search?q=new+GuAutoScalingGroup+user%3Aguardian&type=code) will need to be updated in order to take the GuAutoScalingGroup change into account.
`yarn test` from root of the repository.
The repository is cleaner (and littered with fewer TODOs) and our `GuAutoScalingGroup` construct is more consistent with the rest of the constructs.
We need to make sure we migrate the affected …
=> Add overrideId prop to GuAutoScalingGroup and refactor for TODOs

src/constructs/core/stack.ts
The compiler hinted at this and it makes sense. No impact to anything as nothing is using the fields in their current `protected` state.
=> tweak private properties of GuStack

src/constructs/loadbalancing/elb.test.ts, src/constructs/loadbalancing/elb.ts
This PR adds an `overrideId` prop to `GuApplicationLoadBalancer `, rather than overriding by default.
Yes, it looks like just the [one](https://github.com/guardian/deploy-tools-platform/blob/14d392c29405ef53a0a9d0ad930090442e92400b/cdk/lib/grafana/grafana-stack.ts#L191) usage needs to be updated.
`yarn test` from root of the repository.
The repository is cleaner and our `GuApplicationLoadBalancer` construct is more consistent with the rest of the constructs.
=> Make overrideId optional for GuApplicationLoadBalancer

README.md, docs/001-general-usage.md, docs/002-starting-a-new-project.md, docs/003-migrating-existing-stacks.md, docs/004-tips-tricks-and-gotchas.md, docs/architecture-decision-records/000-template.md, docs/architecture-decision-records/001-constructs-and-patterns.md, docs/architecture-decision-records/002-component-constuctors.md, docs/architecture-decision-records/003-package-manager.md, docs/architecture-decision-records/004-testing.md, docs/architecture-decision-records/005-package-structure.md
This PR adds a `docs` dir with separate files for general usage, starting a new CDK project and migrating existing cloudformation to CDK. Grouping the docs into their own folder makes it easier to split the files out logically as we expand the documentation about the library. 
It also adds a folder of [Architecture Design Records (ADRs)](https://github.com/joelparkerhenderson/architecture_decision_record). These files are where we can document the decisions we make around any form of structure, architecture or approach. By documenting them in this way, we can preserve the thought process behind all of the decisions whilst also laying out formally the preferences for all developers working on the library. 
The folder contains a template and some initial ADRs covering decisions we've …
=> Update documentation and add ADRs

src/constructs/core/stack.test.ts, src/constructs/core/stack.ts, src/constructs/lambda/__snapshots__/lambda.test.ts.snap, src/constructs/rds/instance.test.ts, src/patterns/__snapshots__/instance-role.test.ts.snap, test/utils/simple-gu-stack.ts
For now, we do not support a multi-app stack so make `app` mandatory for simplicity.
Yes, as the signature of GuStack's constructor has changed.
n/a
Simpler code, for now?
We'll need to support multi-app stacks at some point, so this might cause a massive diff later.
n/a
=> make `app` mandatory in a GuStack

src/constructs/iam/policies/base-policy.test.ts, src/constructs/iam/policies/log-shipping.test.ts, src/constructs/iam/policies/s3-get-object.test.ts, src/constructs/iam/policies/ssm.test.ts, test/utils/attach-policy-to-test-role.ts, test/utils/index.ts
This PR adds a helper function which can be used when testing policies to add the policy to a test role. This is required as policies that are not added to roles do not get included in the stacks and therefore can't be tested. Providing a test helper means that each test does not have to create the role itself, reducing the amount of duplicated code.
No.
Run the test suite and ensure everything still passes
Less repeated code between tests
=> Add a test helper for policy tests

script/test, src/constructs/iam/policies/describe-ec2.test.ts, src/constructs/iam/policies/describe-ec2.ts, src/constructs/iam/policies/index.ts, src/constructs/iam/policies/parameter-store-read.test.ts, src/constructs/iam/policies/parameter-store-read.ts, src/patterns/__snapshots__/instance-role.test.ts.snap, src/patterns/instance-role.test.ts, src/patterns/instance-role.ts
https://github.com/guardian/cdk/pull/66 but w/out the `Try` as its not needed since https://github.com/guardian/cdk/pull/69.
Updates the standard permissions given to `InstanceRole`, adding:
- Permissions to read instance and ASG state - applications read these at launch for service or config discovery
- Permissions to read from parameter store, for config
This is after observing the verbosity within the [new Typerigther stack](https://github.com/guardian/typerighter/compare/setup-rule-manager-infrastructure). cc @jonathonherbert @SHession 
Yes, the stacks can be thinned out as more things come as standard.
See unit tests.
Reducing the boilerplate needed to define a CDK stack.
n/a
n/a
=> add more permissions to InstanceRole as standard, take 2

src/constructs/iam/policies/base-policy.ts, src/constructs/iam/roles.ts, src/constructs/loadbalancing/elb.ts
This PR makes two changes to simplify the code around default parameters:
1) Empty default parameter objects have been removed as they don't do anything
2) The `defaultParameters` object of the `GuApplicationListener ` has been removed in favour of including the params in the call to `super`. This reduces the number of ways that we do default props to two. See #79 for further discussion of how we should do default props.
No.
Run the test suite and see that nothing has changed.
We don't have redundant code and have fewer ways of including default props
=> Tidy up default props

src/constants/index.ts, src/constants/regex-pattern.test.ts, src/constants/regex-pattern.ts, src/constructs/core/parameters.test.ts, src/constructs/core/parameters.ts, src/constructs/iam/policies/__snapshots__/ses.test.ts.snap, src/constructs/iam/policies/ses.test.ts, src/constructs/iam/policies/ses.ts
Adds a new `GuSESSenderPolicy` construct which will:
- Add an `EmailSenderAddress` parameter to a `GuStack`
- Add an IAM policy to allow `ses:SendEmail` on that address
We have a few stacks that have this permission, each declare the policy in varying ways from [no restriction](https://github.com/guardian/anghammarad/blob/c919ebed337cb9be8653ac5ebf71ff2a6aa6990f/cloudformation/anghammarad.template.yaml#L40-L44) to [resource restricted](https://github.com/guardian/deploy-tools-platform/blob/1db44220323083ed89ef3fd03f8e1f27cfe2d390/cdk/lib/amiable/amiable.ts#L86-L92) to [condition restricted](https://github.com/guardian/editorial-tools-platform/blob/855ca76de244c9400c18a2ed9a34d428c99886fd/cloudformation/media-service-account/media-atom-maker/media-atom-maker.yaml#L786-L798).
After reading …
=> add an email sender policy

src/constructs/autoscaling/asg.ts, src/constructs/core/stack.ts, src/constructs/iam/policies/s3-get-object.ts, src/constructs/loadbalancing/elb.ts
This PR removes the remaining TODOs from the codebase in an effort to tidy up. Of the four PRs removed:
* One has been converted to a comment as there is no direct action required at the moment
* Two have been converted to [ideas](https://github.com/guardian/cdk/discussions/categories/ideas) as there is no clear solution at the moment
* One has an [open PR](https://github.com/guardian/cdk/pull/121)
=> Remove todos

src/constructs/loadbalancing/elb.test.ts, src/constructs/loadbalancing/elb.ts, src/constructs/rds/instance.test.ts, src/constructs/rds/instance.ts
This PR sets the `deletionProtection` value to true by default for the `GuDatabaseInstance` and `GuApplicationLoadBalancer` constructs. 
This change updates a default value which will have an effect on existing projects (once the version of the library is bumped). For most projects, this new default value should be a sensible change however in some cases, it may be necessary to override it. 
Two new unit tests cover the change. It could also be tested by applying it to a previously migrated stack.
Components which are risky to remove have deletion protection enabled by default.
There is a risk that this isn't a sensible default and either it is mistakenly set in many cases causing extra developer effort or it requires overriding in many cases.
=> Add deletion protection by default

package.json, src/constructs/loadbalancing/clb.test.ts, src/constructs/loadbalancing/clb.ts, src/constructs/loadbalancing/index.ts
This PR adds a new `GuClassicLoadBalancer` component which extends the `LoadBalancer` construct provided by the `@aws-cdk/aws-elasticloadbalancing` library. 
It adds three main pieces of functionality:
* A boolean value can be passed to the `overrideId` prop to remove the 8 digit hash added to the end of the logical id
* An array of values can be provided to the `deletionOverrideProperties` prop which will be passed to the `addPropertyDeletionOverride` method on the underlying `CfnLoadBalancer`. An enum is defined containing the acceptable values. This allows for properties to be remove to match existing implementations more easily
* An object of property names and values can be passed to the `overrideProperties` prop which will each be passed to the `addPropertyOverride` method on the …
=> Add GuClassicLoadBalancer

.eslintrc.js, eslint/README.md, eslint/index.js, eslint/package.json, eslint/rules/valid-constructors.js, package-lock.json, package.json, src/constructs/core/parameters.ts, src/constructs/core/stack.ts, src/constructs/ec2/security-groups.ts, src/constructs/iam/policies/log-shipping.ts, src/patterns/instance-role.test.ts, src/patterns/instance-role.ts
This PR creates a custom ESLint rule which is used to check that the constructors of all constructs and patterns follow the best practice laid out in the [ADR](https://github.com/guardian/cdk/blob/main/docs/architecture-decision-records/002-component-constuctors.md).
Any constructs breaking those rules have been updated. In all cases except one, this change is non-breaking.
The InstanceRole pattern has had an `id` parameter added which means that any stacks implementing it will need to be updated.
Yes! The InstanceRole pattern has now had an `id` parameter added to conform to the style guide. This means that any stacks implementing it will need to be updated.
Run the lint command to see if any errors are detected. Check a deliberate violation to see it catch things. 
The best practice …
=> Add a custom eslint rule to check the constructors

src/constructs/iam/policies/assume-role.test.ts, src/constructs/iam/policies/assume-role.ts
This PR adds a new `GuAssumeRolePolicy` which takes `resources` as a prop. This reduces the amount of code required to provide assume role permissions. 
No changes are required but existing stacks where a Policy grants assume role permissions may wish to migrate to this. 
Unit tests cover the new construct. Implementing it in place of a policy which grants this permissions in an existing stack shouldn't cause any changes when running the snapshot tests.
Fewer lines of code are required to define common policies.
=> Add GuAssumeRolePolicy

src/constructs/iam/policies/base-policy.ts, src/constructs/iam/policies/dynamodb.test.ts, src/constructs/iam/policies/dynamodb.ts, src/constructs/iam/policies/index.ts
Adds two DynamoDB policies using a different (and possibly simpler) format from existing policy constructs.
In https://github.com/guardian/cdk/pull/77 we made `GuPolicy` abstract to discourage usage of it. In that PR we noted that if one wanted to create a custom policy they still could by extending `GuPolicy`. In this PR we make that process easier with the addition of `GuAllowPolicy` and `GuDenyPolicy` constructs.
These new constructs have a super simple interface and the dynamodb constructs added in this PR demonstrate their usage.
No, but it would mean a load of refactoring of existing constructs to extend from `GuAllowPolicy`.
Observe CI. I've only added tests to the dynamo constructs as new policy constructs get tested implicitly as a result.
- A simpler interface to create policies …
=> Add DynamoDB read and write policies

src/constructs/iam/policies/assume-role.ts, src/constructs/iam/policies/base-policy.ts, src/constructs/iam/policies/dynamodb.ts
This PR update the `GuDynamoDBPolicy` class to pass through any additional props in the super call. It also omits the `statements` prop from the signature to prevent additional statements being added. As this same signature is used elsewhere, an new type is defined and used in both places.
No.
This can be tested by implementing in existing stacks and seeing that the snapshot tests still pass.
Policy constructs pass through additional props but don't allow additional statements to be added.
=> Update Policy Props

src/constructs/iam/policies/log-shipping.test.ts, src/constructs/iam/policies/log-shipping.ts, src/patterns/__snapshots__/instance-role.test.ts.snap, src/patterns/instance-role.test.ts, src/patterns/instance-role.ts
We've established best practice for accounts/stacks to define the kinesis stream to send logs to to be a SSM Parameter called `/account/services/logging.stream.name`.
This updates `GuLogShippingPolicy` to add the parameter to the stack within that construct. The construct is bringing its own resources with it, rather than being passed in as props. This makes it more self contained.
This builds on the BYO* pattern introduced in https://github.com/guardian/cdk/pull/91.
Yes! The signature of `InstanceRole` has changed to no longer require a stream name, but simply a `includeLogShipping` boolean.
- Observe CI?
Simpler interface to `InstanceRole` and more self contained constructs.
n/a
=> update GuLogShippingPolicy to bring it's own parameter

src/constructs/iam/policies/s3-get-object.test.ts, src/constructs/iam/policies/s3-get-object.ts, src/patterns/__snapshots__/instance-role.test.ts.snap, src/patterns/instance-role.test.ts, src/patterns/instance-role.ts
The changes in https://github.com/guardian/cdk/pull/137 were quite nice, this PR applies the same methodology to the policy that allows GETting a object from S3.
Creates a new `GuGetDistributablePolicy` construct to create an IAM policy allowing S3 GET from a distribution bucket. This construct also brings with it a SSM Parameter for the name of the bucket, defaulting to `/account/services/artifact.bucket`. This simplifies the props for `InstanceRole`, removing `bucketName`.
This PR also changes `GuGetS3ObjectPolicy` to extend from `GuAllowPolicy` which yields simpler code.
Yes. Now an `InstanceRole` is simpler to instantiate (`new InstanceRole(scope)` is sufficient).
Observe CI.
Simpler interfaces.
n/a
=> Create GuGetDistributablePolicy construct

src/constructs/core/parameters.test.ts, src/constructs/core/parameters.ts, src/constructs/iam/policies/log-shipping.ts, src/patterns/__snapshots__/instance-role.test.ts.snap
This PR updates the `GuParameter` to take a new `fromSSM` prop. If this prop is set to true then the `type` value will be wrapped with `AWS::SSM::Parameter::Value`. This means that all parameters extending the `GuParameter` can now be denoted as `fromSSM`. Due to the, the `GuSSMParameter` has been removed and the one case where it was used has been updated.
Yes. Anywhere that is currently using the `GuSSMParameter` will need to be updated to use another construct with the `fromSSM` value set to true.
New unit tests have been added to cover the exact functionality. The `GuLogShippingPolicy` was using `GuSSMParameter` and has been refactored so you can also see that it still produces the same cloudformation.
GuParameter constructs present a more consistent interface with regard to getting …
=> Allow all parameters to be from SSM

src/constructs/core/parameters.test.ts, src/constructs/core/parameters.ts, src/constructs/iam/policies/log-shipping.ts, src/constructs/iam/policies/s3-get-object.test.ts, src/constructs/iam/policies/s3-get-object.ts, src/patterns/__snapshots__/instance-role.test.ts.snap
This PR updates the `GuParameter` to take a new `fromSSM` prop. If this prop is set to true then the `type` value will be wrapped with `AWS::SSM::Parameter::Value`. This means that all parameters extending the `GuParameter` can now be denoted as `fromSSM`. Due to the, the `GuSSMParameter` has been removed and the one case where it was used has been updated.
Yes. Anywhere that is currently using the `GuSSMParameter` will need to be updated to use another construct with the `fromSSM` value set to true.
New unit tests have been added to cover the exact functionality. The `GuLogShippingPolicy` was using `GuSSMParameter` and has been refactored so you can also see that it still produces the same cloudformation.
GuParameter constructs present a more consistent interface with regard to getting …
=> Add SSM prop to GuParameter

.github/workflows/cd-docs.yaml, .gitignore, README.md, package-lock.json, package.json, script/docs, script/release, script/release-docs, typedoc.js
[TypeDoc](https://typedoc.org/) will generate a documentation site which we can publish to GitHub Pages.
A new `script/docs` script is added to view docs locally and `script/release` is updated to run [`gh-pages`](https://www.npmjs.com/package/gh-pages) to publish the generated site to GitHub Pages.
No.
- Checkout branch
- Run `script/docs`
Published documentation 🎉 .
This will also encourage us to annotate our code properly, as noted [here](https://github.com/guardian/cdk/pull/137#discussion_r556698030).
n/a
=> add TypeDoc to project

src/constructs/ec2/vpc.ts
This PR adds a new `fromIdParameter` method to the `GuVpc` class. This method will create a new parameter for the VpcId and use this to return the reference to the VPC to be used throughout the stack.
No changes are required but existing stack may migrate to the new method to reduce the amount of code required.
Migrate an existing stack to the method and run the snapshot tests.
Fewer parameters have to be defined manually.
=> Add BYO pattern to GuVpc

.github/workflows/cd-docs.yaml
Following https://github.com/guardian/cdk/pull/148, it looks like releases and tags are different concepts in GitHub, even though, confusingly, tags show up on https://github.com/guardian/cdk/releases.
It looks like our release process is currently only creating tags and NOT creating releases. As a result, this change tweaks the GH Action to update docs on _tag_ creation.
We'll likely add semantic-release to this library, which does in fact create releases, but this is a little far away.
No.
n/a
Docs are updated automatically when a tag is created.
n/a
=> update the GH Action trigger

package.json
The gh-pages command needs to explicitly know the user performing an action, so tell it.
Inspired by https://github.com/guardian/tools-index/pull/75/files.
=> set user for gh-pages

src/constructs/ec2/security-group.test.ts, src/constructs/ec2/security-groups.ts
A simple construct to abstract away a common requirement of open access to port 443.
This would mean [this](https://github.com/guardian/typerighter/blob/fc029ed8d493a782d9d658be1fbfa0418ffc9a51/cdk/lib/rule-manager/rule-manager.ts#L84-L93) can be removed.
Yes - [Typerighter](https://github.com/guardian/typerighter/blob/fc029ed8d493a782d9d658be1fbfa0418ffc9a51/cdk/lib/rule-manager/rule-manager.ts#L84-L93) becomes a bit thinner.
See tests.
One more common construct provided by this library.
n/a
=> adds GuPublicInternetAccessSecurityGroup construct

src/constructs/core/stack.ts, src/constructs/loadbalancing/clb.test.ts, src/constructs/loadbalancing/clb.ts, src/constructs/loadbalancing/elb.test.ts, src/constructs/loadbalancing/elb.ts, src/constructs/rds/instance.test.ts, src/constructs/rds/instance.ts, test/utils/simple-gu-stack.ts
This PR adds a new `migrated`  prop to the `GuStack`. This prop can be set to true to denote that a stack has been migrated from a cloudformation template. Other constructs can then modify their behaviour where that is the case. 
Currently, the only implementation is in the `GuApplicationLoadBalancer`, `GuApplicationListener`, `GuApplicationTargetGroup`, `GuClassicLoadBalancer` and `GuDatabaseInstance` constructs. If the `migrated` value is true and the override id prop is _not_ false then the override id logic will be invoked. The overrideId prop has been left for cases outside of the default where the id still needs to be constant. Including the `&& props.overrideId !== false` condition means that it is also possible to explicitly override the default behaviour for a migrated stack if …
=> Add migrated prop to GuStack

src/constructs/ec2/vpc.ts
This PR updates the default path of the VPC parameter created by the `fromIdParameter` to be `/account/vpc/primary/id` to discourage the use of the default VPC. 
See thread here: https://github.com/guardian/cdk/pull/149#discussion_r558843564
Any stacks using this method already will have the ensure the value is set at the new path. Although, to my knowledge, nothing is using it yet.
Implement this method in an existing stack and view that changes by running the snapshot test.
People are discouraged from using the default VPC.
=> Update default VPC parameter path

README.md
This PR updates the README to:
* Point users towards the discussions section if they want to engage with us 💬 
* Points users specifically towards the ADRs directory if they're interested in architecture 🏛️ 
No.
The README points people to the best places to find more information on each topic.
=> Add notes about discussions and ADRs to README

docs/005-default-parameter-store-locations.md
A number of constructs now "bring their own" parameters and read from "standard" locations in parameter store. To make it easier for a user to see all of the default paths, this PR adds a new file to the docs which contains a table listing them.
(See discussion thread: https://github.com/guardian/cdk/discussions/175#discussioncomment-293101)
No.
The account configuration required to use constructs from the library is explained clearly in documentation.
=> Add doc with default SSM paths

src/constructs/ec2/security-group.test.ts, src/constructs/ec2/vpc.test.ts
This PR makes some small updates to the tests in `constructs/ec2`
* Add some basic tests of the `GuVpc` class
* Rename the tests for the `GuPublicInternetAccessSecurityGroup` class
No
Run the updates test suite
All constructs have relevant tests
=> Update EC2 tests

docs/005-default-parameter-store-locations.md, src/constructs/ec2/vpc.test.ts, src/constructs/ec2/vpc.ts
This PR adds a new `subnetsFromParameters` method to the `GuVpc` class which follows the bring-your-own-parameter pattern. The function takes a props object which contains an optional type to denote whether the subnets are public or private. The parameter is set accordingly.
No change is required but stacks using the `subnets` method and defining the parameter explicitly can now update.
Implement this in place of the `subnets` function in an existing stack.
More constructs bring their own parameters, reducing the amount of code required to define a stack.
=> Add subnetsFromParameter method

src/constructs/loadbalancing/clb.test.ts, src/constructs/loadbalancing/clb.ts
This PR introduces a static `DefaultHealthCheck` object to the `GuClassicLoadBalancer` which is merged with the provided props. This allows either the entire object or individual values to be omitted (see new test cases for examples). 
No changes are required however stacks that implement the `GuClassicLoadBalancer` can reduce the number of props they pass in. 
Upgrade an existing stack and remove an healthCheck values which are the same as the default value. The snapshot tests should still pass, confirming that nothing in the output has changed.
Fewer lines of code are required to define load balancers and best practice around CLB health checks comes for free.
=> Add default health check values for CLB

README.md
This PR removes a duplicated heading and makes the `Decisions Records` heading an h3, inline with the others in that section.
No
=> Tweak README formatting

src/constructs/autoscaling/asg.test.ts, src/constructs/autoscaling/asg.ts
This PR updates the `GuAutoscalingGroup` class to follow the bring-your-own-parameter pattern by adding the `InstanceType` and `AMI` parameters within the constructor.
Yes. Existing stacks that use the `GuAutoscalingGroup` will be able to remove the manually configured parameters. Where parameter names differ, this will have to be updated.
Update an existing stack to use the new `GuAutoscalingGroup` and run the snapshot tests. This should general no or minimal changes.
Less code is required to configure constructs that always require parameters.
=> ASG adds instanceType and AMI parameters

src/constructs/lambda/__snapshots__/lambda.test.ts.snap, src/constructs/lambda/lambda.test.ts, src/constructs/lambda/lambda.ts
Whilst testing https://github.com/guardian/cdk/pull/186, I noticed that `memorySize` and `timeout` are optional parameters for a `GuLambda`. If these values are omitted, CloudFormation defaults to [128MB](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-memorysize) and [3 seconds](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-timeout), respectively.
I don't think that these default values are particularly helpful for many of the Guardian use-cases that I've seen (they are especially unhelpful for Scala lambdas!), so I've tried to suggest something more appropriate.
There are no required changes, but some projects may automatically increase the memory …
=> Provide sensible defaults for GuLambda memorySize and timeout

package.json
Recently ran `./script/setup` and saw a few warnings (see below). This fixes the `prepublish` deprecation warning and the missing repository field warning. There's a third warning about a missing license field, but I'm not sure what license we need.
I vaguely remember us having issues with `prepare` in the past, however I think that when we were installing directly from GitHub rather than NPM, so this should be ok.
<details>
<summary>Original terminal output</summary>
```console
➜ ./script/setup
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
> …
```
=> Fixes 2 warnings from npm

package-lock.json, package.json, src/constructs/ec2/vpc.ts
Updates AWS CDK to the [latest version](https://github.com/aws/aws-cdk/releases) (latest at time of writing!). This is to keep up to date.
I think so. As `peerDependencies` are not installed (unless on npm@7), we'd need to ensure dependant projects' version of AWS CDK match this.
CI should suffice.
Keeping up to date.
n/a
=> bump aws-cdk to current latest version

.github/workflows/ci.yaml, package-lock.json, package.json, script/check-aws-cdk, script/update-aws-cdk
We introduced dependabot in #55 to keep our dependencies up to date. However dependabot doesn't report against the CDK libraries (related https://github.com/dependabot/dependabot-core/issues/1171).
This adds a fairly gnarly bash script to:
- List all versions of `@aws-cdk/core` (and assume it's ordered!)
- Use `jq` to find how out of date we are
- If we are 5* versions out of date, exit 1
This is all run in CI.
Also takes inspiration [from Source](https://theguardian.design/2a1e5182b/p/876251-getting-started/t/06dcf1) and uses [`npm-check-updates`](https://www.npmjs.com/package/npm-check-updates) to update the `@aws-cdk/*` libraries. All wrapped in a new `update-aws-cdk` script.
Related to https://github.com/guardian/cdk/pull/191.
*this was an arbitrary choice, we can tweak as needed …
=> check age of aws-cdk/core during ci

src/constructs/loadbalancing/elb.test.ts, src/constructs/loadbalancing/elb.ts
Following on from https://github.com/guardian/cdk/pull/184, this PR adds some default values for the `healthCheck` prop on the `GuTargetGroup` construct. For consistency, the default values are the same as defined for the `GuClassicLoadBalancer`. The default values are spread with any passed in so that you can do the following:
```ts
new GuTargetGroup(this, "TargetGroup", {
...
healthCheck: {
port: "3000"
}
...
})
```
No changes are required but stacks the use the `GuTargetGroup` can reduce the number of props they have to pass in.
Update an existing stack that implements the `GuTargetGroup` and remove any props that match the defaults. Run the snapshot test and confirm that it still passes.
Stacks implementing the `GuTargetGroup` get sensible default health check values for free.
The …
=> Add default health check values for GuTargetGroup

src/constructs/loadbalancing/clb.test.ts, src/constructs/loadbalancing/clb.ts
This PR adds a new `GuHttpsClassicLoadBalancer` construct which sets defaults for the load balancer listener. It restricts the number of listeners to one with the following defaults:
```ts
InstancePort: "9000",
InstanceProtocol: "http",
LoadBalancerPort: "443",
Protocol: "https",
```
If a value for the `sslCertificateId` prop is not provided, it also creates a new parameter and sets the output of that as the prop value.
No changes are required but stacks which implement the `GuClassLoadBalancer` and have an HTTPS listener can reduce the number of props they provide.
Migrate an existing stack to use the `GuHttpsClassLoadBalancer` and run the snapshot test to confirm that nothing has changed.
Stacks can define fewer props to get a standard load balancer which listens for HTTPS traffic
=> Add GuHttpsClassicLoadBalancer

src/constructs/autoscaling/asg.test.ts, src/constructs/autoscaling/asg.ts
This PR updates the type of the parameter created auto-magically in the `GuAutoscalaingGroup` to be a `GuAMIParameter`. Using this parameter changes the `Type` value to `AWS::EC2::Image::Id` which will restrict the values that can be input, offering better validation.
This change will update the parameter anywhere it is currently used which will be seen at deploy time. Given that an invalid value would have caused the deploy to fail, this shouldn't have any effect.
See the updated unit test and verify that it passes.
Better validation of parameter values.
=> Update AMI parameter

src/constructs/iam/roles/instance-role.ts
This PR updates the import of `GuRole` in the `instance-role.ts` file to import directly from the `roles.ts` file rather than the `index.ts` in the `roles` directory as this was causing an error when importing anything from `@guardian/cdk/lib/constructs/iam`. 
Any projects importing `GuInstanceRole` or `GuRole` from their specific file will now be able to get them from the `@guardian/cdk/lib/constructs/iam` path.
Bump to the latest version and try importing the `GuInstanceRole` construct from `@guardian/cdk/lib/constructs/iam`
All imports work as expected.
=> update GuRole import in instance role

src/constructs/autoscaling/asg.test.ts, src/constructs/autoscaling/asg.ts
Currently the `GuAutoscalingGroup` creates parameters for the `imageId` (`AMI`) and `instanceType` values and omits the props. This PR adds the props back in as optional and only creates the parameters if no value is passed. This maintains the BYO pattern as the default behaviour but allows flexibility where required.
No
New unit tests have been written to cover the change in behaviour.
The default behaviour of our constructs makes them easy to use but also allows for flexibility.
=> Allow imageId and instanceType to be passed into ASG

README.md
Adding a couple of notes for forgetful people like me! Obviously this isn't a great process, but at least the docs are now complete. Hopefully we can automate it and avoid these tedious steps soon!
=> docs: Document release-related chores!

jest.config.js, jest.setup.js, src/constants/__mocks__/library-info.ts, src/constants/library-info.ts, src/constructs/cloudwatch/__snapshots__/lambda-alarms.test.ts.snap, src/constructs/core/stack.test.ts, src/constructs/core/stack.ts, src/constructs/iam/policies/__snapshots__/ses.test.ts.snap, src/constructs/iam/roles/__snapshots__/instance-role.test.ts.snap, src/constructs/lambda/__snapshots__/lambda.test.ts.snap, src/constructs/rds/instance.test.ts, src/patterns/__snapshots__/scheduled-lambda.test.ts.snap, src/patterns/__snapshots__/sns-lambda.test.ts.snap, tsconfig.json
Adds `X-Gu-CDK-Version` tag to `GuStack`. We can use this to track which stacks have been created using the library, and with which version. Adding the tag to `GuStack` means it'll get applied to all resources.
The absence of this tag suggests the stack hasn't been created with the cdk library. Using the version number allows us to track how up to date stacks are too.
We mock the library version in tests to remove having to update snapshots whenever we publish a new version of the library, which, among other things, would make automated publishing difficult! The mock is applied globally for simplicity.
Yes! The change is small though, it should be a matter of bumping the version of this library being used.
Observe existing tests.
We know what version of this library was used to create a …
=> feat: Add `X-Gu-CDK-Version` tag to GuStack

package-lock.json, package.json, src/constants/library-info.ts, tsconfig.json
Previously (in #223 and [v0.32.0 of this library](https://github.com/guardian/cdk/releases/tag/v0.32.0)) we read the version number from `package.json` by reading from a specific file path. To do this we had to set `resolveJsonModule` to `true`.
This resulted in `lib` ([the output directory for TypeScript](https://github.com/guardian/cdk/blob/6c19e431055d3348b107e69a28a5476e4a319d3e/tsconfig.json#L17) and [entry point of the library](https://github.com/guardian/cdk/blob/6c19e431055d3348b107e69a28a5476e4a319d3e/package.json#L4)) going from:
```console
lib
|_index.js
|_package.json
```
to:
```console
lib
|_src
| |_index.js
| |_package.json
|_package.json
```
Note the extra `src` subdirectory. This impacts import statements. From:
```typescript
import { GuAutoScalingGroup } from …
```
=> fix: package layout and content

README.md, script/release
We use `np` to orchestrate the publication of a module to NPM. One of the steps `np` performs is a commit to edit `package.json`'s `version`.
As we have branch protection enabled for `main`, we have to raise a PR to get this commit in. Automate this process in the release script as it's pretty boring!
This change checks one has the [GitHub CLI](https://cli.github.com/) installed and raises a PR if it can.
Related https://github.com/guardian/cdk/pull/229/files#r570193715
This is still a stop gap until we have semantic-release or similar in the project.
No.
Create a release?
More automation = less thinking = fewer mistakes!
n/a
=> chore: further automate release process

src/patterns/scheduled-lambda.ts
Adds some documentation which should have been included in https://github.com/guardian/cdk/pull/186!
No.
Run `./script/docs` and have a look at the new docs!
Users of this library should have a better understanding of how to use the scheduled lambda pattern.
N/A
=> docs: Add basic docs for scheduled lambda pattern

src/constructs/cloudwatch/__snapshots__/lambda-alarms.test.ts.snap, src/constructs/core/stack.test.ts, src/constructs/core/stack.ts, src/constructs/iam/policies/__snapshots__/ses.test.ts.snap, src/constructs/iam/policies/parameter-store-read.test.ts, src/constructs/iam/policies/s3-get-object.test.ts, src/constructs/iam/roles/__snapshots__/instance-role.test.ts.snap, src/constructs/lambda/__snapshots__/lambda.test.ts.snap, src/constructs/rds/instance.test.ts, src/patterns/__snapshots__/scheduled-lambda.test.ts.snap, src/patterns/__snapshots__/sns-lambda.test.ts.snap, test/utils/simple-gu-stack.ts
As we look to reduce the number of parameters requiring manual updating and maintaining in CFN, this allows library users to hard-code stack and stage variables so we can reason with their values in other parts of the codebase.
If a user would like to avoid having the stack and stage as tokens (which later gets resolved at deployment by writing the values in the CFN UI), you could now simply state these values in the stack declaration:
```typescript
const stack =  new GuStack(new App(), "Test", { app: "testing", stack: "deploy", stage: "CODE" });
```
Since we don't often (or ever) write stage-specific CDK declarations, I expect the `stage` prop will not be used often. However, being able to provide the `stack` as a hardcoded string I think provides value in a) having more configuration …
=> feat(stack): GuStack accepts Stack value as prop

src/constants/regex-pattern.test.ts, src/constants/regex-pattern.ts, src/constructs/core/parameters.ts, src/constructs/loadbalancing/elb.test.ts, src/constructs/loadbalancing/elb.ts
`GuCertificateArnParameter` has an allowed pattern of an ACM ARN string. Update `GuHttpsApplicationListener` to use it and validate the certificate prop too.
No.
See updated tests and CI output.
Fewer errors as user input is restricted via the regex.
n/a
=> feat: create a GuCertificateArnParameter construct

src/constructs/core/parameters.test.ts, src/constructs/core/parameters.ts, src/constructs/core/stack.test.ts, src/constructs/core/stack.ts
https://github.com/guardian/cdk/pull/65, but for parameters.
Helper functions to get/set parameters on the GuStack. An `Error` is thrown when getting a parameter that hasn't been set; this is to catch the error at compile time.
This is useful for when a construct reads from a parameter but isn't responsible for adding the parameter. For example, reading the `DistributionBucketName` param in the user data, where `DistributionBucketName` is added by [`GuGetDistributablePolicy`](https://github.com/guardian/cdk/blob/390a734dbfe228028581b172f1e920b3e223862e/src/constructs/iam/policies/s3-get-object.ts#L16) via [`GuInstanceRole`](https://github.com/guardian/cdk/blob/390a734dbfe228028581b172f1e920b3e223862e/src/constructs/iam/roles/instance-role.ts#L30). One such example can be seen …
=> feat: add parameter helper functions on GuStack

src/constructs/core/parameters.ts, src/constructs/iam/policies/s3-get-object.test.ts, src/constructs/iam/policies/s3-get-object.ts, src/constructs/iam/roles/__snapshots__/instance-role.test.ts.snap
`GuGetDistributablePolicy` is a policy that allows the Instance Profile to download artefacts from S3.
Currently, it has `s3:GetObject` permissions to `bucket/*`. This is pretty wide!
This PR follows the principal of least privilege and grants `s3:GetObject` permissions to `bucket/stack/stage/app/*` only.
We're also creating a standalone `GuDistributionBucketParameter` with a static field to remove magic strings and make it easier to reference ([see Prism's stack](https://github.com/guardian/prism/blob/0602058ccd349ca6c137777e6cb9e1e908cc6325/cdk/lib/prism.ts#L49)).
This is a breaking change, as denoted by the `!` in the PR title: see risk section below for detail.
Yes. With the The IAM policy changes, we need to ensure the artefact is in the correct location.
See tests.
Following the …
=> feat!: tighten GuGetDistributablePolicy's access

src/constructs/autoscaling/asg.test.ts, src/constructs/autoscaling/asg.ts, src/constructs/core/index.ts, src/constructs/core/mappings.ts, src/constructs/core/stack.ts, test/utils/synthed-stack.ts
Since Guardian stacks typically use the same CFN template for different stages (e.g. `CODE` or `PROD`), we often need a way to provide different values to a template depending on which stage is being CloudFormed. For example, many applications use fewer ec2 instances in `CODE` (needs to handle minimal test traffic) than they do in `PROD` (needs to cope with real production workloads). Unfortunately, stage is passed into templates via a parameter which means that it's not available at build-time. Consequently, we cannot simply use TypeScript logic to conditionally change values. 
This PR adds functionality for defining (non-secret) values which differ depending on stage, without forcing library users to think about CFN concepts like `Parameters` or `Mappings` and without requiring them to …
=> feat!: Implement stage dependent ASG capacity via Mappings

src/constructs/autoscaling/asg.test.ts, src/constructs/autoscaling/asg.ts, src/constructs/ec2/security-group.test.ts, src/constructs/ec2/security-groups.ts
Simplify how to define security groups in `GuAutoScalingGroup`. Currently, we can specify `securityGroup` (singular) _and_ `securityGroups` (multiple), where `securityGroup` overrides the [default one](https://github.com/aws/aws-cdk/blob/296a10d76a9f6fc2a374d1a6461c460bcc3eeb79/packages/%40aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts#L913-L916) provided by AWS.
In this PR, we set the default security group to allow outgoing traffic on port 443 (https); this is tighter than AWS's default.
By setting the default security group, the props for `GuAutoScalingGroup` no longer needs the `securityGroup` field 🎉 .
Lastly, we're renaming `securityGroups` to `additionalSecurityGroups` to be more explicit; this is inspired by [`GuInstanceRole`](https://github.com/guardian/cdk/blob/974d1a864252e8d …
=> feat!: refactor security groups in GuAutoScalingGroup

src/constructs/autoscaling/asg.test.ts, src/constructs/autoscaling/asg.ts, src/constructs/autoscaling/index.ts, src/constructs/autoscaling/user-data.ts
Update the type of `userData` in `GuAutoScalingGroup` to be `UserData | string`. This allows it to be more strongly typed.
A side-effect of this change is hard coding the `osType` to linux. Currently all our stacks run a flavour of linux, so this shouldn't be too controversial. There are ambitions from InfoSec and Enterprise to run Windows machines in AWS, however I think we can cross that bridge when we come to it as it'll likely mean other tools, such as AMIgo, need updating too.
This change also paves the way auto generating the user data for the most basic launch configurations of:
- Download config
- Download artefact
- Run artefact
This will be added in a subsequent PR - https://github.com/guardian/cdk/pull/269.
No mandatory, but we can change the type of `userData`.
Existing tests …
=> feat: tweak type of GuASG's userData

src/constructs/autoscaling/asg.test.ts, src/constructs/autoscaling/user-data.test.ts, src/constructs/autoscaling/user-data.ts
Following the change in #267 , introduce a way to autogenerate user data for the ideal scenario of:
- download config
- download distributable
- run distributable
This is part of a wider task of creating an EC2 based pattern.
No.
See added tests.
For the simplest use case, the library has an easier API.
n/a
=> feat: auto generating UserData

.github/workflows/ci.yaml, script/ci
This change updates the GHA for CI to run a single script in the repo. Whilst this results in running steps in sequence, and thus a potential to increase runtime, it makes things easier to reason about.
This becomes particularly apparent when needing to add a GHA job that depends on others completing, for example [post-release-action](https://github.com/guardian/cdk/pull/271).
No.
CI should continue to function.
https://github.com/guardian/cdk/pull/271 becomes simpler.
n/a
=> chore: simplify CI to run a single script

.github/workflows/cd.yaml
#275 was our first fully automated release 🎉 , well _almost_ fully automated as the [docs](https://guardian.github.io/cdk/) were not updated (it should be on [v0.38.1](https://github.com/guardian/cdk/tags)). We update docs via an Action triggered on new tag creation. However as the [default token given to Actions doesn't trigger other Actions](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token), the docs were not updated.
To fix this we can use a custom GH token, which should trigger the docs Action.
Also renames the custom token supplied to `post-release` for clarity as it's the same value.
No.
n/a
Docs get updated upon new releases.
n/a
=> chore: fix auto-generation of docs

src/constructs/iam/policies/cloudwatch.test.ts, src/constructs/iam/policies/cloudwatch.ts, src/constructs/iam/policies/index.ts
Two simple constructs to allow the GETing and PUTing of Cloudwatch metrics. This will allow us to further DRY out templates such as Grafana which defines a custom policy.
I suspect the PUT policy will soon get added to the standard policies given to our [instance role](https://github.com/guardian/cdk/blob/98c95f94cebab71f1943a6c7a2e1900b6c11e9d4/src/constructs/iam/roles/instance-role.ts#L28-L35), possibly behind a flag similar to `GuLogShippingPolicy`. Will create this as it's own PR for clarity.
Yes. They can be thinned out a little!
See added tests.
More constructs means shorter consumer templates!
n/a
=> feat: Constructs to create IAM policies for Cloudwatch GET and PUT

src/constructs/sns/index.ts, src/patterns/sns-lambda.ts
This simplifies import statements and also makes the sns namespace(?) consistent to others.
Going from:
```typescript
import { GuSnsTopic } from "@guardian/cdk/lib/constructs/sns/sns-topic"
```
To:
```typescript
import { GuSnsTopic } from "@guardian/cdk/lib/constructs/sns"
```
No.
n/a
Consistency.
n/a
=> fix: add module index for sns

.github/workflows/cd.yaml
In #291  and #282 we removed the standalone workflow for updating the documentation site. We didn't carry over all the configuration in to the main `cd.yaml` workflow. This fixes that and is hopefully the end of this saga!
This fixes the build on `main` - https://github.com/guardian/cdk/actions/runs/610507981.
No.
Merge it and see?
Docs get deployed automatically again.
n/a
=> chore: configure gh-pages

src/constructs/iam/policies/ssm.test.ts, src/constructs/iam/policies/ssm.ts
`GuAllowPolicy`'s signature makes it really simple to create policies, let's use it to DRY out `GuSSMRunCommandPolicy`.
No.
Existing tests should continue to pass.
DRY.
n/a
=> refactor: make SSM policy extend GuAllowPolicy for DRYness

.github/workflows/cd.yaml, .github/workflows/ci.yaml
As of https://github.com/guardian/actions-merge-release-changes-to-protected-branch/pull/6, the `post-release-action` was renamed to `actions-merge-release-changes-to-protected-branch`. This PR changes the name in the workflow files here.
No.
Raise a PR and merge to main. See that the CI and CD workflows work as expected.
CI and CD continues to work as expected
=> chore: rename post-release-action

README.md
Removes instructions for manual release steps from README. Also updates code snippets to use an actual pattern that exists in the library.
See https://github.com/guardian/cdk/pull/271.
No.
Look at the changes - https://github.com/guardian/cdk/blob/aa-readme/README.md?
Keeping up to date.
n/a
=> chore(docs): update readme to reflect new release process

.github/workflows/ci.yaml
This repository uses the [amannn/action-semantic-pull-request action](https://github.com/amannn/action-semantic-pull-request) to validate that pull request titles conform to the angular commit convention. This action provides an additional option to validate the commit message if a PR only has one commit as this commit message will be the suggested one when squashing and merging. This PR turns that setting on.
Open a single commit PR with an invalid commit and see the check fail.
Reduced risk of incorrect semantic release behaviour.
=> chore: enable validateSingleCommit setting

src/constructs/ec2/security-groups.ts, src/utils/security-groups/helpers.test.ts, src/utils/security-groups/helpers.ts, src/utils/security-groups/index.ts
We [now have code related to different constructs/patterns](https://github.com/guardian/cdk/pull/296#discussion_r590455719) in `utils`, so the code related to security groups is better placed in its own subdirectory.
=> refactor: Move security groups util code

src/constructs/autoscaling/user-data.test.ts, src/constructs/autoscaling/user-data.ts, src/constructs/core/parameters/s3.ts, src/constructs/iam/policies/s3-get-object.test.ts, src/constructs/iam/policies/s3-get-object.ts, src/constructs/iam/roles/instance-role.test.ts, src/utils/ec2/index.ts, src/utils/ec2/private-config.ts
This refactor allows us to specify information about private configuration at the pattern-level. It seems necessary to do this because two separate constructs (`GuUserData` and `GuInstanceRole`) both need this same information. Similarly, we want users to pass the private config bucket name in via a parameter (we don't want bucket names in public GitHub repos) and we must only define this parameter once.
The EC2 app pattern props will take `privateS3Configuration` as an optional prop:
```typescript
export interface GuEc2AppProps {
privateS3Configuration?: GuPrivateS3ConfigurationProps
// other props
}
```
If this prop is defined, we'll be able to wire it through into `GuUserData`. We'll also be able to create the appropriate IAM policies via `GuInstanceRole`'s `additionalPolicies` prop …
=> refactor!: Share private config interface so it can be used by EC2 Pattern

typedoc.js
This fixes the documentation for all code in the `utils` directory, which was broken by https://github.com/guardian/cdk/pull/315 (and overlooked when implementing https://github.com/guardian/cdk/pull/296/commits/6672cce9b712fbfb5a035d6df033ddc499c0b04c).
No
Run `./script/docs` and confirm that everything works as expected.
There should be no missing docs/broken links after merging this change.
N/A
=> docs: Fix documentation for utils directory

src/constructs/ec2/security-group.test.ts, src/constructs/ec2/security-groups.ts, src/utils/security-groups/helpers.test.ts, src/utils/security-groups/helpers.ts
This hopefully creates a simpler interface to defining security group ingress and egress rules. Now, to define an ingress or egress rule we provide a `SecurityGroupAccessRule`.
`SecurityGroupAccessRule` has three mandatory fields:
1. `range` which is the CIDR range
2. `port` which is the port number and protocol (tcp by default)
3. `description` to provide some useful information to the reader viewing the security group in the AWS console
Example usage:
```typescript
new GuSecurityGroup(stack, "FtpAccessSecurityGroup", {
vpc,
ingresses: [
{ range: Peer.anyIpv4(), port: 21, description: "Allow FTP access from the world" },
],
});
```
BREAKING CHANGES:
`CidrIngress` and `CidrEgress` have been removed in favour of a single `SecurityGroupAccessRule`. This change forces a description to be …
=> refactor: create a simpler interface for defining security group rules

.github/workflows/cd.yaml, .github/workflows/ci.yaml
The [guardian/actions-merge-release-changes-to-protected-branch](https://github.com/guardian/actions-merge-release-changes-to-protected-branch) action now has a `v1.0.0` release. This PR updates the workflow files to use this, rather than pulling in from the `main` branch.
No
Merge a PR and confirm that the auto publish process still works as expected
The auto publish process continues to work as expected but now the repository has control over the version of the action used.
=> chore: use v1.0.0 of release action

package-lock.json, package.json
Users of this library don't need semantic-release to use it, so move it. IIUC devDependencies are not installed transitively, whereas dependencies are, so this change keeps things clean for users of this library.
This looks to be the cause for the big diff in [this PR](https://github.com/guardian/prism/pull/155/files):
No.
n/a
Faster install times?
n/a
=> fix(deps): move semantic-release to devDependencies

package-lock.json, package.json
According to [these docs](https://github.com/commitizen/cz-cli#making-your-repo-commitizen-friendly), we haven't made our repository commitizen-friendly. This PR merges in the result of running `commitizen init cz-conventional-changelog --save-dev --save-exact` on the repo and setting up basic config.
This will enable everyone to use the proper commitizen cli in the CDK repo with `cz`, `git cz` or `npm cz`.
Nope.
In the root of the repo, run `npx cz` and see the interactive menu work!
We can use `npx cz` with ease!
=> chore: make the repo commitizen-friendly

src/constructs/core/parameters/log-shipping.ts, src/constructs/iam/policies/__snapshots__/log-shipping.test.ts.snap, src/constructs/iam/policies/log-shipping.test.ts, src/constructs/iam/policies/log-shipping.ts, src/constructs/iam/roles/instance-role.ts, test/utils/attach-policy-to-test-role.ts
This is ultimately part of https://github.com/guardian/cdk/pull/332.
This policy is now a [singleton](https://en.wikipedia.org/wiki/Singleton_pattern) as we only ever want one per stack. If there are multiple roles defined in this stack that require log shipping permissions, a single policy will be defined and attached to the roles.
This DRYness helps keep within the file size limits of cloudformation too.
Also included in this change is a new `GuLoggingStreamNameParameter`, also written as a singleton for the same reasons.
To make the review easier, each commit can be read in sequence as they have been crafted to tell the story.
Usage hasn't really changed as this policy will never really be used by consumer stacks as they'l be using `GuInstanceRole` instead, which adds this policy by …
=> refactor(GuLogShippingPolicy)!: make GuLogShippingPolicy a singleton

package-lock.json, script/check-npm-version, script/setup
In #335 we moved to a v2 lockfile which is the new format for NPMv7. CI doesn't have native support for NPMv7 yet, so move back to a v1 lockfile.
See https://github.com/guardian/cdk/pull/335#issuecomment-802678168 for more information.
As `package-lock.json` doesn't form part of the bundle published to NPM, I don't think this requires a release of its own.
No.
n/a
n/a
n/a
=> chore: stay on v1 lockfile as CI doesn't have native NPMv7 support

src/constructs/autoscaling/user-data.test.ts, src/constructs/core/parameters/s3.ts, src/constructs/iam/policies/s3-get-object.test.ts, src/constructs/iam/policies/s3-get-object.ts
Following #337 and part of a bigger bit of work in #332, this makes `GuDistributionBucketParameter` a singleton as we only ever want one of them in a stack.
BREAKING CHANGE:
* The removal of the static `parameterName` field means `GuDistributionBucketParameter.parameterName` becomes `GuDistributionBucketParameter.getInstance(stack).id`
Yes. The [Prism stack](https://github.com/guardian/prism/blob/956d4334ea13c3ce20ed33e7b337064f3e5c49fb/cdk/lib/prism.ts#L51) will need to be updated to the new format.
See existing tests?
A much simpler API and ground work for supporting multiple apps (for example a backend api and frontend web app microservice) within a single stack.
n/a
=> feat!: make GuDistributionBucketParameter a singleton

src/constructs/iam/policies/describe-ec2.test.ts, src/constructs/iam/policies/describe-ec2.ts, src/constructs/iam/policies/ssm.test.ts, src/constructs/iam/policies/ssm.ts, src/constructs/iam/roles/__snapshots__/instance-role.test.ts.snap, src/constructs/iam/roles/instance-role.test.ts, src/constructs/iam/roles/instance-role.ts
A `GuInstanceRole` provides the basic permissions needed by EC2, it grants access to:
- SSM
- Describing tags
- Writing to kinesis for log shipping
#326 started the work to support the declaration of multiple apps in a stack, where an app is a collection of ASG, LB etc. However, when actually attempting to use the updated constructs in reality, the synth step failed due to multiple constructs using the same ID.
This change follows #341 and #337 and converts `GuSSMRunCommandPolicy` and `GuDescribeEC2Policy` to singletons. This means these policies will only get created once regardless of how many roles use them - there will be one policy with multiple roles attached to it. This helps keep the stack DRY and also reduces the chance of reaching the max file size limits of cloudformation.
The …
=> feat: support multiple GuInstanceRoles in a stack

docs/architecture-decision-records/002-component-constuctors.md, eslint/rules/valid-constructors.js, eslint/rules/valid-constructors.test.ts, jest.config.js, package.json, script/ci, script/lint, src/constructs/autoscaling/user-data.ts, src/constructs/core/mappings.ts, src/constructs/core/parameters/acm.ts, src/constructs/core/parameters/ec2.ts, src/constructs/core/parameters/identity.ts, src/constructs/core/parameters/log-shipping.ts, src/constructs/core/parameters/s3.ts, src/constructs/core/parameters/ses.ts, src/constructs/iam/policies/cloudwatch.ts, src/constructs/iam/policies/describe-ec2.ts, src/constructs/iam/policies/log-shipping.ts, src/constructs/iam/policies/parameter-store-read.ts, src/constructs/iam/policies/s3-get-object.ts, src/constructs/iam/policies/ses.ts, src/constructs/iam/policies/ssm.ts, src/constructs/iam/roles/instance-role.ts, src/constructs/loadbalancing/alb.test.ts, src/constructs/loadbalancing/alb.ts, src/utils/lambda/event-source.ts, tsconfig.eslint.json
We have a lint rule for constructors [because](https://github.com/guardian/cdk/blob/main/docs/architecture-decision-records/002-component-constuctors.md):
> This project contains a large number of classes, making up the various constructs and patterns. The project is intended to be used as a component library and, therefore, used by a number of people who don't have extensive knowledge of either the CDK or this library. It is therefore important to make the experience of using these classes as intuitive as possible.
We have a few too many instances of `// eslint-disable-next-line custom-rules/valid-constructors` 😅 .
It looks like this is mainly because the `id` field is static (for example the [`Stage` parameter](https://github.com/guardian/cdk/blob/0c32dbe8a73333b6ebf39d24c3e11d935845cfc0 …
=> feat: revise custom lint rule

src/constructs/loadbalancing/elb.test.ts, src/constructs/loadbalancing/elb.ts
Removes the `propertiesToRemove` prop. It looks like we were using this to set the scheme on the load balancer, however this is already being driven by the `internetFacing` prop provided by AWS.
For a scheme of "internal", set `internetFacing` to `false`. For a scheme of "internet-facing", set `internetFacing` to `true`.
See:
- https://github.com/aws/aws-cdk/blob/fb6512314db1b11fc608cd62753090684ad0d3c4/packages/%40aws-cdk/aws-elasticloadbalancing/lib/load-balancer.ts#L249
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-elb.html#cfn-ec2-elb-scheme
Yes - the props to `GuClassicLoadBalancer` is changing, with `propertiesToRemove` disappearing, so stacks would need to migrate. The migration is just setting a boolean however, so not too bad.
n/a
A simpler …
=> fix: simplify props for `GuClassicLoadBalancer`

tsconfig.json
This library is broken since v6.0.1 after PR #356. Users face this stack trace:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/philip_mcmahon/code/editions/projects/aws/node_modules/read-pkg-up/index.js
require() of ES modules is not supported.
require() of /Users/philip_mcmahon/code/editions/projects/aws/node_modules/read-pkg-up/index.js from /Users/philip_mcmahon/code/editions/projects/aws/node_modules/@guardian/cdk/lib/constants/library-info.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from …
```
=> fix: change to output as ES modules

package-lock.json, package.json, src/constants/library-info.ts, tsconfig.json
**TL;DR** Publishing `@guardian/cdk` in ESM format is tricky, it is easiest to stay on CommonJS.
In https://github.com/guardian/cdk/pull/365, we changed the output format to ES Modules. This was after https://github.com/guardian/cdk/pull/356 which bumped `read-pkg-up` to v8.0.0.
Looking at `read-pkg-up`'s [release notes for v8.0.0](https://github.com/sindresorhus/read-pkg-up/releases/tag/v8.0.0) the package has changed to ESM only and consuming projects [need to](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c):
> 1. Use ESM yourself. (preferred)
> Use import foo from 'foo' instead of const foo = require('foo') to import the package.
> 2. If the package is used in an async context, you could use await import(…) instead of require(…).
> 3. Stay on the existing version …
=> fix: compile to commonjs

src/constructs/ec2/security-groups/base.test.ts, src/constructs/ec2/security-groups/base.ts, src/constructs/ec2/security-groups/index.ts, src/constructs/ec2/security-groups/wazuh.test.ts, src/constructs/ec2/security-groups/wazuh.ts, src/constructs/iam/policies/log-shipping.ts
We'd only ever want one of these resources defined in a stack as it can be re-used by anything that needs it. This helps keep the overall size of the template down and thus reduces chance of reaching the file size limits of cloudformation.
This change also refactors the security groups, splitting them across multiple files to make them easier to reason about.
Reviewing commit by commit might be easiest.
Yes. Usage of the Wazuh security group would need to change.
See tests.
A simpler API and reduced chance of reaching the file size limits of cloudformation
n/a
=> feat: make Wazuh access security group a singleton

src/constructs/core/index.ts, src/constructs/core/ssm.test.ts, src/constructs/core/ssm.ts
We're seeing the `GuSSMIdentityParameter` tests sporadically fail (for example, [here](https://github.com/guardian/cdk/runs/2234965115?check_suite_focus=true#step:4:104)).
From the code:
> We need to create UIDs for the resources in this construct, as otherwise CFN will not trigger the lambda on updates for resources that appear to be the same
This PR switches to use `performance.now()` for a [high resolution timer](https://www.w3.org/TR/hr-time/) which provides more accuracy than `Date.now()` and thus increases the chance of uniqueness.
I suspect we could also use `Math.random`, but not sure.
This change also adds `ssm`'s exports to `core` and  moves the `id` function to a static function on `GuSSMIdentityParameter` to provide a more explicit namespace. This means usage becomes: …
=> fix: use high resolution timer for GuSSMIdentityParameter id

src/constructs/core/ssm.ts
This reverts commit 660da8a47d3ccbf93cc424acc370c554c4a5647d as it [hasn't had the desired effect](https://github.com/guardian/cdk/pull/374#issuecomment-811846159) of making the tests more deterministic. Using the clock (via `Date.now()` or `performance.now()`) isn't reliably producing unique numbers, switch to `Math.random`.
No.
n/a
Erm, the tests are no worse?
n/a
=> fix: use `Math.random` to generate a uid for `GuSSMParameter`

src/constructs/autoscaling/asg.test.ts, src/constructs/ec2/security-groups/base.test.ts, src/constructs/ec2/security-groups/base.ts, src/constructs/ec2/security-groups/wazuh.ts
Refactor `GuSecurityGroup` into the vanilla abstract class `GuBaseSecurityGroup` and the concrete class `GuSecurityGroup` which has an `AppIdentity`.
This allows a stack to create a security group scoped to a particular app within a multi app stack.
`GuWazuhAccess` now extends `GuBaseSecurityGroup` as it is a singleton and applies to all apps within a stack.
Follows https://github.com/guardian/cdk/pull/326.
Yes, they will need to pass in an `AppIdentity` as the props for `GuSecurityGroup` have changed.
No new tests added. Existing tests should pass.
It is possible to define a security group for a specific app within a stack and have it tagged with the `App` tag.
n/a
=> feat: allow GuSecurityGroup to be specified at the app level

src/constructs/autoscaling/asg.ts, src/constructs/core/stack.ts
The `setStageDependentValue` and `getStageDependentValue` helper functions have been removed. In order to reduce boilerplate, the same functionality is now provided via a single function (`withStageDependentValue`).
Yes, this is a breaking change. Stacks which use `setStageDependentValue` and `getStageDependentValue` directly will need to use `withStageDependentValue` instead. Stacks which use this functionality via the ASG construct should be unaffected.
[Existing ASG unit tests](https://github.com/guardian/cdk/blob/3bbd3124819876ef0dc1a4c8a3e361d7481e01c8/src/constructs/autoscaling/asg.test.ts#L181-L258) already validate this behaviour (and they still pass!).
* Less boilerplate is needed to use stage-dependent values.
As mentioned above, this is a breaking change. However, as this …
=> refactor!: Improve Mappings helper function(s)

src/constructs/core/migrating.test.ts, src/constructs/core/migrating.ts, src/constructs/core/stack.ts
A resource's logicalId maps to the name of the created resource.
For example, take this CloudFormation YAML for an ASG:
```yaml
DataNodeAutoScalingGroup:
Type: AWS::AutoScaling::AutoScalingGroup
Properties:
AvailabilityZones: !GetAZs ""
LaunchConfigurationName: !Ref DataNodeLaunchConfig
MinSize: 3
MaxSize: 4
Cooldown: 180
HealthCheckType: EC2
HealthCheckGracePeriod: 300
VPCZoneIdentifier: !Ref PrivateVpcSubnets
Tags:
- { Key: Stack, Value: !Ref Stack, PropagateAtLaunch: true }
- { Key: App, Value: "elk-es-data", PropagateAtLaunch: true }
- { Key: Stage, Value: !Ref Stage, PropagateAtLaunch: true }
- { Key: ElasticSearchCluster, Value: !Ref ClusterName, PropagateAtLaunch: true }
```
This creates an ASG called `DataNodeAutoScalingGroup`. This pattern is widely used in YAML definitions of …
=> refactor: Encapsulate overriding of logicalId in a single place

src/constructs/loadbalancing/alb.test.ts, src/constructs/loadbalancing/alb.ts
This simplifies the default healthcheck for ALBs by [defaulting to using the traffic port](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html#cfn-elasticloadbalancingv2-targetgroup-healthcheckport), rather than defaulting to a commonly used (but hardcoded) value.
I think it's very unlikely that any existing projects will be affected by this change.*
I think the updated unit tests are sufficient?
When defining the EC2 App pattern, we'll no longer need to override this default when a different traffic/application port is specified.
*There is a small risk that a project is currently relying on this default to perform a healthcheck via port 9000 even though they are sending all other traffic to a different port. This strikes me …
=> fix: use traffic port for ALB healthcheck by default

src/constructs/autoscaling/asg.test.ts, src/constructs/autoscaling/asg.ts, src/utils/test/alphabetical-tags.ts, src/utils/test/jest.ts, src/utils/test/synthed-stack.ts
For consistency with other constructs, suffix the `id` of `GuAutoScalingGroup` with the `app`. This ensures the logicalId is unique both on the auto-generated path and the `existingLogicalId` path.
Also adds a [custom Jest matcher](https://jestjs.io/docs/expect#custom-matchers-api) to simplify logicalId testing. It is fairly common to want to test the logicalId of a resource. This can be tricky as:
- constructs that have an `AppIdentity` will suffix the `id` with the app value
- not every construct supports static logicalIds and will always be auto-generated
Rather than passing in the `id` with a combination of `migratedFromCloudFormation` and `existingLogicalId` to get a static/deterministic logicalId, we can pass a regex to the new `toHaveResourceOfTypeAndLogicalId` matcher, asserting …
=> fix: Improve GuAutoScalingGroup's support of a multi-app stack

src/constructs/core/identity.test.ts, src/constructs/core/identity.ts, src/constructs/iam/roles/__snapshots__/instance-role.test.ts.snap
This PR ensures that the logical ids generated by this library always conform to [AWS's standard](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html):
> The logical ID must be alphanumeric (A-Za-z0-9).
No.
Existing unit tests have been updated due to this change.
Previously, it was impossible to CloudForm the resources created by the `GuInstanceRole` construct if your `AppIdentity` included non-alphanumeric characters (e.g. when using `test-app`). After this change, users will be able to include hyphens (or other non-alphanumeric characters if they really must?!) in their app names.
I can't think of any risks which would result from making this change.
=> fix: ensure all generated logical ids conform to CloudFormation standard

src/constructs/core/migrating.test.ts, src/constructs/core/migrating.ts, src/utils/logger.ts
As we migrate to the new logicalId logic introduced in #364, we'll see the migration messages more and more.
As these messages are expected, we can afford to stop producing them in TEST to avoid the build log becoming too noisy.
An example of noisy build log can be seen [here](https://github.com/guardian/cdk/runs/2294779782?check_suite_focus=true#step:4:45).
No.
See the build log?
A quieter build log will highlight any genuine errors more easily.
n/a
=> refactor: Stop producing migration messages in TEST

src/constructs/core/migrating.ts, src/constructs/core/stack.ts, src/constructs/ec2/security-groups/wazuh.test.ts, src/constructs/ec2/security-groups/wazuh.ts
Might be easiest to review commit by commit.
Replacing in-use security groups is difficult as it requires careful orchestration with instances.
Hardcoding the logicalId to "WazuhSecurityGroup" regardless of new or migrating stack makes it:
- easier for YAML defined stacks to move to GuCDK as the resource will be kept
- easier for stacks already using GuCDK to upgrade versions
Furthermore, the group description of a security group is [stateful](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html#cfn-ec2-securitygroup-groupdescription):
> Update requires: Replacement
In order to reduce friction for teams migrating from YAML to GuCDK, change the description to match [the user guide](https://github.com/guardian/security-hq/blob/main/hq/markdown …
=> fix: Hardcode the logicalId for `GuWazuhAccess`

src/constructs/cloudwatch/__snapshots__/lambda-alarms.test.ts.snap, src/constructs/cloudwatch/alarm.test.ts, src/constructs/cloudwatch/alarm.ts, src/constructs/cloudwatch/lambda-alarms.ts
This PR makes two improvements to our alarms:
1. Disables alarm actions in `CODE` by default. This prevents us from spamming teams with alerts about their `CODE` environments (in my experience these just generate unactionable noise, as `CODE` environments are expected to break sometimes).
2. Handles missing data correctly for lambda-error-percentage alarms. No data in this scenario is fine; it just means that the lambda has not been invoked at all.
No. Any user who wants to keep (or temporarily test) alarm actions in their `CODE` environment can still do so if they wish by setting `actionsEnabledInCode` to `true`.
I've tried upgrading https://github.com/guardian/tag-janitor/blob/main/cdk/lib/cdk-stack.ts (locally) in order to use this change and confirmed that the changes set looks …
=> fix: silence alarms in CODE and handle missing data correctly

package-lock.json, package.json
Updating the version number in the repository following the release of v8.0.1. [This step failed in CD](https://github.com/guardian/cdk/runs/2305782006?check_suite_focus=true) (hence the manual PR).
=> chore(release): 8.0.1

src/utils/test/jest.ts, src/utils/test/synthed-stack.ts
The `findResourceByTypeAndLogicalId` function is useful in other contexts than just assertions.
This is partly inspired by the AWS CDK library.
See:
- https://github.com/aws/aws-cdk/blob/ecc9bf386ca088ca82a332c649f13613b9793628/packages/%40aws-cdk/assert/jest.ts#L63
No, just a refactor.
n/a
`findResourceByTypeAndLogicalId` becomes available to use (see https://github.com/guardian/cdk/pull/400).
n/a
=> refactor: Make `findResourceByTypeAndLogicalId` standalone

src/constructs/loadbalancing/alb/application-listener.test.ts, src/constructs/loadbalancing/alb/application-listener.ts
Requires https://github.com/guardian/cdk/pull/408.
Use AppIdentity to identity the `GuApplicationListener` and `GuHttpsApplicationListener` constructs.
We're also making a call to `AppIdentity.taggedConstruct` here too even though it's a no-op as it's [not supported](https://docs.aws.amazon.com/ARG/latest/userguide/supported-resources.html#services-elasticloadbalancing).
This is for consistency across the project. If a construct's props extend `AppIdentity`, it should call `AppIdentity.taggedConstruct`.
Yes. The auto-generated logicalIds for `GuApplicationListener` and `GuHttpsApplicationListener` constructs have an updated naming scheme.
See additional tests.
Consistency across the project.
n/a
=> fix: Make GuApplicationListeners support multiple apps

src/constructs/loadbalancing/alb/application-listener.test.ts, src/constructs/loadbalancing/alb/application-load-balancer.test.ts, src/constructs/loadbalancing/alb/application-load-balancer.ts
Requires https://github.com/guardian/cdk/pull/409.
Make `GuApplicationLoadBalancer` consistent with other constructs by adding `AppIdentity` to its props and adding a suffix to its logicalId and ensure it is tagged appropriately too.
Yes. The auto-generated logicalIds for `GuApplicationLoadBalancer` and GuHttpsApplicationListener constructs have an updated naming scheme.
See additional tests.
Consistency across the project.
n/a
=> fix: Add multi app support to `GuApplicationLoadBalancer`

src/constructs/autoscaling/asg.test.ts, src/constructs/loadbalancing/alb/application-listener.test.ts, src/constructs/loadbalancing/alb/application-target-group.test.ts, src/constructs/loadbalancing/alb/application-target-group.ts
Requires https://github.com/guardian/cdk/pull/410.
Make `GuApplicationTargetGroup` consistent with other constructs by adding `AppIdentity` to its props and adding a suffix to its logicalId and ensure it is tagged appropriately too.
Yes. The auto-generated logicalIds for the `GuApplicationTargetGroup` constructs has an updated naming scheme.
See additional tests.
Consistency across the project.
n/a
=> fix: Add multi app support to `GuApplicationTargetGroup`

eslint/rules/valid-constructors.js, src/constructs/acm/certificate.ts, src/constructs/core/migrating.test.ts, src/constructs/core/migrating.ts, src/constructs/core/stack.ts, src/utils/mixin/index.ts, src/utils/mixin/migratable-construct-stateful.test.ts, src/utils/mixin/migratable-construct-stateful.ts, src/utils/mixin/migratable-construct.test.ts, src/utils/mixin/migratable-construct.ts, src/utils/mixin/types.ts
Currently, to define a migratable construct you need to:
- ensure the props implement the correct interfaces
- call `GuMigratingResource.setLogicalId` in the constructor
This is quite a lot and if there are no tests against the latter, we're just hoping to spot mistakes at review time.
Enter [mixins](https://www.typescriptlang.org/docs/handbook/mixins.html)!
> Along with traditional OO hierarchies, another popular way of building up classes from reusable components is to build them by combining simpler partial classes. You may be familiar with the idea of mixins or traits for languages like Scala, and the pattern has also reached some popularity in the JavaScript community.
In this change, we create two mixins:
1. GuMigratableConstruct
2. GuStatefulMigratableConstruct
These mixins greatly …
=> feat: Introduce mixins for migratable constructs 

src/constructs/autoscaling/asg.test.ts, src/constructs/autoscaling/asg.ts, src/constructs/loadbalancing/alb/application-listener.test.ts, src/constructs/loadbalancing/alb/application-target-group.test.ts, src/constructs/loadbalancing/alb/application-target-group.ts
This adds a few sensible defaults:
We want/intend our autoscaling groups to have required permissions (eg AssumeRole for SSM) by default. This PR adds the role to the ASG construct so that you get it for free. When developing our EC2 pattern, it would be great to [have it created by default without explicitly specifying it in our pattern description](https://github.com/guardian/cdk/pull/399/files#r609673294).
We also benefit from having sensible defaults for how we scale our instances based on stages. This adds a `minimumInstances` count of 1 for CODE (and therefore maximum of 2) and 3 for PROD (and therefore maximum of 6).
By default, load balancers talk to autoscaling groups/instances via HTTP. This adds a sensible default to use HTTP that can be overridden.
I don't think so. I think …
=> chore: add sensible defaults to GuAutoScalingGroup and GuApplicationLoadBalancer

.github/dependabot.yml
The integration-test directory holds an... integration test.
It is a standalone project that:
- installs @guardian/cdk from a relative path
- defines a stack
- synths the stack
This is to observe any regressions in the packaging of @guardian/cdk.
This change adds dependabot to the integration test project, as it is a project after all and its dependencies need to kept up to date.
See:
- #367
No.
n/a
More dependencies are kept up to date.
n/a
=> chore(deps): configure dependabot for the integration-test project

integration-test/package.json, package.json
We perform a check at CI time to ensure the version of aws-cdk libraries we're using are within 5 versions of the latest available.
If we're out of date, CI fails with instructions to run `./script/update-aws-cdk`. This script uses ncu (npm-check-updates) to update the aws-cdk dependencies.
This change updates the call to ncu to:
- Configure ncu to update the "aws-cdk" dependency in addition to @aws-cdk/*
- Add the --deep flag to "Run recursively in current working directory."
**Before** (only checking `cdk/package.json`)
```console
➜ ./script/update-aws-cdk
> @guardian/cdk@8.0.1 update-aws-cdk /Users/akash_askoolum/code/cdk
> ncu "/^@aws-cdk/.*$/" --upgrade && npm install
Upgrading /Users/akash_askoolum/code/cdk/package.json
[====================] 15/15 100%
All dependencies match the …
```
=> chore(deps): Keep aws-cdk dependencies in integration-test up to date

src/constructs/loadbalancing/alb/application-listener.test.ts, src/constructs/loadbalancing/alb/application-listener.ts
In this change, we're updating the `GuApplicationListener` construct to adopt the new logic. As of #418 it's as simple as using the `GuStatefulMigratableConstruct` mixin!
The logicalId logic currently in `GuApplicationListener` is very complicated with multiple paths to overriding the logicalId.
This is massively simplified, as evidenced in the updated tests.
This is the first in a series of PRs to adopt the new logic. Hopefully this multi PR approach is better than the previous monster PR (#400)!
Possibly.
The overriding logic in `GuApplicationListener` has changed. If stacks are making use of the current (broken?) logic, they will need to be attended to.
See tests?
As …
=> fix: Update `GuApplicationListener` with revised logicalId logic

src/constructs/iam/policies/base-policy.test.ts, src/constructs/iam/policies/base-policy.ts
Following #423, this change adopts the logicalId logic introduced in #364 into the `GuPolicy` policy.
`GuPolicy` is an abstract class, so testing has been added to the concrete classes `GuAllowPolicy` and `GuDenyPolicy`.
This change brings consistency to the implementation of logicalId overriding.
Possibly.
The overriding logic in `GuAllowPolicy` and  `GuDenyPolicy` has changed. If stacks are making use of the current (broken?) logic, they will need to be attended to.
See tests? There are quite  a few tests added, it might be easier to review the change on a commit by commit basis.
As noted above, the path to update to the next version of the library might require a bit of …
=> fix: Update `GuPolicy` with revised logicalId logic 

src/constructs/iam/roles/__snapshots__/instance-role.test.ts.snap, src/constructs/iam/roles/instance-role.ts, src/constructs/iam/roles/roles.test.ts, src/constructs/iam/roles/roles.ts
In this change, we're updating the `GuRole` construct to adopt the new logic. As of #418 it's as simple as using the `GuMigratableConstruct` mixin!
As a by-product, `GuInstanceRole`'s tests need updating. The snapshot tests are updated to reflect the fact that `GuInstanceRole` doesn't set `existingLogicalId` when calling `GuRole`, therefore the logicalId will always be auto-generated.
Possibly.
The overriding logic in `GuRole` and `GuInstanceRole` has changed. If stacks are making use of the current (broken?) logic, they will need to be attended to.
See tests?
As noted above, the path to …
=> fix: Update `GuRole` with revised logicalId logic

src/constructs/autoscaling/asg.test.ts, src/constructs/ec2/security-groups/base.test.ts, src/constructs/ec2/security-groups/base.ts
In this change, we're updating the `GuBaseSecurityGroup` construct to adopt the new logic. As of #418 it's as simple as using the `GuMigratableConstruct` mixin!
Possibly.
The overriding logic in `GuBaseSecurityGroup` has changed. If stacks are making use of the current (broken?) logic, they will need to be attended to.
See tests?
=> fix: Update `GuBaseSecurityGroup` with revised logicalId logic

src/constructs/kinesis/kinesis-stream.test.ts, src/constructs/kinesis/kinesis-stream.ts, src/patterns/kinesis-lambda.test.ts, src/patterns/kinesis-lambda.ts, src/utils/mixin/migratable-construct.ts
In this change, we're updating the `GuKinesisStream` construct to adopt the new logic. As of #418 it's as simple as using the `GuStatefulMigratableConstruct` mixin!
Possibly.
The overriding logic in `GuKinesisStream` changed. If stacks are making use of the current (broken?) logic, they will need to be attended to.
See tests?
=> fix: Update `GuKinesisStream` with revised logicalId logic 

src/constructs/sns/sns-topic.test.ts, src/constructs/sns/sns-topic.ts, src/patterns/sns-lambda.test.ts, src/patterns/sns-lambda.ts, src/utils/mixin/migratable-construct.ts
In this change, we're updating the `GuSnsTopic` construct to adopt the new logic. As of #418 it's as simple as using the `GuStatefulMigratableConstruct` mixin!
Possibly.
The overriding logic in `GuSnsTopic` changed. If stacks are making use of the current (broken?) logic, they will need to be attended to.
See tests?
=> fix: Update `GuSnsTopic` with revised logicalId logic 

src/constructs/rds/instance.test.ts, src/constructs/rds/instance.ts
In this change, we're updating the `GuDatabaseInstance` construct to adopt the new logic. As of #418 it's as simple as using the `GuStatefulMigratableConstruct` mixin!
Possibly.
The overriding logic in `GuDatabaseInstance` changed. If stacks are making use of the current (broken?) logic, they will need to be attended to.
See tests?
=> fix: Update `GuDatabaseInstance` with revised logicalId logic

src/constructs/autoscaling/asg.test.ts, src/constructs/loadbalancing/alb/application-target-group.test.ts, src/constructs/loadbalancing/alb/application-target-group.ts
In this change, we're updating the `GuApplicationTargetGroup` construct to adopt the new logic. As of #418 it's as simple as using the `GuStatefulMigratableConstruct` mixin!
Possibly.
The overriding logic in `GuApplicationTargetGroup` changed. If stacks are making use of the current (broken?) logic, they will need to be attended to.
See tests?
A simpler, DRYer, more consistent code base?
=> fix: Update `GuApplicationTargetGroup` with revised logicalId logic

src/utils/logger.ts
When a stack is synthesized, AWS CDK will:
- print the resulting CloudFormation template as YAML to the console
- save the resulting CloudFormation template as JSON to disk
The AWS CDK library [does not support synthesizing a YAML template to disk](https://github.com/aws/aws-cdk/issues/2965). The only way to achieve this is is to redirect the result of `cdk synth` to disk.
For example:
```console
cdk synth > cloudformation.yaml
```
Since #364 we have started printing important messages to the console. This breaks the saving YAML to disk trick as the file on disk is not valid YAML.
For example:
```yaml
GuStack has 'migratedFromCloudFormation' set to false. MyDatabase is a stateful construct, it's logicalId will be auto-generated and AWS will create a new resource.
Parameters:
Stage:
Type: …
```
=> fix: Log messages as YAML comments

src/constructs/loadbalancing/alb/application-load-balancer.test.ts, src/constructs/loadbalancing/alb/application-load-balancer.ts
In this change, we're updating the `GuApplicationLoadBalancer` construct to adopt the new logic. As of #418 it's as simple as using the `GuStatefulMigratableConstruct` mixin!
Possibly.
The overriding logic in `GuApplicationLoadBalancer` changed. If stacks are making use of the current (broken?) logic, they will need to be attended to.
See tests?
A simpler, DRYer, more consistent code base?
=> fix: Update `GuApplicationLoadBalancer` with revised logicalId logic

src/constructs/loadbalancing/elb.test.ts, src/constructs/loadbalancing/elb.ts
In this change, we're updating the `GuClassicLoadBalancer` construct to adopt the new logic. As of #418 it's as simple as using the `GuStatefulMigratableConstruct` mixin!
Possibly.
The overriding logic in `GuClassicLoadBalancer` changed. If stacks are making use of the current (broken?) logic, they will need to be attended to.
See tests?
A simpler, DRYer, more consistent code base?
=> fix: Update `GuClassicLoadBalancer` with revised logicalId logic

src/constructs/autoscaling/asg.test.ts, src/constructs/autoscaling/asg.ts
In this change, we're updating the `GuAutoScalingGroup` construct to adopt the new logic. As of #418 it's as simple as using the `GuStatefulMigratableConstruct` mixin!
Possibly.
The overriding logic in `GuAutoScalingGroup` changed. If stacks are making use of the current (broken?) logic, they will need to be attended to.
See tests?
A simpler, DRYer, more consistent code base?
=> fix: Update `GuAutoScalingGroup` with revised logicalId logic

src/constructs/cloudwatch/__snapshots__/ec2-alarms.test.ts.snap, src/constructs/cloudwatch/__snapshots__/lambda-alarms.test.ts.snap, src/constructs/cloudwatch/ec2-alarms.test.ts, src/constructs/cloudwatch/ec2-alarms.ts, src/constructs/cloudwatch/index.ts, src/constructs/cloudwatch/lambda-alarms.test.ts
This PR adds a construct which allows users to easily create an alarm as per [this recommendation](https://github.com/guardian/recommendations/pull/35). In a subsequent PR we'll be able to create this alarm as part of the EC2 App pattern.
No.
I've tested:
* CloudForming a stack with this alarm
* Triggering the alarm by forcing instances to serve 5XXs
* Triggering the alarm by forcing the load balancer to serve 5XXs
It should be easy to set up an alert as part of the EC2 App Pattern.
This should be a low risk change.
=> feat: Add construct for EC2-based infrastructure alarm

docs/001-general-usage.md, tsconfig.json
In #223 (and #233) we started adding a tag (`gu:cdk:version`) to track which version of `@guardian/cdk` is being used.
This tag helps us measure adoption:
- the presence of the tag tells us the library is being used
- the value of the tag tells us the version of the library being used
Whilst this is really useful, it does somewhat block users from using tools such as dependabot. This is because the snapshot tests will _always_ fail due to the value of the tag changing between version numbers.
In this repository, we have configured a global mock for this tag to ensure its value is static and thus simplifying the tests.
This change updates the TypeScript configuration to include (more specifically stop excluding) the `__mocks__` directories.
This results in all mocks making their way into …
=> feat: Include `__mocks__` in TS output (and published library)

package.json
In #420 we updated the arguments to `ncu` to update the aws-cdk libraries.
Having run the command to try to update to @aws-cdk/* v 1.98.0, it is only updating the library "aws-cdk" rather than "@aws-cdk/*" and "aws-cdk".
This change switches to a regex pattern rather than multiple inputs to `ncu` and things seem much happier.
```console
➜ ./script/update-aws-cdk
> @guardian/cdk@8.3.0 update-aws-cdk /Users/akash_askoolum/code/cdk
> ncu "/^@?aws-cdk(/.*)?$/" --upgrade --deep && npm install
Upgrading /Users/akash_askoolum/code/cdk/package.json
[====================] 15/15 100%
@aws-cdk/assert                      1.97.0  →  1.98.0
@aws-cdk/aws-apigateway              1.97.0  →  1.98.0
@aws-cdk/aws-autoscaling             1.97.0  →  1.98.0
@aws-cdk/aws-cloudwatch-actions      1.97.0  → …
```
=> chore: Use regex to update deps with ncu

src/constructs/autoscaling/user-data.test.ts, src/constructs/autoscaling/user-data.ts, src/patterns/ec2-app.test.ts, src/patterns/ec2-app.ts
Our [first draft of the EC2 App pattern](https://github.com/guardian/cdk/pull/399) works fine if `userData` is provided as a `string`. This PR fixes a [todo](https://github.com/guardian/cdk/pull/399#discussion_r609663035) so that our custom `userData` type (`GuUserDataProps`) can be used more easily. More specifically, if the user informs us that they need to download private config from s3, we now ensure that EC2 instances will (automatically) have the permissions to do this.
No.
I've added a unit test to cover this scenario. We should probably start testing this pattern with a 'real' application soon too!
Users won't need to manually add permissions in a case like this, where we can figure out the permissions needed automatically.
I can't think of any...
=> fix: improve support for GuUserData in EC2 App pattern

jest.config.js
In #448 we started including the mocks in the published package.
Since then the following message is appearing when running tests, both locally and in CI:
```log
jest-haste-map: duplicate manual mock found: library-info
The following files share their name; please delete one of them:
* <rootDir>/lib/constants/__mocks__/library-info.js
* <rootDir>/src/constants/__mocks__/library-info.ts
```
This change configures Jest to ignore the `lib` directory, which should quieten this message.
This should not affect the published package.
See:
- https://jestjs.io/docs/configuration#modulepathignorepatterns-arraystring
- https://github.com/facebook/jest/issues/6801#issuecomment-712951064
- #448
No.
Compare build logs?
Fewer warnings in the build log.
n/a
=> chore: Fix "duplicate manual mock found" message

src/constructs/loadbalancing/elb.test.ts, src/constructs/loadbalancing/elb.ts
Adding `AppIdentity` to `GuClassicLoadBalancer` to support a multi-app stack.
This means the auto-generated logicalId gets suffixed with the app string and the resource also gets the App tag.
This isn't considered a breaking change because `GuClassicLoadBalancer` only gets used when migrating a stack and not for new stacks.
That is, we can expect `existingLogicalId` will always get set, which will prevent the logicalId from being auto-generated.
The Prism stack can close [a TODO](https://github.com/guardian/prism/blob/7592e9e8c02f5267d160eeefe738536caf98ca4c/cdk/lib/prism.ts#L33) 🎉 
See tests?
Consistent application of `AppIdentity` to identify a resource being tied to an app.
n/a
=> fix: Add `AppIdentity` to `GuClassicLoadBalancer`

src/constructs/cloudwatch/__snapshots__/lambda-alarms.test.ts.snap, src/constructs/cloudwatch/alarm.test.ts, src/constructs/cloudwatch/lambda-alarms.test.ts, src/constructs/lambda/__snapshots__/lambda.test.ts.snap, src/constructs/lambda/lambda.test.ts, src/constructs/lambda/lambda.ts, src/patterns/__snapshots__/kinesis-lambda.test.ts.snap, src/patterns/__snapshots__/scheduled-lambda.test.ts.snap, src/patterns/__snapshots__/sns-lambda.test.ts.snap
Simplifies the props needed to create a `GuLambdaFunction` by removing the bucket key in favour of using the `GuDistributionBucketParameter` singleton.
This brings `GuLambdaFunction` in line with our EC2 constructs and patterns.
`GuDistributionBucketParameter` adds an SSM parameter to a stack with a default path of `/account/services/artifact.bucket`.
BREAKING CHANGE: Shape change to the props for `GuLambdaFunction`
The `code.bucket` field has been removed.
Yes. They'll need to update, the diff shouldn't be too difficult though as it's just the removal of a property.
Providing a simpler API that is consistent between EC2 and Lambda constructs.
n/a
=> feat: Simplify props for `GuLambdaFunction`

src/constructs/cloudwatch/ec2-alarms.ts, src/patterns/ec2-app.test.ts, src/patterns/ec2-app.ts
This PR wires up the new 5XX alarm construct (https://github.com/guardian/cdk/pull/439) with the EC2 app pattern. Users can opt-in/out of alarm creation with minimal effort and minimal understanding of CloudWatch concepts. 
This follows a [convention that is already in place for our lambda-based patterns](https://github.com/guardian/cdk/blob/2692d040c70486fbe5acb11075e4fc0a027d86fa/src/patterns/sns-lambda.ts#L70).
No, although it's a breaking change for the EC2 app pattern, the pattern is not in use yet.
I've updated the unit tests and included a new one to test that alarm creation works when the appropriate props are provided.
1. Teams who want to configure alarms for their EC2 apps can do so with minimal effort. 
2. Teams who have chosen to configure alarms via a different mechanism can …
=> feat: Add optional alarm configuration to EC2 App pattern

script/update-aws-cdk
Updates the `update-aws-cdk` script to:
1. Check one is on the head of main, with no changes
2. Update the aws-cdk libraries
3. Raise a PR with the correct message to issue a new major release
This is after my previous attempt to write the correct message failed.
PR #450 did not issue a new release because the commit had "BREAKING CHANGES" rather than the singular "BREAKING CHANGE" 🙄.
This change scripts the process to take the pain away.
No.
https://github.com/guardian/cdk/pull/465 was created with the changes in this branch. If merging that PR creates a new major release, then this script works.
Indeed, it has 🎉  https://github.com/guardian/cdk/releases/tag/v10.0.0.
🤖 
n/a
=> chore: Script the steps to update aws-cdk libs

docs/001-general-usage.md, typedoc.js
We use TypeDoc to create the documentation site. The file [`docs/001-general-usage.md`](https://github.com/guardian/cdk/blob/main/docs/001-general-usage.md) is used for the index page.
There are a couple of warnings in the build log:
```
Unsupported highlight language "console" will not be highlighted. Run typedoc --help for a list of supported languages.
target code block :
cdk synth --app="ts-node ./bin/my-app.ts" > cloudformation.yaml
source files :undefined
output file :
/home/runner/work/cdk/cdk/target/index.html
Warning:
Unsupported highlight language "json5" will not be highlighted. Run typedoc --help for a list of supported languages.
target code block :
{
"Key": "gu:cdk:version",
"PropagateAtLaunch": true,
"Value": "TEST", // <-- would otherwise be the version number of …
```
=> chore: Address TypeDoc warnings

src/constructs/autoscaling/user-data.test.ts, src/constructs/autoscaling/user-data.ts, src/patterns/ec2-app.test.ts, src/types/distributable.ts
An alternative to #478 .
Following from #455, simplify the props for `GuUserData` by removing the bucket key in favour of using the `GuDistributionBucketParameter` singleton.
This is the start of a `GuLambdaFunction` refactoring which will, ultimately, answer [this TODO](https://github.com/guardian/cdk/blob/af4ab09e53f0695cd170b474e10ab1b4f95b5f1f/src/constructs/lambda/lambda.ts#L21).
This change introduces a new `src/types` directory to house our types. Having a dedicated directory makes it easier to share types between constructs.
BREAKING CHANGE: Shape change to the props for `GuUserData`
The `bucket` field has been removed and we'll automatically use `GuDistributionBucketParameter`.
Yes, see breaking change notes above.
See updated tests.
A simpler API with a smaller surface area and …
=> feat: Simplify props for `GuUserData`

src/constructs/autoscaling/asg.test.ts, src/constructs/autoscaling/asg.ts, src/patterns/__snapshots__/ec2-app.test.ts.snap
Wazuh is required to be installed on an EC2 instance as part of our InfoSec program.
This security group allows the Wazuh agent to connect to the server.
See:
- https://github.com/guardian/security-hq/blob/5e453f456b08763cabdfe5a0717346be8a24d556/hq/markdown/wazuh.md
It shouldn't do. Teams should have Wazuh running. This plus the fact that the Wazuh security group is a singleton should mean this change is a no-op for stacks.
See updated tests.
More stuff comes for free 🎉 .
n/a
=> feat: Add Wazuh security group to ASG by default

src/constructs/loadbalancing/elb.ts
This PR adds some docs for our ELB constructs.
No.
Run `./script/docs` and have a look at the changes?
It should be harder for users to accidentally create these legacy resources (although I'm sure there's more we can do in this area). Users who must use these legacy resources should be able to understand the defaults (and how to override them) more easily than before.
N/A
=> docs: Add docs for ELB constructs

.github/PULL_REQUEST_TEMPLATE.md
Adds a reminder about documentation to our PR template.
No.
Merge this PR?
It should be harder to forget about adding/editing the docs when making changes to this library.
Yes, there is a risk that my attempt at a friendly reminder will be off-putting to other contributors. Feel free to suggest different wording that could help here 😀
=> chore: Add reminder about documentation to PR template

src/constructs/loadbalancing/alb/application-listener.test.ts, src/constructs/loadbalancing/alb/application-listener.ts, src/constructs/loadbalancing/alb/application-load-balancer.ts, src/constructs/loadbalancing/alb/application-target-group.ts, src/patterns/ec2-app.ts
* Refactors `GuHttpsApplicationListener` so that it accepts a (mandatory) `GuCertificate`, instead of an optional ARN
* Uses the `GuHttpsApplicationListener` in our `GuEc2App` pattern
* Adds basic docs for all ALB-related constructs
Yes, this PR includes a [breaking change](https://github.com/guardian/cdk/commit/edb9b33672f312ec3b0aad96e41cf95321257148) to the `GuHttpsApplicationListener` construct. That said, [I don't think anyone is currently using this construct](https://github.com/search?q=org%3Aguardian+GuHttpsApplicationListener&type=code)!
This should be covered by existing unit tests. Note that the CFN produced by the `GuEc2App` pattern does not change, the code is just simplified slightly.
* Pattern code should be easier to understand
* Users of the library are able to understand …
=> refactor: Improve `GuHttpsApplicationListener` and use it in `GuEc2App` pattern

src/constructs/cloudwatch/alarm.ts, src/constructs/cloudwatch/ec2-alarms.ts, src/constructs/cloudwatch/lambda-alarms.ts
This PR adds some docs (and moves some docs to the correct place!) for our CloudWatch constructs.
No.
This _is_ a documentation change.
Run `./script/docs` and have a look at the changes?
It should be easier to use and understand these constructs.
N/A
=> docs: Add docs for CloudWatch constructs

src/constructs/kinesis/kinesis-stream.ts, src/constructs/sns/sns-topic.ts
This PR adds some docs for our Kinesis stream and SNS topic constructs.
No.
N/A.
I've tested these changes by running `./script/docs`.
It's easier to understand these constructs, especially if you are migrating a stream/topic which has already been CloudFormed.
N/A
=> docs: Add basic docs for Kinesis streams and SNS topics

integration-test/bin/cdk.ts, integration-test/src/__snapshots__/integration-test-stack.test.ts.snap, integration-test/src/integration-test-stack.ts, src/constructs/core/parameters/log-shipping.ts, src/constructs/core/parameters/s3.test.ts, src/constructs/core/parameters/s3.ts, src/constructs/ec2/security-groups/wazuh.ts, src/constructs/iam/policies/describe-ec2.ts, src/constructs/iam/policies/log-shipping.ts, src/constructs/iam/policies/ssm.ts, src/utils/test/index.ts, src/utils/test/singleton.ts
A singleton is something that will be instantiated once and once only.
Or rather, a singleton construct is one which will be instantiated once and once only in a `Stack`.
This change fixes a bug where a singleton could not be used within two `Stack`s that get instantiated using the same `App` instance.
Something like this was not possible as there would be a cyclic reference:
```typescript
class MyStack extends GuStack {
constructor() {
GuDistributionBucketParameter.getInstance(this);
}
}
class MyOtherStack extends GuStack {
constructor() {
GuDistributionBucketParameter.getInstance(this);
}
}
const app = new App();
const myStack = new MyStack(app, "MyStack", { stack: "deploy" });
const myOtherStack = new MyOtherStack(app, "MyOtherStack", { stack: "deploy" });
myStack.synth(); …
```
=> fix: Support singletons across multiple stacks

src/constructs/core/parameters/base.test.ts, src/constructs/core/parameters/base.ts
At the moment, there is no indication in the UI that the parameter you are filling in is an SSM parameter. Users may remember to add a sensible default or a hint in the description, but they also may not. 
This change ensures that, when not provided explicitly, users are hinted that the parameter is from SSM as well as what the ideal SSM path should be.
Nope.
Users spend less time confused about how to handle CFN parameters in the UI.
I don't think there are any, as the default gets overridden if desired.
=> fix(guparameter): add a sensible default to GuParameters when using SSM

src/constructs/loadbalancing/elb.test.ts, src/constructs/loadbalancing/elb.ts
Reinstates some functionality that was removed in https://github.com/guardian/cdk/pull/362, as we've [realised that adding a `Scheme` property where it was previously undefined will lead to a resource replacement](https://docs.google.com/document/d/1MAwidPjyc2Ozl-J2VCnhhHGaVURGuzPAxow6BCLwDkg/edit). 
Projects using old versions of the library which specify `Scheme` via `propertiesToRemove` should set `removeScheme` to `true` when upgrading to the latest version.
Yes, we've updated the docs.
We've added a unit test for this.
It should be harder to accidentally replace your load balancer.
There's a risk that people still won't realise the significance of adding the scheme property to their LBs, but we have other actions which intend to address this.
=> feat: Allow users to remove Scheme property to avoid LB replacement

.github/dependabot.yml
This is a somewhat arbitrary day, the aim is to spread Dependabot PRs throughout the week to avoid being overloaded by PRs across our repositories at the start of the week.
Note: the Dependabot configuration for GHA are unchanged as PRs to bump these are fairly infrequent already.
No.
No.
n/a
Dependabot PRs will be raised on Wednesday morning, rather than Monday morning.
n/a
=> chore: Configure Dependabot to run on Wednesday

src/patterns/__snapshots__/ec2-app.test.ts.snap, src/patterns/ec2-app.test.ts, src/patterns/ec2-app.ts
Currently, we have no way of passing in whitelisted CIDR ranges to our EC2 pattern. This is something we'd like to be able to do as [some stacks such as AMIable require it](https://github.com/guardian/deploy-tools-platform/blob/ee1cfd98af1de71f0d2bb6700831827c7375942b/cdk/lib/amiable/amiable.ts#L81). 
Furthermore, the current logic of the pattern only accounts for 2 of the 3 possible application/load balancer access options:
1. Load balancer is open to the world (currently covered by `publicFacing: true`)
2. Load balancer is open to the world but IP-locked (not currently covered)
3. Load balancer is internal (covered by `publicFacing: false`)
This PR changes the `GuEc2App` props by replacing `publicFacing` with `access`. This new `access` field can be used in one of the three following …
=> feat(ec2-app-pattern): add support for different access types

docs/003-migrating-existing-stacks.md
Adds some more docs about https://github.com/guardian/cdk/pull/510 to increase the visibility of this problem/risk.
N/A
N/A
N/A
Hopefully this will spare any more users from hitting this problem when migrating their stacks.
This PR probably decreases risk slightly!
=> docs: add warning about scheme property

src/patterns/__snapshots__/ec2-app.test.ts.snap, src/patterns/ec2-app.test.ts, src/patterns/ec2-app.ts
In https://github.com/guardian/cdk/pull/500, we made some changes to the security group configuration of the EC2 App pattern. As part of this we have inadvertently added a [very permissive egress rule](https://github.com/guardian/cdk/blob/859ef3e6c3a0be0bab45ed4ee47ff1c684bcb278/src/patterns/__snapshots__/ec2-app.test.ts.snap#L604-L610) to our load balancer. We have also overridden some of the AWS CDK's default security group behaviour, which I now believe to be unnecessary.
Here's a [diff](https://github.com/guardian/cdk-playground/compare/jw-14.4.0-upgrade?expand=1) which shows the security group changes which occur when upgrading to `14.4.0` (from `14.2.0`).
Here's a much [smaller diff](https://github.com/guardian/cdk-playground/compare/jw-cdk-upgrade?expand=1) which shows the changes …
=> refactor: control incoming traffic via the listener and tighten egress rules

src/constructs/core/migrating.test.ts, src/constructs/core/migrating.ts, src/utils/mixin/migratable-construct-stateful.test.ts
Use AWS CDK Annotations to log messages instead of our custom Logger.
Annotations have coloured output (info = white, warning = yellow, error = red).
They also work with the `--trace`, `--strict` and `--ignore-errors` flags of the CDK CLI.
Note, we don't need to employ the trick in #434 as Annotations (somehow) do not get piped to disk if one redirects output to disk.
Before:
```console
➜ npx cdk synth --strict --path-metadata false --version-reporting false
Parameters:
Stage:
Type: String
Default: CODE
AllowedValues:
- CODE
- PROD
Description: Stage name
```
After:
```console
➜ npx cdk synth --strict --path-metadata false --version-reporting false
[Info at /CdkPlayground/MySnsTopic] GuStack has 'migratedFromCloudFormation' set to false. MySnsTopic is a stateful construct, it's logicalId …
```
=> fix: Use AWS CDK Annotations to log messages

src/patterns/__snapshots__/ec2-app.test.ts.snap, src/patterns/ec2-app.test.ts, src/patterns/ec2-app.ts
For a currently-unclear reason, using [`listener.connections.addSecurityGroup`](https://github.com/guardian/cdk/blob/d6be4df7e0fe95dc39eddf54b63ca7aef66bd819/src/patterns/ec2-app.ts#L204) when declaring `RESTRICTED` applications does not seem to attach the created security group to the listener or load balancer. The security group gets created, but doesn't seem to attach to anything. This results in `RESTRICTED` applications not being accessible by the CIDR ranges specified.
This PR changes the logic so that the load balancer security group is created with the intended ingresses _only if an application is `RESTRICTED`_, but creates its own security group if not, maintaining some of the benefits from #534. 
This may not be the best way to do this (and we may/should revert to using …
=> fix(ec2-pattern): Ensure RESTRICTED applications have CIDR ingresses set to the load balancer security group

integration-test/package.json
This was missed in https://github.com/guardian/cdk/pull/569.
See https://github.com/guardian/cdk/pull/569 for full details.
=> chore: Remove @guardian/eslint-config-typescript

src/constructs/ec2/security-groups/base.test.ts, src/constructs/ec2/security-groups/base.ts
`GuPublicInternetAccessSecurityGroup` has been removed, as AWS automatically creates a security group which
is almost identical to this by default when creating an Application Load Balancer.
Yes, this is a breaking change. As far as I can see it only affects [Typerighter](https://github.com/guardian/typerighter/blob/fa90ef260cd71e0f4fa1b893d7bba9b87ff828ef/cdk/lib/rule-manager/rule-manager.ts#L102-L107).
In the future, users should make use of the default security group that AWS automatically creates when creating an Application Load Balancer. However, moving from `GuPublicInternetAccessSecurityGroup`  to AWS's default requires a security group replacement, which is a disruptive change, so stacks which previously created an instance of `GuPublicInternetAccessSecurityGroup` should be able …
=> chore!: remove `GuPublicInternetAccessSecurityGroup`

docs/005-default-parameter-store-locations.md, src/patterns/ec2-app.test.ts, src/patterns/ec2-app.ts, src/utils/test/simple-gu-stack.ts
Many stacks [like to configure an access logging policy for their load balancers](https://github.com/search?p=2&q=org%3Aguardian+%22AccessLoggingPolicy%22&type=Code). This appears to be a fairly common trend among EC2 applications, and also has significant variability in terms of how it's configured. Although it would be great to enforce a sensible default (ie always logging to the same bucket and prefix), this is currently not the case across the Guardian and so it is worth providing an interface to users to configure it themselves.
This PR allows users to optionally configure access logging by specifying the bucket and prefix of where the logs are written.
Nope.
Yes, a comment has been added to explain usage, with an example provided.
Users can specify access logging …
=> feat(ec2-app): allow users to configure access logging

integration-test/package-lock.json, integration-test/package.json
This is a replacement for #563 which Dependabot is having trouble with.
I think this is because the version of aws-sdk (a transitive dep from @guardian/cdk) in the lockfile changes. It looks like this is caused by #566.
=> chore(deps): bump @types/node from 15.0.2 to 15.3.0 in /integration-test

src/patterns/ec2-app.test.ts, src/patterns/ec2-app.ts
As discussed in chat, we are currently experiencing issues with `GuSSMParameter`'s implementation not playing nicely with snapshot tests, primarily due to `GuSSMParameter` forcing a new ID for its resources at every synth which then makes snapshot tests fail due to a mismatch in IDs.
As a temporary stop-gap while we fix this problem, this PR resorts to a "traditional" CFN string parameter with the default value being the same as the value fetched by `GuSSMParameter`. 
Nope.
Nope, don't think so.
Snapshot tests still pass while users configure access logging.
=> fix(ec2-app): use a traditional GuStringParameter for access logging

src/constructs/core/custom-resources/runtime/lambda.js, src/constructs/core/custom-resources/runtime/lambda.symlink.ts, src/constructs/core/custom-resources/runtime/lambda.test.ts, src/constructs/core/ssm.test.ts, src/constructs/core/ssm.ts
We currently have quite a complicated setup in place to make a few tests work, namely we've checked in an empty `lambda.js` file and a symlink.
This change takes a different approach by using a mock in the tests.
No.
No.
This change is part of a wider set of changes to introduce a CLI to GuCDK that checks if your AWS account is setup properly by checking [SSM parameters'](https://github.com/guardian/cdk/blob/4b007724c637bdf7db3a18574c8db18691fe4d5c/docs/005-default-parameter-store-locations.md) existence. Part of this process is to change the [tsconfig file](https://github.com/guardian/cdk/blob/4b007724c637bdf7db3a18574c8db18691fe4d5c/tsconfig.json#L19), outputting inline rather than in a separate `lib` directory. Once we do that `tsc` will overwrite …
=> refactor: Simplify the SSM custom resource

src/constants/tag-keys.ts, src/patterns/__snapshots__/ec2-app.test.ts.snap, src/patterns/ec2-app.test.ts, src/patterns/ec2-app.ts
At the moment, we have poor visibility on which stacks are using which patterns. As we roll out the pattern to more stacks, this will become poorer and poorer.
This PR is the first step in a piece of work to make surfacing pattern usage across the AWS estate easier. If & when this gets merged in, we can then build a lambda to surface this information in CloudWatch, which could then be queried by and visualised in Grafana dashboards.
No. We would need to bump the library version and re-deploy any stacks using the pattern (which there are not many of, as of yet).
'
Sort of - a comment has been left above the behaviour detailing why it is necessary.
`./script/test` from the root of the repo.
The ASGs of stacks using the pattern begin to surface in AWS, and we are eventually able to display …
=> feat(ec2-app-pattern): add gu:cdk:pattern-name tag to AutoScalingGroup

src/constructs/cloudwatch/__snapshots__/ec2-alarms.test.ts.snap, src/constructs/cloudwatch/alarm.ts, src/constructs/cloudwatch/ec2-alarms.test.ts, src/constructs/cloudwatch/ec2-alarms.ts, src/patterns/ec2-app.test.ts, src/patterns/ec2-app.ts
* Creates a new alarm construct which helps to identify cycling instances (e.g. after a failed deploy or scaling event)
* Allows users to create this new alarm easily, via the EC2 App pattern
* Simplifies an existing alarm construct slightly (id is no longer required)
Perhaps this should have been split into separate PRs; I'm happy to do that if reviewers think it'd be helpful.
1. Yes, any user who currently instantiates a `Gu5xxPercentageAlarm` directly (i.e. not via the pattern) should no longer specify an id in the constructor
2. Any user who has already created a `Gu5xxPercentageAlarm` (either directly, or via the pattern) will also need to:
1. Specify a custom name 
2. Temporarily remove alarms
3. Any user who has configured an alarm via the pattern will need to refactor their …
=> feat: add an alarm capable of catching cycling instances and instantiate within the EC2 App pattern

src/patterns/ec2-app.ts
When testing the pattern out, it struck me that part of the value of the `scaling` prop is to specify your `PROD` scaling exclusively, as you would often be happy with the default `CODE` scaling of 1 min & 2 max. At the moment, our pattern forces you to specify both CODE and PROD if you use the `scaling` prop, when you may often only want to control one environment. 
This PR makes both stages optional, so you can only specify one stage and benefit from the defaults for the other.
Nope.
Nope, as I think it's still fairly clear with the current docs.
Users can optionally specify just one stage for scaling policies.
=> fix(ec2-app): allow users to specify scaling for only one stage

src/constructs/acm/certificate.test.ts, src/constructs/autoscaling/asg.test.ts, src/constructs/core/migrating.test.ts, src/constructs/core/migrating.ts, src/constructs/ec2/security-groups/base.test.ts, src/constructs/ec2/security-groups/wazuh.ts, src/constructs/iam/policies/base-policy.test.ts, src/constructs/iam/roles/roles.test.ts, src/constructs/kinesis/kinesis-stream.test.ts, src/constructs/loadbalancing/alb/application-listener.test.ts, src/constructs/loadbalancing/alb/application-load-balancer.test.ts, src/constructs/loadbalancing/alb/application-target-group.test.ts, src/constructs/loadbalancing/elb.test.ts, src/constructs/rds/instance.test.ts, src/constructs/sns/sns-topic.test.ts, src/patterns/kinesis-lambda.test.ts, src/patterns/kinesis-lambda.ts, src/patterns/sns-lambda.test.ts, src/patterns/sns-lambda.ts, src/utils/mixin/migratable-construct.test.ts
Updates the shape of `GuMigratingResource` to include a reason field to explain why a resource's logical ID is being pinned.
This is on the back of https://github.com/guardian/prism/pull/212 which fixes [this mistake](https://github.com/guardian/prism/commit/dc69fbee724965a49d9db54ef356fb18867e368c#diff-14cbc0e0275d178f0a4cf31c3c0d4408758ee8daad333947c0ff38391bc7d600L19).
The `reason` field isn't used anywhere, it's more like using the compiler to force comments... now that I think about it, it's a possible misuse of the compiler 😬 !
Yes - there is an interface shape change. Projects cannot rely on Dependabot bumping the version of GuCDK as the CI step will definitely fail. The change isn't too onerous, however.
Yes - added.
See tests?
Today's developers are kind to tomorrow's?
n/a
=> fix: Add a reason prop to GuMigratingResource

README.md
This change updates the text of the link to the `aws cdk` repo in the README to ensure the sentence makes sense and to provide more context from the link text alone.
=> chore(docs): Update AWS CDK link in README

src/patterns/ec2-app.test.ts, src/patterns/ec2-app.ts
At the moment, some stacks like [Prism](https://github.com/guardian/prism/blob/3ca28b2329dd837cee07fb7152b74e7dd55b8185/cdk/lib/prism.ts#L93-L100) require specifying block device configurations. This isn't easily or obviously achievable by accessing the ASG sub-construct (eg `pattern.autoScalingGroup`) nor by escape hatches (eg `const cfnAsg = app.autoScalingGroup.node.defaultChild as unknown as CfnAutoScalingGroup`), and so the best method might be to thread it through the pattern props.
This PR adds a prop (nested under an `autoScalingGroup` key) that allows users to optionally configure block devices.
=> feat(ec2-app-pattern): allow threading of ASG block device configuration

docs/005-default-parameter-store-locations.md, src/constructs/core/parameters/anghammarad.ts, src/constructs/iam/policies/anghammarad.test.ts, src/constructs/iam/policies/anghammarad.ts
Create a policy that allows `sns:Publish` to the Anghammarad SNS topic.
The Anghammarad SNS topic is used across multiple stacks, so we can promote it to an account wide ("account/services") parameter store location.
We then wrap this account wide parameter into the `AnghammaradTopicParameter` singleton, which the policy will add when necessary.
Yes, they become a little DRYer as they no longer need to define this policy themselves.
Yes and documentation is included.
Tests have been added that cover:
- Automatic parameter addition (well, the implementation of the singleton)
- The IAM policy
Creating a first class construct for Anghammarad permissions means downstream stacks become DRYer.
(I can also correctly spell Anghammarad!)
n/a
=> feat: Add policy to allow writing to Anghammarad

src/constructs/core/parameters/anghammarad.ts, src/constructs/core/parameters/index.ts, src/constructs/iam/policies/anghammarad.test.ts, src/constructs/iam/policies/anghammarad.ts, src/constructs/iam/policies/index.ts
Follows #626.
Update the name of `AnghammaradSenderPolicy` to `GuAnghammaradSenderPolicy` to be consistent with the library.
Also add exports to the index files to simplify how the construct gets imported.
No. Nothing is currently using this construct.
No.
n/a
Consistent naming and importing to yield a simpler interface to the library.
n/a
=> fix: Consistently name the `AnghammaradSenderPolicy`

src/constructs/s3/__snapshots__/index.test.ts.snap, src/constructs/s3/index.test.ts, src/constructs/s3/index.ts
Guardian best practice is to retain S3 buckets as buckets share a global namespace. `GuS3Bucket` will set the correct policy on the bucket to simplify this.
See:
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html
No.
Yes and it has been added.
See the added tests?
It is easier to create Guardian flavoured buckets.
n/a
=> feat: Add a construct to ease S3 bucket creation

package-lock.json
I'm getting this small change when installing dependencies (from a clean state) on `main`, so thought it was worth bringing `package-lock.json` up to date.
=> chore: Bring package-lock up to date

src/constructs/core/parameters/identity.ts
A CFN parameter for the stack name is not necessary when defining a stack with GuCDK.
Indeed since #243, `GuStack` takes a mandatory string for `stack` in it's constructor. Due to the changes in #243, it follows that `GuStackParameter` is never used and is dead code. That is, making this a patch release should follow semver... I think!
No.
No.
n/a
Removal of dead code.
n/a
=> fix: Remove the `GuStackParameter` construct

src/constructs/core/parameters/vpc.test.ts, src/constructs/core/parameters/vpc.ts, src/constructs/ec2/vpc.ts, src/patterns/__snapshots__/ec2-app.test.ts.snap, src/patterns/ec2-app.ts
As we do not run multiple apps in the same stack across multiple VPCs, we can make `GuVpcParameter` a singleton.
`GuVpcParameter` always reads from Parameter Store now. By default it reads from `/account/vpc/primary/id`, where `/account/vpc/primary/id` is the primary VPC used in an account. If teams use multiple VPCs, they are able to change this path at runtime.
BREAKING CHANGE: The `GuVpcParameter` construct is now a singleton.
It shouldn't. Most stacks are using the `GuVpc.fromIdParameter` function which adds the parameter, rather than using the parameter directly. As the signature of `GuVpc.fromIdParameter` hasn't changed, existing stacks should be able to blindly update the version of the library being used.
Yes, added.
See tests.
A simpler API.
n/a
=> feat!: Make `GuVpcParameter` a singleton

src/constructs/ec2/vpc.test.ts, src/constructs/ec2/vpc.ts, src/patterns/ec2-app.ts
`subnetsfromParameter` becomes `subnetsFromParameter` (the `f` should be capitalised).
=> fix: Fix naming of `subnetsFromParameter` static function

src/constructs/core/parameters/identity.ts, src/constructs/core/stack.ts
Converts the `GuStageParameter` construct into a singleton to simplify references to it across constructs.
Before, we had to something like:
```typescript
const stage = this.getParam<GuStageParameter>("Stage");
```
With this change, this becomes:
```typescript
GuStageParameter.getInstance(this).valueAsString
```
BREAKING CHANGE: `GuStageParameter` is now a singleton
Making `GuStageParameter` a singleton simplifies access to it. Note, `this.stage` on the `GuStack` is still possible.
No? I think stacks are accessing `stage` via the property on `GuStack`, which hasn't changed.
No.
n/a
Accessing `stage` across constructs, particularly in a YAML to CDK process, becomes simpler (see [AMIgo](https://github.com/guardian/amigo/blob/e59a763e895b58c46b3bae346bf1257faeb1fb2b/cdk/lib/amigo.ts#L145)). …
=> feat!: Make `GuStageParameter` a singleton

package.json
If not explicitly set, it looks like NPM will use the first line of the README.md as the description.
Using `npm view  @guardian/cdk --json | jq .description`, we can see the current description of `@guardian/cdk` in NPM is `"![npm][badge-npm] [![CD][badge-cd]][internal-cd-file]"`.
This change explicitly sets the description field.
=> fix: Set the package description

.github/dependabot.yml
We've started to see Dependabot raise PRs that only update the `package-lock.json` and not `package.json` (#683, #684). Setting `versioning-strategy` to `increase` will:
> Always increase the version requirement to match the new version.
That is, it should force both `package.json` and `package-lock.json` to be updated.
See:
- https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#versioning-strategy
No.
No.
n/a
More reliable Dependabot PRs.
n/a
=> chore: Set Dependabot's versioning-strategy

bin/gu-cdk, package-lock.json, package.json, script/cli, src/bin/commands/aws-cdk-version.ts, src/bin/index.ts, src/constants/__mocks__/tracking-tag.ts, src/constants/library-info.ts, src/constants/tracking-tag.ts
Add a CLI to the repository 🎉 .
This is the start of a process to bring [`@guardian/cdk-cli`](https://github.com/guardian/cdk-cli) into this repository as it makes it easier to keep the CLI up to date (we should be able to use the compiler to tell us if we've changed a type but forgot to update the CLI). Yay mono-repos!
This change adds one command `aws-cdk-version` to print the version of `aws-cdk` libraries being used. We should be able to invoke it by doing `npx @guardian/cdk aws-cdk-version` 🤞🏽 .
There's also a helpful script to invoke the CLI in DEV - `./script/cli`.
This is heavily inspired by the [AWS CDK CLI](https://github.com/aws/aws-cdk/blob/71c0a4c413e77452f47c797d4e861aa542174ce9/packages/aws-cdk/bin/cdk.ts).
```console
➜ npx @guardian/cdk --help
@guardian/cdk aws-cdk-version …
```
=> feat: Add a CLI to the repository

src/bin/aws-credential-provider.ts, src/bin/commands/account-readiness.ts, src/bin/commands/aws-cdk-version.ts, src/bin/index.ts, src/constants/ssm-parameter-paths.ts, src/constructs/core/parameters/anghammarad.ts, src/constructs/core/parameters/log-shipping.ts, src/constructs/core/parameters/s3.ts, src/constructs/core/parameters/vpc.ts, src/constructs/ec2/vpc.ts, src/patterns/ec2-app.ts
Requires #675.
It might be easier to review commit by commit.
The `account-readiness` CLI command will check for the existence of SSM parameters in an account.
Note: It does not check if the value is correct, just that it exists. Although `LoggingStreamName` is described as "Name (not ARN)", this command will not validate the value in parameter store against this requirement.
The command supports the `--profile` and `--region` flags, similar to AWS's CLI.
```console
[OK] 8/8 SSM parameters found. 0/8 SSM parameters not found.
```
```console
[ACTION NEEDED] 0/8 SSM parameters found. 8/8 SSM parameters not found.
```
```console
{
"found": [
{
"path": "/account/services/anghammarad.topic.arn",
"description": "SSM parameter containing the ARN of the Anghammarad SNS topic"
},
{
"path": …
```
=> feat: Add `account-readiness` CLI command 

src/bin/commands/account-readiness.ts, src/bin/commands/aws-cdk-version.ts, src/bin/index.ts, src/types/command.ts
Our linting rules are set to warn when an exported function doesn't explicitly define it's return type.
Set the type to `CliCommandResponse`.
Note: `CliCommandResponse`'s use of `Record<string, unknown>` is pretty generic, we might want to be more strongly typed in future.
This is a no-op.
=> chore: Fix linting warning

src/bin/commands/account-readiness.ts, src/bin/commands/aws-cdk-version.ts, src/bin/index.ts
This PR makes cli verbose by default
No
No
N/A
N/A
N/A
=> feat: Make cli verbose by default

src/constructs/cloudwatch/__snapshots__/lambda-alarms.test.ts.snap, src/constructs/iam/policies/parameter-store-read.ts, src/constructs/lambda/lambda.test.ts, src/constructs/lambda/lambda.ts, src/patterns/__snapshots__/api-lambda.test.ts.snap, src/patterns/__snapshots__/kinesis-lambda.test.ts.snap, src/patterns/__snapshots__/scheduled-lambda.test.ts.snap, src/patterns/__snapshots__/sns-lambda.test.ts.snap
This adds a policy statement to the Lambda construct so that permission is always granted to read SSM parameters under  $stage/$stack/$app/* for a lambda.
No
Have added a note on the lambda docs to reflect new permission.
Covered by snapshot tests.
Users don't need to concern themselves with granting permission to read configuration.
Risk is low due to test coverage.
=> feat: add SSM read to Lambda construct for app params

src/constructs/cloudwatch/__snapshots__/lambda-alarms.test.ts.snap, src/constructs/lambda/lambda.ts, src/patterns/__snapshots__/api-lambda.test.ts.snap, src/patterns/__snapshots__/kinesis-lambda.test.ts.snap, src/patterns/__snapshots__/scheduled-lambda.test.ts.snap, src/patterns/__snapshots__/sns-lambda.test.ts.snap
This PR adds stack/stage/app environment variables to our lambda construct, which also adds it to all lambda-based patterns.
Existing projects which don't manually set these environment variables should get them for free. Existing projects which already set these environment variables manually should be able to remove some boilerplate.
Yes, we've added a small note about this.
This should be covered by snapshot testing.
Users can avoid adding this boilerplate to their `cdk` templates.
I think this is a low risk change.
=> feat: add stack/stage/app environment variables to lambda

jest.setup.js, src/bin/commands/check-package-json.test.ts, src/bin/commands/check-package-json.ts, src/bin/index.ts, src/constants/__mocks__/library-info.ts, src/constants/library-info.ts, src/utils/package-json.test.ts, src/utils/package-json.ts
When using `@guardian/cdk` the version of `aws-cdk` libraries in your `package.json` must exactly match the version `@guardian/cdk` uses. Else you get a rather cryptic message:
```console
Type 'import("/Users/philip_mcmahon/code/editions/projects/aws/node_modules/@aws-cdk/aws-ec2/lib/vpc").ISubnet[]' is not assignable to type 'import("/Users/philip_mcmahon/code/editions/projects/aws/node_modules/@aws-cdk/aws-lambda/node_modules/@aws-cdk/aws-ec2/lib/vpc").ISubnet[]'.
```
This command allows you to provide a `package.json` file to check if the versions of `aws-cdk` libraries match what `@guardian/cdk` uses.
```
npx @guardian/cdk check-package-json
```
No.
No.
Assuming the changes in #675 haven't broken the published version of the package:
- Checkout this branch
- Run `./script/setup`
- Run …
=> feat: Add check-package-json CLI command

script/cli, src/bin/index.ts
It is useful to know what version of the CLI you're using when running commands.
Let's say you're working on a CDK project using v22.3.0 of GuCDK. You'll be using AWS CDK libraries of v1.110.1.
However if you run `npx @guardian/cdk aws-cdk-version` the CLI will suggest using v1.115.0 of the AWS CDK libraries. This is because you're invoking the latest version of the CLI, rather than version for v22.3.0.
Printing the version of GuCDK in the CLI response should hopefully make this process easier.
Before:
```console
➜ ./script/cli aws-cdk-version | jq .
{
"dependencies": {
"@aws-cdk/assert": "1.115.0",
"@aws-cdk/aws-apigateway": "1.115.0",
"@aws-cdk/aws-autoscaling": "1.115.0",
"@aws-cdk/aws-cloudwatch-actions": "1.115.0",
"@aws-cdk/aws-ec2": "1.115.0",
"@aws-cdk/aws-elasticloadbalancing": …
```
=> feat: Add the GuCDK version to the CLI JSON response

src/constructs/cloudwatch/__snapshots__/ec2-alarms.test.ts.snap, src/constructs/loadbalancing/alb/application-target-group.test.ts, src/constructs/loadbalancing/alb/application-target-group.ts, src/patterns/__snapshots__/ec2-app.test.ts.snap
On ALBs the deregistration delay determines how quickly an instance can be removed from a target grouo. The default is five minutes which makes deploys take a lot longer than is needed.
This delay should be tuned to be longer than your longest ever expected request. As such 30s seems reasonable for most use cases but I could be convinced to push this up to 60s.
In addition we also flip the healthy/unhealthy default values which look wrong (an instance should go out of service no slower than come in) and increase the polling interval so that the load balancer is more responsive.
Existing projects will inherit these more sensible defaults when they upgrade.
These specific settings are not documented.
Deploys of apps like Prism are substantially faster.
It's possible that some apps rely on …
=> fix: improve default healthcheck and deregistration settings

package-lock.json, package.json, src/constructs/core/migrating.test.ts, src/constructs/core/migrating.ts, src/constructs/core/parameters/anghammarad.ts, src/constructs/core/parameters/identity.ts, src/constructs/core/parameters/log-shipping.ts, src/constructs/core/parameters/s3.ts, src/constructs/core/parameters/vpc.ts, src/constructs/core/stack.ts, src/constructs/ec2/security-groups/wazuh.ts, src/constructs/iam/policies/anghammarad.ts, src/constructs/iam/policies/describe-ec2.ts, src/constructs/iam/policies/log-shipping.ts, src/constructs/iam/policies/ssm.ts, src/types/migrating.ts, src/utils/mixin/migratable-construct-stateful.ts, src/utils/mixin/migratable-construct.ts, src/utils/singleton.ts, src/utils/test/index.ts, tools/integration-test/package.json
Updates @guardian/eslint-config-typescript to v0.7.0 which brings a [new linting rule](https://github.com/guardian/configs/pull/114) to prevent [circular dependencies](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-cycle.md).
It also fixes the 18 issues that this rule catches. The fixes are fairly straightforward:
- The file `singleton.ts` moves from `utils/test/singleton.ts` to `utils/singleton.ts` (https://github.com/guardian/cdk/pull/773/commits/ed72819c1ba00fa91461eadfb2129d9f5f3ff50f)
- Two interfaces and user defined type guards get relocated to the `types` directory (https://github.com/guardian/cdk/pull/773/commits/3c1194e8c7d70ab59486053fd078a1ddec812cc4)
<details>
<summary>List of circular dependency violations</summary>
```console
➜ ./script/lint
> …
```
=> fix: Remove circular dependencies 

src/constructs/core/custom-resources/runtime/lambda.ts
In a `catch`, the caught value is of type `unknown`. This is because `throw "something bad happened"` is valid JS. That is, you don't have to throw an `Error` type.
Refactor to handle this fact in a slightly more type-safe way.
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw
This is after seeing #777 [fail](https://github.com/guardian/cdk/runs/3547568732?check_suite_focus=true) it's build.
No.
No.
n/a
#777 can be merged and one less instance of disabling the linter.
n/a
=> refactor: Safer retrieval of error message

src/patterns/ec2-app.ts
This PR allows users of the `GuEc2App` (and its subclasses) to access the underlying VPC. This means that users can, amongst other things, more easily wire up additional security groups. For example:
```typescript
const playApp = new GuPlayApp(params);
const anotherSg = new GuSecurityGroup(this, "PostgresSecurityGroup", {
app: "my-app",
vpc: playApp.vpc,
allowAllOutbound: false,
egresses: [{
range: Peer.anyIpv4(),
port: 5432,
description: "My Postgres SG",
}],
});
playApp.autoScalingGroup.addSecurityGroup(anotherSg)
```
cc @jonathonherbert 
No.
No.
I've tested this via [`cdk-playground`](https://github.com/guardian/cdk-playground/compare/jw-test?expand=1).
It should be easier to teams to configure additional resources which require access to the VPC (e.g. security groups).
N/A
=> feat: allow GuEc2App users to access VPC

src/constructs/lambda/lambda.ts
Since the `ErrorPercentageAlarmForLambda` is hard coded to a value which does not contain a unique identifier per lambda in a stack, it is not currently possible to define more than one per stack. This change
prefixes the `id` so that multiple lambdas may be created per stack.
I don't think so, I think fresh cloudformation including this change will spin up a load of new resources with new ids anyway, but I'm not sure.
No
We reference this code version for generating a stack with two lambdas [here](https://github.com/guardian/uk-coronavirus-data-alerts/blob/email-type-verified/package.json#L5) on a branch of the uk-coronavirus-data-alerts project where we define a stack with two lambdas:
The cloudformation generated can be successfully deployed:
=> fix: make it possible to define multiple lambdas per stack

src/utils/mixin/migratable-construct.ts
TBF we are _unsure_ about the types of `args` and we need to _ensure_ they are correct before continuing...
=> chore: fix typo

src/bin/commands/account-readiness/index.ts, src/bin/commands/account-readiness/ssm.ts, src/bin/commands/aws-cdk-version.ts, src/bin/commands/check-package-json.ts, src/bin/index.ts, src/types/cli.ts
Refactors `src/bin/commands` a little to allow for future commands, such as VPC readiness.
This is a no-op, it's in it's own PR because the VPC readiness branch is getting a little big!
No.
No.
n/a
Future work is easier.
n/a
=> refactor: Organise for more account readiness commands

src/patterns/__snapshots__/ec2-app.test.ts.snap, src/patterns/ec2-app.ts
This fixes the problem reported in https://github.com/guardian/cdk/pull/804 for the `GuEc2App` pattern (and subclasses).
=> fix: Don't tag the entire stack with pattern app tag in GuEc2App

src/patterns/__snapshots__/scheduled-ecs-task.test.ts.snap, src/patterns/scheduled-ecs-task.ts
This removes the AppIdentity.taggedConstruct call from `GuScheduledEcsTask`. On Lurch this caused some problems as we have multiple apps in one stack, and `AppIdentity.taggedConstruct` replaced all of those tags with the app tag of our `GuScheduledEcsTask`. We're doing this https://github.com/guardian/lurch/blob/main/packages/infra/LurchCDK.ts#L359 to work around it at the moment but that's not very good!
Just Lurch
Gu Patterns should not interfere with other resources within the same stack
Tagging will be less thorough :(
=> fix: Don't tag the entire stack with pattern app tag in GuScheduledEcsTask

src/patterns/scheduled-ecs-task.ts
On Lurch we'll soon have multiple `GuScheduledEcsTask`s in the same stack. Some of the props will be the same. It's useful to export these types so that we can have functions which take e.g. a containerConfiguration as a parameter
=> fix: Export GuScheduledEcsTask useful types

src/constructs/dns/__snapshots__/dns-records.test.ts.snap, src/constructs/dns/dns-records.test.ts, src/constructs/dns/dns-records.ts, src/constructs/dns/index.ts
This PR allows users to create DNS records in NS1 via `@guardian/cdk`.
No, this is new functionality. Some projects will now be able to 'inherit' their existing DNS records, but this is not mandatory.
Yes, I've added some minimal documentation.
I've added unit tests for this. I've also confirmed that the CFN that gets produced can create a `Guardian::DNS::RecordSet` in the Developer Playground.
Apps which use `@guardian/cdk` to define their infrastructure can now create and manage CNAMEs in their source code, with minimal boilerplate.
I think the risks associated with this change are managed via https://github.com/guardian/cfn-private-resource-types. This PR just makes it easier to use the private resource type!
=> feat: add CDK constructs for Guardian::DNS::RecordSet

.github/workflows/cd.yaml, .github/workflows/ci.yaml
[`guardian/actions-setup-node`](https://github.com/guardian/actions-setup-node) is a fork of `actions/setup-node` and adds node version auto-discovery. Using it results in simpler GitHub workflows.
It also makes changing the node version as simple as updating `.nvmrc`, keeping `node-version` within the workflow files in sync with `.nvmrc`.
Additionally `actions/setup-node` (and thus ``guardian/actions-setup-node`) [uses `actions/cache` under the hood](https://github.com/actions/setup-node#caching-packages-dependencies). This means we can further simplify the workflows.
No.
No.
CI should continue to function.
Simpler configuration and a simpler story for node upgrades in the future.
We introduced caching to solve a specific issue (#532). Does this change impact that? Hopefully not as, …
=> chore: Swap `actions/setup-node` for `guardian/actions-setup-node`

src/bin/commands/account-readiness/index.ts, src/bin/commands/account-readiness/vpc.ts, src/constants/library-info.ts, src/constants/ssm-parameter-paths.ts, src/types/cli.ts, src/utils/cli/vpc.test.ts, src/utils/cli/vpc.ts, src/utils/math.test.ts, src/utils/math.ts
GuCDK uses values in SSM parameter store to know into which VPC resources should be launched.
If the parameters do not exist, GuCDK will produce a template that cannot be executed.
This change adds some VPC analysis to the `account-readiness` CLI command. It:
- Finds all VPCs in the AWS region
- Determines if the VPC is in use (logic copied from [Prism](https://github.com/guardian/prism/blob/a9f3ecf47a1f2fd4361f61c39832c936a170b6f7/app/collectors/vpc.scala))
- Expects three SSM parameters to exist for each in use VPC:
1. `^/account/vpc/([A-z0-9.-_])+/id$`
2. `^/account/vpc/([A-z0-9.-_])+/subnets/private$`
3. `^/account/vpc/([A-z0-9.-_])+/subnets/public$`
Typically, an account has one in use VPC.
This _is_ the CLI 😈 .
No.
- Checkout branch
- Run `./script/cli account-readiness --profile …
=> feat: Perform VPC analysis in account-readiness

src/patterns/__snapshots__/scheduled-ecs-task.test.ts.snap, src/patterns/scheduled-ecs-task.test.ts, src/patterns/scheduled-ecs-task.ts
This adds the app-stage prefix to alarms generated by the scheduled ecs task pattern. Without this it is not possible to have more than one GuScheduledEcsTask in the same stack
Currently this pattern is only in use by Lurch so all OK I think!
No
I've tested this using the lurch stack
Being able to have >1 guscheduledecstask in a stack
=> fix: include app in scheduled ecs pattern alarm names 

src/constructs/autoscaling/asg.ts, src/constructs/ec2/security-groups/base.test.ts, src/constructs/ec2/security-groups/base.ts, src/constructs/iam/policies/base-policy.ts, src/constructs/iam/policies/parameter-store-read.ts, src/constructs/iam/policies/s3-get-object.ts, src/constructs/iam/roles/instance-role.ts, src/constructs/loadbalancing/alb/application-listener.ts, src/constructs/loadbalancing/alb/application-load-balancer.ts, src/constructs/loadbalancing/alb/application-target-group.ts, src/constructs/loadbalancing/elb.ts, src/constructs/rds/instance.test.ts, src/constructs/rds/instance.ts
Refactors some constructs to make use of the `GuAppAwareConstruct` mixin introduced in #853. This mixin ensures the logicalId of a construct includes the app identifier and also ensures the construct gets an `App` tag.
This is a no-op, as evidenced in the diff - there are only _additional_ tests and assertions in previous tests continue to hold true.
Note: This doesn't change all app aware constructs in the codebase, just the ones where refactoring is a no-op. There are more changes incoming to update the other constructs.
No.
No.
Observe CI, it should go green.
A DRYer codebase and simpler construct definition as we only need to add a mixin rather than mutating the `id` and adding tags.
n/a
=> refactor: Use `GuAppAwareConstruct` mixin to DRY codebase

README.md, script/ci, script/cli-docs
Adds the CLI docs to README.md and also adds a script to update the contents of README.md over time.
This script is also executed during CI to ensure the README.md file is up to date.
This is useful because we're going to be adding to the CLI more and more, so it's useful to keep the docs updated too.
See it [here](https://github.com/guardian/cdk/tree/aa-cli-docs#using-the-guardiancdk-cli).
Inspired by [oclif](https://github.com/oclif/oclif/blob/589a5d91742d1ad8602ca4cbed4b41f442e78237/src/commands/readme.ts#L71-L79).
No.
This is the documentation.
- Checkout branch
- Run `./script/cli-doc`
- Observe a no-op as there are no changes needed (confirm with `git status`)
- Remove the content in README.md between the markers, but not the markers themselves
- Run `./script/cli-doc`
- Observe the …
=> docs: Add the CLI docs to README.md

src/constructs/acm/__snapshots__/certificate.test.ts.snap, src/constructs/acm/certificate.ts, src/constructs/autoscaling/asg.test.ts, src/constructs/autoscaling/asg.ts, src/constructs/cloudwatch/__snapshots__/ec2-alarms.test.ts.snap, src/constructs/cloudwatch/__snapshots__/lambda-alarms.test.ts.snap, src/constructs/cloudwatch/alarm.test.ts, src/constructs/cloudwatch/alarm.ts, src/constructs/cloudwatch/ec2-alarms.ts, src/constructs/cloudwatch/lambda-alarms.ts, src/constructs/core/mappings.ts, src/constructs/core/stack.ts, src/constructs/lambda/lambda.ts, src/patterns/__snapshots__/ec2-app.test.ts.snap, src/patterns/ec2-app.test.ts
Fixes #850.
As reported in #850 it isn't possible to define stage dependent values for multiple apps in a single stack.
Let's say we have two apps: `api` and `login`. The mappings currently produced look like:
```json
"stagemapping": {
"CODE": {
"domainName": "login.code.example.com",
"minInstances": 1,
"maxInstances": 2
},
"PROD": {
"domainName": "login.example.com",
"minInstances": 3,
"maxInstances": 6
}
}
```
That is the `Mappings` for `api` have been lost as they're overwritten by those from `login` as it's last write wins.
This change makes `Mappings` app aware, resulting in this:
```json
"api": {
"CODE": {
"domainName": "api.code.example.com",
"minInstances": 1,
"maxInstances": 2
},
"PROD": {
"domainName": "api.example.com",
"minInstances": 5,
"maxInstances": 10
}
},
"login": { …
```
=> feat!: Make `GuStageMapping` app aware

.github/workflows/ci.yaml
Fixes a typo - the correct tag of `guardian/actions-merge-release-changes-to-protected-branch` to use is `v1.2.0` not `1.2.0`.
(I have created a [`1.2.0` tag temporarily](https://github.com/guardian/actions-merge-release-changes-to-protected-branch/tags) to fix CI for all the dependabot PRs that have just been raised!)
=> ci: Use correct tag

src/constructs/cloudwatch/__snapshots__/lambda-alarms.test.ts.snap, src/constructs/cloudwatch/lambda-alarms.test.ts, src/constructs/cloudwatch/lambda-alarms.ts, src/constructs/lambda/lambda.ts
Note, it makes sense to update the lambda-related patterns too here, but keen to keep that to a separate PR as still have some thinking about the specific approach there, and also to help keep this PR small.
Adds a throttling alarm to our lambda construct.
TODO (test on Playground.)
Initial motivation was to require a concurrency limit to our lambda construct, but it is difficult to know how to set this and not always desirable. An alternative is, as here, to alarm on throttling. This should let teams know when they hit lambda contention/account limits. They can then apply limits or increase quotas (or fix issues) as appropriate.
N/A.
Note, we should update the lambda patterns too. (Current thinking is that a follow-on PR for that will make reviewing things easier.)
[^1]: Consider whether …
=> feat: add (optional) throttling alarm to lambda construct

src/constructs/acm/certificate.ts, src/constructs/dns/__snapshots__/dns-records.test.ts.snap, src/constructs/dns/dns-records.test.ts, src/constructs/dns/dns-records.ts, src/patterns/ec2-app.ts, src/types/domain-names.ts
This PR updates the `GuCname` construct so that it is optimised for our most typical use case. That is, creating CNAMEs which point to a load balancer or API gateway instance for the `CODE` and `PROD` stages. 
It is still possible to create CNAMEs which don't align with this use-case (e.g. using a non-standard `Stage`), but as that is moving away from the paved road, it must be achieved via the lower-level `GuDnsRecordSet` (which requires a little more thought and boilerplate).
In order to achieve this, we have made **breaking changes**:
* Setting the TTL is now mandatory when you create a `GuCname`
* `GuCname` now requires an app name
* Domain names for `CODE` and `PROD` stages are also required
I have tested this by releasing to beta and [making the change to …
=> feat!: Improve the GuCname construct

src/constructs/core/stack.ts
BREAKING CHANGE: Removes the `stackName` prop and adds an optional `cloudFormationStackName` prop.
This helps to remove ambiguity between the Guardian concept of a stack and a CloudFormation stack.
This is a trivial change so we haven't added a test.
Before there were props called `stack` and `stackName` that referred to two completely separate things - very confusing! Hopefully renaming the latter should make this distinction clearer.
This should be low risk as only a couple of projects currently use this prop (and they are both owned by Developer Experience!). We'll update them once this change is released.
[^1]: Consider whether this is something that will mean changes to projects that have already been migrated, or to the CDK CLI tool. If changes are required, consider adding a …
=> refactor!: rename stackName to cloudFormationStackName in GuStackProps

README.md
This is a readme update to explain the use of `npx` (to read the expected version of aws-cdk) while preparing a migration from aws-cdk to @guardian/cdk.
=> docs: Explain the use of npx to check the expected aws-cdk version

src/constructs/ecs/__snapshots__/ecs-task.test.ts.snap, src/constructs/ecs/ecs-task.test.ts, src/constructs/ecs/ecs-task.ts, src/patterns/scheduled-ecs-task.test.ts, src/patterns/scheduled-ecs-task.ts
This pulls out the guts of GuScheduledEcsTask pattern and moves them into a new GuEcsTask construct. This is to support the creation of fargate tasks which do not run on a schedule. 
The investigations team needs this to support our our migrations task - which we run every time we need to make a change to the database. This is currently a lambda but can take longer than 15 minutes. We could run it on our bastion/locally, but this would mean adding psql and node to the bastion which we'd rather avoid for the usual security reasons. The downside of running them locally (as is done for discussion and flexible-content) is that someone could switch their laptop off/lose network connection part way through.
Note the change set isn't as big as it seems - this is mostly a copy paste job of …
=> feat: Introduce GuEcsTask (pulled from GuScheduledEcsTask)

src/constructs/ecs/__snapshots__/ecs-task.test.ts.snap, src/constructs/ecs/ecs-task.ts
This adds an `environmentOverrides` prop to `EcsTask` which can be used to set an environment variable in the container running the task. This is useful for adding config properties, but can also be used to override environment variables at the point the function is run.
This was a bit of a faff to work out the syntax, I found these pages useful:
- https://docs.aws.amazon.com/step-functions/latest/dg/connect-ecs.html
- https://stackoverflow.com/questions/60573180/how-do-i-pass-json-to-an-ecs-task-in-an-aws-stepfunction
- https://docs.aws.amazon.com/cdk/api/latest/docs/aws-stepfunctions-tasks-readme.html
Depends on https://github.com/guardian/cdk/pull/921
I've tested this using Lurch's CODE stack and was able to pass an environment variable to the task.
[^1]: Consider whether this is …
=> feat: Support environment overrides in EcsTask

.github/dependabot.yml
Configure Dependabot to ignore aws-cdk to reduce noise in PRs. Dependabot wants to update each aws-cdk library one at a time, however they need to be done all at once else type checks will fail. We have a CI check to help keep us up to date, so we don't need Dependabot here.
Will close:
- #936 
- #930 
- #927 
- #926 
- #925
n/a
Less noise in PRs.
n/a
=> chore: Configure Dependabot to ignore aws-cdk

src/constants/stage.ts, src/constructs/acm/certificate.ts, src/constructs/autoscaling/asg.ts, src/constructs/cloudwatch/alarm.ts, src/constructs/core/mappings.ts, src/constructs/core/stack.test.ts, src/constructs/core/stack.ts, src/constructs/dns/dns-records.ts, src/constructs/vpc/__snapshots__/vpc.test.ts.snap, src/constructs/vpc/vpc.test.ts, src/constructs/vpc/vpc.ts, src/types/domain-names.ts, src/types/stage.ts, tools/eslint/rules/valid-constructors.js, tools/eslint/rules/valid-constructors.test.ts
Possibly easiest to review commit by commit.
Creates `GuStackForInfrastructure`, a sub-class of `GuStack` designed for infrastructure based stacks.
An infrastructure based stack is a singleton - there should only be one in an AWS account (well, per region, per account).
Examples of infrastructure stacks include:
- [VPC stacks](https://github.com/guardian/cdk/blob/57d427b09a3c3d5fcf9b406f1ad2ecaf927e6152/src/constructs/vpc/vpc.ts)
- [cloudwatch-logs-management](https://github.com/guardian/cloudwatch-logs-management)
- [elasticsearch-node-rotation](https://github.com/guardian/elasticsearch-node-rotation)
- (coming soon) cost anomaly detection
A `GuStack` can have a `Stage` value of either `CODE` or `PROD`. It is not designed for infrastructure/singleton stacks. This means, for example, we …
=> feat: Add `GuStackForInfrastructure` where `Stage` is always `INFRA`

src/constructs/core/stack.test.ts, src/constructs/core/stack.ts
This PR allows users to opt-out of stack tagging.
As part of the initial migration to `@guardian/cdk` users import their CloudFormation template. This is essentially a no-op, but the change set is huge because we are adding tags to everything. 
This PR allows users to opt-out of tagging, to make the initial change smaller and easier to understand.
Co-authored by @akash1810 and @michaelwmcnamara.
We've added a unit test for this.
Users should feel more confident when migrating to `@guardian/cdk`
The main risk here is that people forget to turn tagging on after the initial migration, however Riff-Raff would catch this pretty quickly anyway.
[^1]: Consider whether this is something that will mean changes to projects that have already been migrated, or to the CDK CLI tool. If changes are …
=> feat: allow users to opt-out of tagging via GuStack

README.md, src/bin/index.ts
This adds the ability to accept and parse a 'new' command for cdk.
It is an implementation for yargs of the 'new' command from the cdk-cli:
https://github.com/guardian/cdk-cli/blob/dd3460d17937a9de3c24bfe11f8bad0bba0f66e5/src/commands/new.ts#L41-L70
The command accepts and processes all the inputs the real 'new' command will use, but just displays some testing text to show the arguments have been received.
This is the first part of the "merge cdk-cli into cdk" trello card: https://trello.com/c/xSsYX4zR/992-merge-cdk-cli-into-cdk
This change also refactors the profile and region yargs from the global scope to within the 'account-readiness' code as this is the only command that makes use of these.
-
- To test the 'new' command:
Run `./script/cli new --multiApp true --app "myApp" --stack …
=> refactor: Create skeleton for 'new' command in preparation for copying this command from cdk-cli

src/constructs/core/stack.ts, src/constructs/stack-set/__snapshots__/stack-set.test.ts.snap, src/constructs/stack-set/index.ts, src/constructs/stack-set/stack-set.test.ts, src/constructs/stack-set/stack-set.ts
Create constructs to support the creation of `AWS::CloudFormation::StackSet` resources. Unfortunately, AWS CDK does not (yet) have a L2 construct for Stack Sets 😢 .
Usage:
```typescript
// the infrastructure to create in target accounts
class AccountAlertTopic extends GuStackForStackSetInstance {
constructor(id: string, props: GuStackProps) {
super(id, props);
new GuSnsTopic(this, "topic-for-alerts");
}
}
// the infrastructure to create in the root account
class ParentStack extends GuStackForInfrastructure {
constructor(scope: App, id: string, props: GuStackProps) {
super(scope, id, props);
new GuStackSet(this, `${id}StackSet`, {
stackSetInstance: new AccountAlertTopic("Alerts", { stack: props.stack }),
name: "centralised-alarms",
description: "Provisioning of standard account alerting …
```
=> feat: Add Stack Set support

.github/workflows/ci.yaml, script/ci
Currently CI will fail when the version of AWS CDK libraries being used are over 5 releases out of date. This forces us to keep somewhat up to date with releases, however it does introduce an odd situation:
1. Raise PR
2. CI passes on PR
3. PR gets approved
4. New AWS CDK released
5. PR merged
6. Semantic Release creates a new release
7. Robot that keeps `version` in `package.json` up to date raises PR
8. Robot PR fails CI and cannot be automatically merged
The latest example of this can be seen on:
- #977 
- #995 
- #997.
Where #977 passed CI (step 2) and was merged (step 5) and #995 (step 7) is now failing it's CI checks (step 8).
When this happens we usually update the branch of the robot's PR to remove the AWS CDK check, allowing CI to pass. This isn't great as we put the check back …
=> ci: Move AWS CDK check into it's own GHA job

.github/workflows/cd.yaml, .github/workflows/ci.yaml, README.md, package-lock.json, package.json
Currently when a new release is made (via Semantic Release), a robot will raise and merge a PR to update `version` in `package.json`.
This is handy as we can browse the file to see what the latest version is.
I don't think it's necessary for the release process - Semantic Release gets the latest version number from npm.
It comes at a slight cost, however:
- A bit of PR noise. We're not expected to interacted with the robot's PRs, but the `CODEOWNERS` rules mean we get added as reviewers.
- An odd scenario where our CI checks don't pass and the robot's PR cannot be automatically merged. See #998.
This change moves to a simpler model of keeping `version` in `package.json` completly static between releases.
If one would like to find the number of the latest version, npm or GitHub releases …
=> chore: Forgo keeping `version` in `package.json` up to date

src/constructs/lambda/lambda.test.ts, src/constructs/lambda/lambda.ts
We should never use a deprecated or non-LTS runtime for lambdas. In this change, we add an error annotation to this effect.
Note: the annotation does not prevent the stack from being synthesised, to do this, we'd want to `throw`. I'm not sure if that's desirable behaviour atm though?
See added tests.
We are discouraged from using deprecated or non-LTS lambda runtimes.
We have to maintain the `DEPRECATED_RUNTIMES` list.
[^2]: If you are adding a new construct or pattern, has new documentation been added? If you are amending defaults or changing behaviour, are the existing …
=> feat: Add error annotation when a deprecated lambda runtime is used

package.json
I noticed a problem when testing https://github.com/guardian/cdk/pull/971 after it was released; the template files were omitted from the published `npm` package, which causes the `new` command to fail. This PR ensures that the necessary template files are included.
I've taken a similar approach to https://github.com/guardian/cdk-cli/pull/48, but I think using `cp` will be fine for our purposes.
Create a temporary directory and run `npx @guardian/cdk@beta new --stack my-stack --app my-app`.
The `new` command works correctly!
N/A
[^2]: If you are adding a new construct or …
=> fix: include template for project generation tooling when publishing

src/constructs/s3/__snapshots__/index.test.ts.snap, src/constructs/s3/index.test.ts, src/constructs/s3/index.ts
Updates `GuS3Bucket` to be private by default and also become app aware, which results in the bucket receiving the `App` tag.
BREAKING CHANGE: The `app` prop for a `GuS3Bucket` is now required.
See added tests.
Buckets follow best practice by default.
By becoming app aware, the auto generated logical id changes. This results in resource replacement 😱 ! [Usage](https://github.com/search?q=org%3Aguardian+GuS3Bucket&type=code) of this construct isn't very big and those stacks that are using it are also preserving a logical id from a previously YAML defined stack.
[^2]: If …
=> fix!: Make S3 buckets follow best practices

src/constructs/acm/certificate.test.ts, src/constructs/acm/certificate.ts, src/constructs/autoscaling/asg.test.ts, src/constructs/autoscaling/asg.ts, src/constructs/cloudwatch/alarm.test.ts, src/constructs/cloudwatch/alarm.ts, src/constructs/core/stack.test.ts, src/constructs/core/stack.ts, src/constructs/dns/dns-records.test.ts, src/constructs/dns/dns-records.ts, src/constructs/s3/__snapshots__/index.test.ts.snap, src/constructs/s3/index.test.ts, src/constructs/s3/index.ts, src/constructs/stack-set/stack-set.test.ts, src/constructs/vpc/vpc.test.ts, src/types/stage.test.ts, src/utils/test/simple-gu-stack.ts
Might be easier to review commit by commit.
The `withStageDependentValue` function on a `GuStack` can be used to add a [CloudFormation Mapping](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html) to the template where a value is dependant on the stage the template is being run in.
This makes sense for a `GuStack` where `stage` is either CODE or PROD. However creating a mapping for a `GuStackForInfrastructure` where `stage` is always INFRA is redundant.
In this change we only create the CloudFormation Mapping where necessary; if stage is INFRA we return a value directly, rather than via a Mapping.
See the additional tests where we assert that Mappings for `GuStackForInfrastructure` is `undefined`.
A shorter and simpler synthesised CloudFormation …
=> fix: Only create a CFN Mapping when necessary

.github/workflows/cd.yaml, .github/workflows/ci.yaml, README.md, package-lock.json, package.json
This PR reverts https://github.com/guardian/cdk/pull/1006. Although we don't need the version number in `package.json` for releasing, it is [used by `LibraryInfo`](https://github.com/guardian/cdk/blob/a33a14bd05528a202c47208b1a6d930e95a36f0f/src/constants/library-info.ts#L8-L31), so I think it's worth reinstating this.
=> revert: "chore: Forgo keeping `version` in `package.json` up to date"

.github/workflows/cd.yaml
In the past, the project generation tooling (which previously lived in https://github.com/guardian/cdk-cli) frequently became out of date. We recently migrated this code into the same repository as the constructs/patterns (see https://github.com/guardian/cdk/pull/962 and https://github.com/guardian/cdk/pull/971) and started automatically using the latest `cdk` libraries in all newly generated projects (https://github.com/guardian/cdk/pull/1028).
This PR checks that the project generation tooling still works after every release. 
I've confirmed that this command will run successfully in GitHub Actions (via a [workflow run](https://github.com/jacobwinch/post-release-testing/runs/4726003628?check_suite_focus=true) in another repository).
By running this command after every release we should …
=> test: run project generation after every release

.github/workflows/cd.yaml
This reverts commit eca07f386fe78cd5d43dbb1398342813a9d20e91 as it is [causing the CD workflow to fail](https://github.com/guardian/cdk/runs/4761287199?check_suite_focus=true).
I'll attempt this again when I understand the problem.
=> revert: "test: run project generation after every release"

script/update-aws-cdk
Note, PRs currently failing because we are not on latest aws-cdk so ran the script and hit this.
Checks some of the less common deps for this script. Note, I haven't checked `git` or `npm` as those are expected for a TS project already.
Attempt to run the script without the dependencies and get a descriptive error.
=> fix: check update-aws-cdk script dependencies before running

package.json
Add the [`target` flag](https://github.com/raineorshine/npm-check-updates#how-dependency-updates-are-determined) to `ncu` to ensure we stay on v1 of aws-cdk libraries. Otherwise v2 might be used, which we're not compatible with (yet!).
This will fail the `check-aws-cdk` build step. I propose we:
- Remove the requirement for `check-aws-cdk` to pass
- Merge this
- Raise and merge a PR to update aws-cdk deps
- Enable the requirement for `check-aws-cdk` to pass
- Rebase existing PRs
=> chore(ci): Upgrade to minor version of aws-cdk deps

.github/workflows/cd.yaml, .github/workflows/ci.yaml
Since https://github.com/actions/setup-node/pull/338, GH's setup-node Action understands `.nvmrc` files. This makes our [`guardian/actions-setup-node`](https://github.com/guardian/actions-setup-node) fork somewhat redundant now.
Move to GH's Action so we can deprecate our fork.
CI should pass. The build log should also suggest the correct node version is used too.
=> chore(ci): Use GH's setup-node Action

src/constructs/cloudwatch/__snapshots__/ec2-alarms.test.ts.snap, src/constructs/cloudwatch/ec2-alarms.ts
`GuUnhealthyInstancesAlarm` is built on top of the `UnHealthyHostCount` metric, which is measured by the Load Balancer and posted in 60-second intervals. The alarm however, has a period of 5 minutes, which can have unintended consequences.
Let's consider an example data set, where the number of unhealthy instances is always zero except at `10:07` and `10:08`
```
___________
|10:00 | 0 |
|10:01 | 0 |
|10:02 | 0 |
|10:03 | 0 |
|10:04 | 0 |
|10:05 | 0 |
|10:06 | 0 |
|10:07 | 1 |
|10:08 | 1 |
|10:09 | 0 |
(etc.)
-----------
```
`GuUnhealthyInstancesAlarm` has a period of 5 minutes and evaluates 12 datapoints, which means it looks back at the past hour of data and aggregates it into 12 equally spaced buckets. When the alarm is evaluated at `11:02`, the resulting set of datapoints is
``` …
```
=> fix: Align UnhealthyInstance alarm period with underlying metric period

src/constructs/dns/dns-records.test.ts, src/constructs/dns/dns-records.ts
There are currently two ways to create `Guardian::DNS::RecordSet` resource:
1. `GuCname`
2. `GuDnsRecordSet`
A CNAME should not return multiple answers without "the correct filters in place (such as SELECT_FIRST_N 1) to limit them to a single answer at resolution time".
`Guardian::DNS::RecordSet` does not create any filters (and it's unlikely to).
The props of `GuCname` enforce this single answer restriction, however if you're still able to use `GuDnsRecordSet` to create a CNAME that violates this restriction.
In this change we throw if a CNAME is being created with multiple answers.
See added test.
We're prevented from deploying a potentially broken DNS entry.
n/a
[^1]: Consider whether this is something that will mean changes to projects that have already been migrated, or to the CDK …
=> fix: Enforce a CNAME DNS entry has a single answer

src/constructs/ecs/__snapshots__/ecs-task.test.ts.snap, src/constructs/ecs/ecs-task.test.ts, src/constructs/ecs/ecs-task.ts
This makes [ephemeralStorage](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-ecs.TaskDefinition.html#ephemeralstoragegib) configurable in the ECS Task construct. 
On the investigations team our ECS tasks are running out of disk space due to the amount of data they are processing. We need to configure a larger amount of disk space for the fargate containers.
Set the storage prop, verify that it gets applied to the containers created by the task.
[^2]: If you are adding a new construct or pattern, has new documentation been added? If you are amending defaults or …
=> feat: Make ephemeralStorage configurable via props for ecs task

CODEOWNERS
Amends the code owner of this repository to be DevX Operations specifically. If the security or CSTI folks need to be notified they can be added as reviewers manually.
=> chore: Make operations team codeowners

src/constructs/acm/__snapshots__/certificate.test.ts.snap, src/constructs/acm/certificate.test.ts, src/constructs/acm/certificate.ts, src/constructs/autoscaling/asg.test.ts, src/constructs/autoscaling/asg.ts, src/constructs/autoscaling/user-data.test.ts, src/constructs/cloudwatch/__snapshots__/ec2-alarms.test.ts.snap, src/constructs/cloudwatch/__snapshots__/lambda-alarms.test.ts.snap, src/constructs/cloudwatch/alarm.test.ts, src/constructs/cloudwatch/alarm.ts, src/constructs/cloudwatch/ec2-alarms.ts, src/constructs/dns/__snapshots__/dns-records.test.ts.snap, src/constructs/dns/dns-records.test.ts, src/constructs/dns/dns-records.ts, src/constructs/loadbalancing/alb/application-listener.test.ts, src/patterns/ec2-app.test.ts, src/patterns/ec2-app.ts, src/types/asg.ts, src/types/domain-names.ts
This is a fairly big change. It is possibly easier to review commit by commit. Happy to discuss ways to break it down - I'd be keen for the changes to yield a single new release.
Following discussions in #1049, #1048 and IRL, this PR moves to simplify the codebase by removing explicit stage awareness from these constructs:
- `GuAutoScalingGroup`
- `GuCertificate`
- `GuCname`
- `GuAlarm`
These constructs can still be made stage aware, however it is now the decision of the caller.
This change impacts the `Ec2App` pattern too, but thankfully not in a dramatic way. The prop `certificateProps` has been renamed to `domain`; this is because it is more explicit.
~❓ https://github.com/guardian/cdk-playground/pull/161 demonstrates this branch on a simple stack. If we didn't rename …
=> feat!: Remove stage awareness from constructs

src/constants/access.ts, src/patterns/ec2-app.test.ts, src/patterns/ec2-app.ts, src/types/access.ts
Move from:
```
import { AccessScope } from "@guardian/cdk/lib/patterns/ec2-app";
```
To:
```
import { AccessScope } from "@guardian/cdk/lib/constants/access";
```
n/a
Giving `AccessScope` a more logical home.
n/a
=> fix: Move `AccessScope` onto it's own path

src/patterns/index.ts
I noticed that the `GuApiLambda` pattern was not being exported correctly. This caused two small problems: 
1. The pattern was not listed via the [TypeDocs](https://guardian.github.io/cdk/modules/index.html). 
2. The pattern had to be imported via it's full path e.g. `import { GuApiLambda } from "@guardian/cdk/lib/patterns/api-lambda";`, which is not [what users expect for patterns](https://github.com/guardian/cdk#patterns-and-constructs).
=> chore: export GuApiLambda correctly

tools/integration-test/src/integration-test-stack.ts
CI is passing, so `//` must be valid. However, `/` is more standard 😄 .
=> chore: Correct import path in integration-test

src/constructs/ecs/ecs-task.ts
The changes in https://github.com/guardian/cdk/pull/1075 breaks the ecs task construct because `EphemeralStorage size should be at least 21` according to cloudformation - this is suprising as the [default is apparently 20gb](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-ecs.TaskDefinition.html#ephemeralstoragegib)  I guess if you set it to anything other than the default then it expects you to actually increase the amount of storage from the default amount.
I'm not sure what the best thing to do here is - this PR currently sets the default to 21GB which I've tested solves the problem - but it could also probably be `undefined` so that the default 20gb value is used.
I've verified that this solves the problem. 
Previously broken deploy: …
=> fix: ephemeralStorage must be > 20 when configuring

src/constructs/iam/roles/github-actions.ts
Removes references to `@guardian/actions-assume-aws-role` as this has now been [deprecated](https://github.com/guardian/actions-assume-aws-role#readme).
=> docs: remove references to actions-assume-aws-role

tools/integration-test/.gitignore
Every so often the IDE decides to compile the `integration-test` project. This creates files within `tools/integration-test/dist/`, which we do not care about. Add this directory to `.gitignore`. This means we can `git add .` again!
=> chore: gitignore compiled code from `integration-test` project

src/constructs/autoscaling/asg.ts, src/patterns/ec2-app/__snapshots__/base.test.ts.snap
This PR ensures that all EC2 instances provisioned via `@guardian/cdk` use [IMDSv2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html), encoding the security best practice described [here](https://github.com/guardian/security-hq/blob/main/hq/markdown/guardduty-sechub-common-problems.md#ec2-instances-should-use-imdsv2).
Snapshot testing should suffice here.
Another best practice is encoded in the library; it would currently be tricky to conform to this best practice as we do not expose the ASG props at the pattern-level.
Yes, there is a risk that a team will break their application when they upgrade if they are still relying on `IMDSv1` - there is a good description of the potential impact of that …
=> fix: EC2 instances should use IMDSv2

src/patterns/__snapshots__/api-lambda.test.ts.snap, src/patterns/api-lambda.test.ts, src/patterns/api-lambda.ts
* Returns the created `LambdaRestApi`s to the caller
* Tests adding a domain name to a `LambdaRestApi` and a `GuCname`
=> feat: Return created LambdaRestApis when creating a GuApiLambda

src/constructs/autoscaling/asg.ts, src/patterns/ec2-app/base.ts
We're adding this prop to allow consumers of the GuAutoScalingGroup construct and GuEc2App pattern to be able to explicitly opt out of IMDSv2. Previously, requireImdsv2 was hardcoded to true inside of GuAutoScalingGroup. It's best practice to use IMDSv2, but it's good to provide an escape hatch for applications that aren't ready to adopt it.
NB: GuAutoScalingGroup defaults the value to false, so existing consumers will be unaffected by this change.
N/A
support-frontend can log again!
N/A
[^2]: If you are adding a new construct or pattern, has new documentation been …
=> fix: add withoutImdvs2 to props of GuAutoScalingGroup and GuEc2App 

docs/migration-guide-lambda.md, docs/migration-guide-scheduled-lambda.md, docs/migration-guide.md, src/constructs/lambda/lambda.ts, src/patterns/scheduled-lambda.ts
This PR adds a migration guide for the scheduled Lambda pattern/architecture. Whilst working on this I noticed a couple of problems with the TypeDocs for the relevant patterns/constructs, so I've also fixed those here.
I've tested this via https://github.com/guardian/elastic-search-monitor/pull/16 & https://github.com/guardian/elastic-search-monitor/pull/17.
Other developers/teams should be able to follow this guide and migrate their own scheduled Lambda infrastructure.
Yes, this is low risk; it only adds documentation & the documentation has been tested/rehearsed.
[^2]: …
=> docs: add migration docs for scheduled lambda architecture

docs/migration-guide.md
Small documentation improvement in response to [this Trello card](https://trello.com/c/kgNzEPc7/1180-should-gucdk-project-generator-default-withouttags-to-true). 
I considered enabling this property by default for all generated projects but decided that forcing another manual step (i.e. "go and change the boolean that the project generation tooling set!") on _all_ users was undesirable. I think that developers might want to do this for their first migration, or for a high profile stack - but I don't think it's necessary to check this every time.
N/A
Users can gain confidence more easily (if desired) when migrating to `@guardian/cdk`.
There's a small risk that people will forget to reenable tagging - I'd expect that to be caught during code review or deployment.
[^1]: Consider whether this …
=> docs: add guidance for viewing diff without tag noise

.vscode/extensions.json
Automatically recommend key extensions when project is opened in VS Code.
=> chore: add VS Code extension recommendations

package-lock.json, package.json
All users will need `aws-cdk` in order to synth their stacks, so I've added it as a peer dependency (as discussed [here](https://github.com/guardian/amigo/pull/719#discussion_r853192458)).
N/A
This helps to inform users that they'll need the `aws-cdk` dependency (and which version they'll need).
I can't think of any here.
=> chore: add aws-cdk as a peer dependency

src/constants/tag-keys.ts, src/constructs/iam/roles/instance-role.ts, src/patterns/ec2-app/__snapshots__/base.test.ts.snap, src/patterns/ec2-app/base.test.ts, src/patterns/ec2-app/base.ts
(Applies to the Ec2App patterns.)
A LogKinesisStreamName tag is added to the ASG and nested resources (including instances). These are read to enable automatic log shipping, initially of Cloud Init Logs.
For more info see:
* https://github.com/guardian/amigo/blob/46725214bac8d4ced5f3b2df27bc49ec6c37bd20/roles/cdk-base/README.md
* https://github.com/guardian/amigo/pull/706
And also the recent Amiable PR that would have not been necessary with this change:
https://github.com/guardian/amiable/pull/122
=> feat: Add support for automatic log shipping

.github/dependabot.yml, package.json
Users of `@guardian/cdk` must be on the exact version of the `aws-cdk` and `construct` dependencies,
else they see issues like this in CI (source https://github.com/guardian/cdk-playground/pull/192):
```console
lib/cdk-playground.ts:17:52 - error TS2345: Argument of type 'this' is not assignable to parameter of type 'IConstruct'.
Type 'CdkPlayground' is not assignable to type 'IConstruct'.
Types of property 'node' are incompatible.
Type 'import("/home/runner/work/cdk-playground/cdk-playground/cdk/node_modules/constructs/lib/construct").Node' is not assignable to type 'import("/home/runner/work/cdk-playground/cdk-playground/cdk/node_modules/@guardian/cdk/node_modules/constructs/lib/construct").Node'.
Types have separate declarations of a private property 'host'.
17 …
```
=> chore(deps): Configure Dependabot to ignore `constructs`

docs/best-practices.md
Adds instructions for manually configuring the Jest mock of `gu:cdk:version` that were lost in #1121. See #448 (and #468) for the original reasoning.
=> docs: re-add instructions for configuring the `gu:cdk:version` mock

src/constructs/vpc/vpc.ts
This change adds a link to the documentation of the VPC construct pointing to the relevant guardian recommendations related to   VPC's.
This is a documentation change.
No functional impact.
=> docs: Update vpc documentation to point to guardian recommendations

tools/eslint/rules/valid-constructors.js, tools/eslint/rules/valid-constructors.test.ts
Since #1134 `GuStackForInfrastructure` no longer exists. Update the custom linting rule accordingly.
Slightly confused as to why CI didn't pick this up... possibly due to how `tsc` is ran? i.e. we never explicitly use [`tsconfig.eslint.json`](https://github.com/guardian/cdk/blob/5ccb3c10dad5447ea014fa48ad58c743aab23c8a/tsconfig.eslint.json#L5).
=> chore(linter rule): Fix valid constructor linting rule

src/constants/tag-keys.ts, src/patterns/ec2-app/base.test.ts, src/patterns/ec2-app/base.ts
This PR helps users to configure application log shipping via the `GuEc2App` pattern (or one of its subclasses).
**By default, application logging is switched off.** This is because the majority of users of the pattern will be migrating (or have already migrated) an app which already ships application logs via some other means. We do not want to accidentally ship duplicate logs to ELK and we do not want to increase friction by forcing users to switch their approach to logging at the point of adoption.
The downside of this is that brand new applications will not automatically pick up this sensible default (i.e. they'll need to remember to opt-in via the pattern props).
I suggest that we update the default behaviour (via a breaking change) when a significant number of apps have started …
=> feat: allow users to opt-in to application log shipping via GuEc2App

package-lock.json, package.json
Small follow up to https://github.com/guardian/cdk/pull/1251.
Whilst working on https://github.com/guardian/amiable/pull/138, I copy & pasted the versions from peer dependencies without thinking about it. This mismatch leads to the following error when running `cdk synth`:
`This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.`
This PR should help others to avoid this problem.
=> chore(deps): Update aws-cdk to 2.23.0

src/patterns/api-multiple-lambdas.ts
Similar to https://github.com/guardian/cdk/pull/1158 - I forgot to allow users to access the underlying API Gateway instance when I added the `GuApiGatewayWithLambdaByPath` pattern via https://github.com/guardian/cdk/pull/1250.
I'm currently migrating an app to this pattern and installing a beta which contains this change allows me to configure DNS properly.
Users can configure DNS for the `GuApiGatewayWithLambdaByPath` pattern.
I can't think of any risks associated with this.
[^2]: If you are adding a new construct or pattern, has new documentation been added? If you …
=> fix: provide access to GuApiGatewayWithLambdaByPath's API Gateway instance

docs/stateful-resources.md
When migrating a stack's template from YAML to CDK, it's important to take care of stateful resources. This change attempts to document why, impact, and resolutions.
Does it [read](https://github.com/guardian/cdk/blob/aa-stateful-resource/docs/stateful-resources.md) well?
=> docs: Add documentation on stateful resources

src/patterns/kinesis-lambda.ts, src/patterns/sns-lambda.ts
The shape of the incoming props, specifically around handling of an existing resource, is likely to be changed over time as we understand use-cases. So, annotate these patterns as `alpha`.
See these attempts to update the incoming props:
- https://github.com/guardian/cdk/pull/1264/files#r872391677
- https://github.com/guardian/cdk/pull/1265
- https://github.com/guardian/cdk/pull/1278#discussion_r876660606
Although [TypeDoc](https://typedoc.org/guides/doccomments/) doesn't [support](https://github.com/TypeStrong/typedoc/issues/1381) `@alpha` it does at least standout:
[TSDoc](https://tsdoc.org/pages/tags/alpha/) seems to support a wider range of tags, but not sure it's worth moving just yet.
n/a
Permission to break the API in future releases 🤞🏽 ?
Across the org, there is only [one …
=> fix: Mark `GuKinesisLambda` and `GuSnsLambda` patterns as alpha

src/constructs/core/__data__/cfn.yaml, src/constructs/core/stack.test.ts, src/constructs/core/stack.ts
A `CfnInclude` construct is added to a stack when [migrating from a YAML/JSON template](https://docs.aws.amazon.com/cdk/v2/guide/use_cfn_template.html).
In this change, we produce a warning to take care over any stateful resources, and suggest use of the `overrideLogicalId` function to ensure such resources are not removed unintentionally.
This becomes useful for the proposed changes in #1278 which seeks to drop our [current messaging](https://github.com/guardian/cdk/blob/abc237fff54a0efbffa5a3733182c1cb738fff4a/src/constructs/core/migrating.ts#L35-L73). This change feels useful in isolation of #1278, hence it being it's own PR.
This has been beta released to 43.4.0-beta.2, so to test:
- Use GuCDK at version 43.4.0-beta.2 in a project that has a `CfnInclude` construct
- Synth the stack …
=> feat: Add warning for stateful resources when migrating to GuCDK

docs/migration-guide-api-with-lambda.md, docs/migration-guide-ec2.md, docs/migration-guide.md
Add a migration guide for the `GuApiLambda` and `GuApiGatewayWithLambdaByPath` patterns.
This is the process that I followed for the `mobile-save-for-later` migration: 
* https://github.com/guardian/mobile-save-for-later/pull/64 
* https://github.com/guardian/mobile-save-for-later/pull/65
* https://github.com/guardian/mobile-save-for-later/pull/66
* https://github.com/guardian/mobile-save-for-later/pull/67
The next time we follow these docs we should make any necessary corrections (I've probably forgotten something!).
Users can attempt self-service migrations to two more GuCDK patterns!
Yes, I have tested this migration path for the `GuApiGatewayWithLambdaByPath` pattern but not the `GuApiLambda` pattern. I'm pretty confident that the process will be the same, but I can't be 100% sure as …
=> docs: add migration guide for API Gateway & Lambda

src/constructs/core/parameters/base.ts, src/constructs/core/stack.test.ts, src/constructs/core/stack.ts, src/constructs/stack-set/stack-set.ts
This is more correct than `getParam` as it return ALL parameters, not just those of type `GuParameter`. As a result the `getParam` and `setParam` functions on `GuStack` are also removed. (There's an argument that this getter could be internal/private to the library - see below.)
This change also somewhat reduces the utility of the [`GuParameter`](https://github.com/guardian/cdk/blob/90382af4c1939ffa7f5385da2739a0259b5b678b/src/constructs/core/parameters/base.ts#L14-L26) construct. We might be able to simplify (or even remove!) it.
Less code, and a more complete API.
> **Note**
> I propose we ship this as a minor update. The risk is this isn't inline with [semver](https://semver.org/).
Although this change removes the `getParam` and `setParam` functions on …
=> feat: Add `parameters` getter on `GuStack`

src/patterns/sns-lambda.ts
Ensure tokens (such as params) can be used for the existing topic ARN prop in the GuSnsLambda pattern.
At the moment this is blocking the Image Copier migration with the following error:
`Error: ID components may not include unresolved tokens: ${Token[TOKEN.210]}.`
=> fix: hardcode ID of existing SNS topic in GuSnsLambda pattern

src/patterns/sns-lambda.ts
https://github.com/guardian/cdk/pull/1347 has a bug: the ID is not guaranteed unique, which means it errors when multiple lambdas are defined with this prop set.
=> fix: ensure ID is unique

src/bin/commands/account-readiness/ssm.ts, src/bin/commands/bootstrap/index.ts, src/bin/commands/new-project/index.ts, src/bin/commands/new-project/utils/imports.ts, src/bin/index.ts, src/constants/ssm-parameter-paths.ts, src/constructs/autoscaling/user-data.ts, src/constructs/core/parameters/anghammarad.ts, src/constructs/core/parameters/fastly.ts, src/constructs/core/parameters/log-shipping.ts, src/constructs/core/parameters/s3.ts, src/constructs/core/parameters/vpc.ts, src/constructs/ec2/vpc.test.ts, src/constructs/ec2/vpc.ts, src/patterns/ec2-app/base.ts, src/utils/cli/vpc.ts, tsconfig.json
It might be easier to review this change commit by commit.
[Introduced](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html#checked-indexed-accesses---nouncheckedindexedaccess) in TS 4.1, [`noUncheckedIndexedAccess`](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) offers stricter type checking, which is a good thing!
From the release notes:
> That means that in our last example, `opts.yadda` will have the type `string | number | undefined` as opposed to just `string | number`. If you need to access that property, you’ll either have to check for its existence first or use a non-null assertion operator (the postfix `!` character).
CI passing should be sufficient.
=> chore: Enable `noUncheckedIndexedAccess`

docs/setting-up-a-gucdk-project.md
This PR's entire purpose is to force the release of https://github.com/guardian/cdk/pull/1364 which fixes a critical vulnerability in [git-url-parse](https://github.com/IonicaBizau/git-url-parse) by bumping it to the latest version.
Actual change is a very minor readme change (I insert the word 'the' in a sentence where it fits)
=> fix: Force release of fixed critical vulnerability in pr 1364

docs/architecture-decision-records/005-x01-package-structure.md
Adds an ADR following a team discussion on how we can add experimental features in a clear and obvious way.
- Does it [read](https://github.com/guardian/cdk/blob/aa-experimental-adr/docs/architecture-decision-records/005-x01-package-structure.md) well?
- Does it accurately reflect the discussion?
=> docs(adr): Add ADR for supporting experimental features

src/constructs/core/parameters/base.test.ts, src/constructs/core/parameters/base.ts
This change update the default value for `GuParameter` to describe that the value is used to route to the value in SSM, which is non-obvious.
The intention is to provide slightly better hints to consumers when they use `GuParameter` in their projects in order to make using GuCDK a more pleasant experience.
=> refactor: Clearer default value for GuParameter

src/aspects/metadata.ts, src/constructs/acm/__snapshots__/certificate.test.ts.snap, src/constructs/cloudwatch/__snapshots__/api-gateway-alarms.test.ts.snap, src/constructs/cloudwatch/__snapshots__/ec2-alarms.test.ts.snap, src/constructs/cloudwatch/__snapshots__/lambda-alarms.test.ts.snap, src/constructs/dns/__snapshots__/dns-records.test.ts.snap, src/constructs/ecs/__snapshots__/ecs-task.test.ts.snap, src/constructs/iam/__snapshots__/fastly-logs-iam.test.ts.snap, src/constructs/iam/policies/__snapshots__/log-shipping.test.ts.snap, src/constructs/iam/policies/__snapshots__/ses.test.ts.snap, src/constructs/iam/roles/__snapshots__/github-actions.test.ts.snap, src/constructs/iam/roles/__snapshots__/instance-role.test.ts.snap, src/constructs/s3/__snapshots__/index.test.ts.snap, src/constructs/stack-set/__snapshots__/stack-set.test.ts.snap, src/constructs/vpc/__snapshots__/vpc.test.ts.snap, src/experimental/patterns/__snapshots__/kinesis-lambda.test.ts.snap, src/experimental/patterns/__snapshots__/sns-lambda.test.ts.snap, src/patterns/__snapshots__/api-lambda.test.ts.snap, src/patterns/__snapshots__/api-multiple-lambdas.test.ts.snap, src/patterns/__snapshots__/scheduled-lambda.test.ts.snap, src/patterns/ec2-app/__snapshots__/base.test.ts.snap, src/utils/mixin/__snapshots__/app-aware-contruct.test.ts.snap
In https://github.com/guardian/cdk/pull/1394 we introduced a Metadata Aspect to enable us to track which specific constructs and patterns are in use, and which version. This manifests itself as `Metadata` in the CloudFormation template.
The version maps to the NPM package version, as such, it changes over time. This means the value stored within snapshot tests would also change. This will become noisy over time.
In https://github.com/guardian/cdk/pull/448 we published a mock and wired every project up to use it. This results in the library version being static in snapshots.
In this change, we update the Metadata Aspect to retrieve the version number in the same way, making it's value static within snapshots also.
This change is an alternative to https://github.com/guardian/cdk/pull/1484. …
=> fix(metadata): Use mocked library version in Metadata Aspect

.github/workflows/update-aws-cdk.yaml
Run the AWS CDK updater (see #1512) today at 1PM to test it. Once it runs, we can revert this change.
=> ci: Run AWS CDK updater today

.github/workflows/update-aws-cdk.yaml
Reverts guardian/cdk#1518, as promised!
To merge after 2PM BST, as schedules are UTC.
=> revert: Revert "ci: Run AWS CDK updater today" [skip-ci]

src/constructs/dns/__snapshots__/dns-records.test.ts.snap, src/constructs/dns/dns-records.ts, src/constructs/ecs/__snapshots__/ecs-task.test.ts.snap, src/constructs/ecs/ecs-task.ts, src/patterns/__snapshots__/api-lambda.test.ts.snap, src/patterns/__snapshots__/api-multiple-lambdas.test.ts.snap, src/patterns/api-multiple-lambdas.ts, src/patterns/ec2-app/__snapshots__/base.test.ts.snap, src/patterns/ec2-app/base.ts
In #1394 we introduced an Aspect to add a Metadata element to the synthesised template. It walks the CDK tree and if it finds a node that starts with "Gu", it adds to the Metadata element.
A node on the CDK tree is a specific type - [`Node`](https://github.com/aws/constructs/blob/4926d6f304442915777db36f039ea7b38c83ad1d/src/construct.ts#L18-L21). In this change, we make some of our custom "constructs" formally extend [`Construct`](https://github.com/aws/constructs/blob/4926d6f304442915777db36f039ea7b38c83ad1d/src/construct.ts#L418-L424). A `Construct` [has a `Node`](https://github.com/aws/constructs/blob/4926d6f304442915777db36f039ea7b38c83ad1d/src/construct.ts#L8-L16), and so appears on the tree.
That is, by extending `Construct` _and_ having a class name prefixed "Gu", we are able to …
=> fix(metadata): Enable reporting on more constructs

src/bin/commands/new-project/utils/init.ts
Added test-update to package.json to make pre commit check easier by including the snapshot ci will expect
script/ci-project-generation
will create a test project in 
/private/tmp/cdk-project
where you can check out the generated package.json
=> chore: new item test-update in package.json

src/experimental/constructs/__snapshots__/error-budget-alarm.test.ts.snap, src/experimental/constructs/error-budget-alarm.test.ts, src/experimental/constructs/error-budget-alarm.ts
This PR adds a new experimental construct which aims to create alarms that will notify teams when they are at risk of missing their SLO targets.
The alarm configuration that we create follows the recommendations in the [SRE Workbook](https://sre.google/workbook/alerting-on-slos/) to implement `Multiwindow, Multi-Burn-Rate Alerts`. There is also another nice explanation of this alerting strategy [here](https://developers.soundcloud.com/blog/alerting-on-slos).
The CloudWatch implementation of this strategy creates nine separate CloudWatch alarms. The main alarms that users need to care about are the three [composite alarms](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Create_Composite_Alarm.html). These track different burn rates of error budget consumption: 
* fast (e.g. …
=> feat: add first attempt at experimental error budget alarm

src/experimental/constructs/__snapshots__/error-budget-alarm.test.ts.snap, src/experimental/constructs/error-budget-alarm.test.ts, src/experimental/constructs/error-budget-alarm.ts
This is a follow-up to https://github.com/guardian/cdk/pull/1576. 
Although the first attempt works fine with a single error budget alarm, the naming convention used for child alarms will prevent multiple `GuErrorBudgetAlarmExperimental`s from being created within the same stack. This bug was caused by accidentally using an old name/id that I'd intended to remove during a refactor.
I've added a unit test to cover this case. When using the old name (e.g. on `main`) it used to fail and now it passes.
* We can support multiple `GuErrorBudgetAlarmExperimental`s  in the same stack
* It's easier to associate a child alarm with its parent (e.g. when looking in the AWS console), due to the more precise name
I think is PR is pretty low risk - this experimental construct is currently only being …
=> fix: improve child alarm naming for GuErrorBudgetAlarmExperimental

src/experimental/constructs/index.ts, typedoc.js
I realised that experimental constructs and patterns were accidentally omitted from the TypeDoc site (inspired by https://github.com/guardian/cdk/pull/1580#discussion_r1011614027!), so I have fixed this in this PR.
Run `./script/start-docs` locally.
It's easier to learn how to use experimental constructs and patterns!
I don't think there are any risks associated with this PR.
=> docs: add experimental constructs and patterns to TypeDoc site

src/experimental/constructs/error-budget-alarm.test.ts, src/experimental/constructs/error-budget-alarm.ts
This makes `GuErrorBudgetAlarmExperimental` throw an error if the client passes an SLO target outside the valid range, which is 95% to 99.95%.
This is because outside of these bounds, the way the alarms are configured do not produce useful results. For example, with an SLO target of 90%, the fast alarm will never trigger (this is the one that work on an hour-long time window).
If the SLO target is overambitious, for example 99.999%, then the alarm will fire but only after the SLO target has been missed, and its error budget consumed (in an hour long window, this would happen in 26 seconds). Because this alert wouldn't be actionable, we don't recommend people use it. For this level of availability, a totally different approach needs to be taken.
We have added unit tests to cover the …
=> fix: Add restriction to the slo target value

src/constructs/dns/dns-records.ts
Fixes a regression introduced in https://github.com/guardian/cdk/pull/1532. Nodes in a CDK tree must have a unique ID. A [typical usage](https://github.com/guardian/security-hq/blob/aa2f2c03277faac9dc01a06d2082f1c85bb439ed/cdk/lib/security-hq.ts#L135-L140) of `GuCname` looks like this:
```ts
new GuCname(this, 'security-hq.gutools.co.uk', {
app: "security-hq",
domainName: 'security-hq.gutools.co.uk',
ttl: Duration.hours(1),
resourceRecord: ec2App.loadBalancer.loadBalancerDnsName,
});
```
Here:
- `level1ConstructId` = `security-hq.gutools.co.uk`, as set by the user
- `level2ConstructId` = `security-hq.gutools.co.uk`, as derived from `domainName` prop
This results in an attempt to add the same ID to the CDK tree.
In this change we update the `GuDnsRecordSet` level 2 construct, to have a …
=> fix(dns): Ensure Level 2 construct has unique ID

src/patterns/__snapshots__/api-multiple-lambdas.test.ts.snap, src/patterns/api-multiple-lambdas.test.ts, src/patterns/api-multiple-lambdas.ts
The `GuApiGatewayWithLambdaByPathProps` construct provides an easy way to set up an Api Gateway endpoint backed by a lambda, however there was previously no way to specify that this endpoint should require an api key. 
This PR adds that functionality by adding an optional `apiKeyRequired` property to the `ApiTarget` interface used to specify endpoints.
There is a Jest test provided
Users of the `GuApiGatewayWithLambdaByPathProps` construct should be able to create endpoints secured by an api key without additional code.
None that I can see, the property is optional so behaviour for existing clients is unchanged
[^1]: Consider whether this is something that will mean changes to projects that have already been migrated, or to the CDK CLI tool. If changes are required, consider adding a …
=> feat: Allow users of GuApiGatewayWithLambdaByPathProps construct to require an apiKey on resources

src/constructs/core/stack.ts
It's useful to have all resources in a stack tagged with `App`, specifically for monitoring costs by app
=> feat: Optional appName for tag

src/experimental/constructs/__snapshots__/error-budget-alarm.test.ts.snap, src/experimental/constructs/error-budget-alarm.test.ts
We've recently been doing some discovery work to ascertain the correct CloudWatch metrics/statistics for typical Availability or Latency SLOs.
This PR adds tests so that we keep working examples which demonstrate how to configure error budget alarms for both of these common SLI types.
This PR only adds tests 😀 
I've deployed the CloudFormation that gets generated by these examples for `cdk-playground` and confirmed that the alerts fire under expected scenarios (e.g. deliberately serving a percentage of errors or slow requests).
We have working examples of alerts for these SLI types documented via unit tests.
The risk here is minor, but documenting these via tests will slow down CI slightly (IMO this is worth it because the tests can't go out of date whereas standard documentation is …
=> docs: add example alerts for Availability and Latency SLOs

.github/workflows/snyk.yml
Removes the Snyk schedule, which is unnecessary and will cause the workflow to become suspended after 60 days of inactivity on the repo!
=> ci: Remove unnecessary Snyk schedule

src/experimental/riff-raff-yaml-file/index.test.ts, src/experimental/riff-raff-yaml-file/index.ts
When we added `riff-raff.yaml` generation in https://github.com/guardian/cdk/pull/1372, we had a validation step that:
1. Discovered all the `GuStack`s in an `App`
2. Discovered the set of `region`s
3. Discovered the set of `stacks`s
4. Discovered the set of `stage`s
5. For [each combination of the above](https://github.com/guardian/cdk/blob/ea02fbdf010f968c09768a261a3692a083829fd6/src/experimental/riff-raff-yaml-file/group-by.ts#L21-L41), [expected to find](https://github.com/guardian/cdk/blob/ea02fbdf010f968c09768a261a3692a083829fd6/src/experimental/riff-raff-yaml-file/index.ts#L78-L97) a `GuStack` that matched.
This meant, for example, for the following:
```ts
class MyDatabaseStack extends GuStack {}
class MyAppStack extends GuStack {}
new MyDatabaseStack({ env: { region: 'eu-west-1' …
```
=> fix(riff-raff.yaml): Loosen restrictions on GuStacks in an App

src/constructs/autoscaling/asg.ts, src/experimental/riff-raff-yaml-file/deployments/cloudformation.ts, src/experimental/riff-raff-yaml-file/index.test.ts, src/patterns/ec2-app/base.ts, src/types/amigo.ts
This builds on the changes in #1697, to make `AmigoStage` property of the cloudformation step of the auto generated `riff-raff.yaml` configurable. This is done via the existing `imageRecipe` property, to avoid making the props list any noisier - it is now `string | AmigoProps` which allows this further configuration, but with the same defaults. This also forms a placeholder for potentially making `Encrypted` configurable too (but given there's a riff-raff bug here - see https://github.com/guardian/riff-raff/pull/991 - we're not including that in this PR, although we may also choose to 'codify best practice' by hard coding that to `true` in CDK).
Experiment with setting these additional properties and see them come out in the `riff-raff.yaml` in `cdk.out`.
More flexible, I'll certainly …
=> feat(riff-raff.yaml): make `AmigoStage` configurable for auto generating `riff-raff.yaml`

src/constructs/autoscaling/asg.ts, src/experimental/riff-raff-yaml-file/deployments/cloudformation.ts, src/experimental/riff-raff-yaml-file/index.test.ts, src/types/amigo.ts
Following https://github.com/guardian/riff-raff/pull/991, add support for encrypted AMIs. By default AMIs are assumed to be encrypted, as this is best practice. Not sure if this would be surprising?
See updated tests.
It's possible to auto-generate a more complete `riff-raff.yaml` file.
If an AMIgo recipe is not configured to create an encrypted copy, and one hasn't explcitly said `Encrypted: false`, then the deployment will fail with Riff-Raff unable to locate a relevant AMI.
[^2]: If you are adding a new construct or pattern, has new documentation been added? If you …
=> feat(riff-raff.yaml): Add support for encrypted AMIs

src/constructs/acm/__snapshots__/certificate.test.ts.snap, src/constructs/acm/certificate.test.ts, src/constructs/dns/__snapshots__/dns-records.test.ts.snap, src/constructs/dns/dns-records.test.ts, src/constructs/loadbalancing/alb/application-listener.test.ts, src/experimental/constructs/__snapshots__/error-budget-alarm.test.ts.snap, src/experimental/constructs/error-budget-alarm.test.ts, src/patterns/ec2-app/__snapshots__/base.test.ts.snap, src/patterns/ec2-app/base.test.ts, src/patterns/ec2-app/base.ts, src/patterns/ec2-app/framework.test.ts
Updates the documentation only. `prod-guardian.com` isn't owned by the Guardian but looks plausibly like it might, can has caused confusion. Let's switch it to something more obviously a placeholder
=> style: Clearer example domain

src/constructs/loadbalancing/alb/application-listener.test.ts, src/constructs/loadbalancing/alb/application-listener.ts, src/patterns/ec2-app/base.ts, src/patterns/ec2-app/framework.test.ts, src/patterns/ec2-app/framework.ts
This adds a new EC2 pattern - `GuPlayWorkerApp`. A few teams run Play apps which do useful data processing tasks like consuming queues and pushing data to other queues, or polling web services, but notably do not provide much of a HTTP API themselves apart from a health check.  For these apps, having an ALB is required for healthchecking but the https certificate / domain are not useful.  None of the existing patterns support this requirement.
This change ensures that certificates are still required for regular Play and Node apps.  For services without a certificate the the ALB port to 8080 instead of 80 and sets the ALB as non-open to discourage abusing the change to host browser facing HTTP services.
If this pattern becomes widely used, it might be worth exploring if the ALB could be …
=> feat: New GuPlayWorkerApp pattern

src/constructs/autoscaling/asg.test.ts, src/constructs/autoscaling/asg.ts, src/constructs/autoscaling/user-data.test.ts, src/experimental/constructs/__snapshots__/error-budget-alarm.test.ts.snap, src/patterns/ec2-app/__snapshots__/base.test.ts.snap, src/patterns/ec2-app/base.test.ts
This change moves `GuAutoScalingGroup` to use `LaunchTemplates` as `LaunchConfigurations` [are deprecated](https://aws.amazon.com/blogs/compute/amazon-ec2-auto-scaling-will-no-longer-add-support-for-new-ec2-features-to-launch-configurations/).
The API to the consumer should remain unchanged, but this will results in EC2 instances getting a different `Name` tag in its current implementation. See https://github.com/guardian/cdk/pull/1731/files#diff-b219fec113d015feaadba12ad710f805f4ba8fc1fcf3c270be34c8fd31b67c0fR101 for the logic that generates the `Name`.
> **Note**
> This change removes tests for `Name` tag on an `AutoScalingGroup` as these are not generated or set by GuCDK and moves from the ASG as Tags to `TagSpecifications` on `LaunchTemplate`.
See …
=> feat: Use LaunchTemplates instead of LaunchConfiguration

.eslintrc.js, package-lock.json, package.json, src/patterns/ec2-app/base.ts
Leverages https://github.com/guardian/eslint-plugin-tsdoc-required to enforce certain documentation requirements.
The aim is to provide more localised documentation - focusing on the props - and to mirror AWS's own approach here.
For now, this is only applied to a single file. If people approve the approach, we can gradually extend it across the codebase.
Requires the following for exported members:
* exported members (classes, interfaces, ...) must be documented with a valid TSDoc
* for exported 'props' interfaces, no top-level comment is required, but properties must be documented with a valid TSDoc
E.g. valid:
```
export interface MyProps {
/**
* Description of someProperty.
*/
someProperty: string;
/**
* Description of anotherProperty.
*/
anotherProperty: number;
}
```
(It is …
=> docs: enforce tsdocs for exported members (illustration)

src/constants/ssm-parameter-paths.ts
**Note, interested in what the actual path here should be. Perhaps `/account/external...`? instead of under services?**
Adds global dist bucket so that we can reference it. This bucket contains artifacts that need to be accessilble to all of our AWS accounts.
Once merged, I will raise a PR on aws-account-setup to add this parameter to all of our accounts. There is somewhat of a chicken and egg issue here, but the window of time between being present in CDK and in accounts (via aws-account-setup) is likely to be small and the only users, initially at least, Devx.
=> feat: Add devx global dist bucket

src/constants/ssm-parameter-paths.ts
Small fix to https://github.com/guardian/cdk/pull/1789 to align parameter name with the path.
Note, no one is using this yet so should be safe to change.
BREAKING CHANGE: the SSM paramter path is changed. To update: DevxGlobalDistBucket -> OrganisationDistributionBucket.
=> fix: refactor org dist bucket naming for clarity

src/constants/ssm-parameter-paths.ts
Adds a new named SSM parameter:
```
DeployToolsAccountId: {
path: "/organisation/deployTools.account.id",
description: "Account ID of the Deploy Tools account. Useful as some shared resources live here.",
},
```
Note, unclear what a good path is here - input very welcome!
The initial motivation is to reference a shared Lambda Layer that lives in the Deploy Tools account (see https://github.com/guardian/cdk/pull/1769/files#diff-8a2ab91d886f00c60278a2b34e5ffd1b2b4a3c6eec5ed33ab147d60693ca9a1dR173). But I suspect this will be generally useful given we often locate shared DevX resources here.
An alternative is:
https://github.com/guardian/private-infrastructure-config
But am reluctant to add this as a dependency to all CDK users as it contains private info and requires private repo access.
=> feat: Add DeployToolsAccountId named SSM parameter

.github/workflows/update-aws-cdk.yaml
In #1512 we automated the process of updating AWS CDK dependencies by creating a schedule that runs on the 10th day of each month.
We sometimes want to perform an update earlier, so allow the GH workflow to be manually invoked.
N/A
We can update AWS CDK dependencies via the GitHub UI (or CLI!), rather than the manual process of:
- Locally switching to `main` and updating
- Locally running `./script/update-aws-cdk`
=> chore(deps): Enable manual AWS CDK update via github.com

src/constructs/lambda/lambda.ts, src/patterns/ec2-app/base.test.ts, src/patterns/ec2-app/base.ts
Introduce Google auth to EC2 patterns
The aim is to support:
* human authentication
* for EC2-pattern users
* that is *secure* and *easy to adopt*
This is achieved by integrating Cognito at the ALB level.
In addition to a workspace check - i.e. the user is part of @guardian.co.uk - a group check is also required. When multiple groups are specified a user need only be a member of one to gain access.
It is recommended that people create a specific Google group for their application and use this for the membership check. If broader P+E dev access is required, use `engineering@guardian.co.uk`.
The overall architecture is as follows:
```mermaid
sequenceDiagram
Note right of ALB: Shaded region is defined in CDK pattern.
rect rgba(0, 0, 255, .1)
ALB->>Cognito: Handle authentication for me …
```
=> feat: Cognito for Google auth

src/constructs/lambda/lambda.ts, src/experimental/riff-raff-yaml-file/deployments/lambda.ts, src/experimental/riff-raff-yaml-file/index.test.ts, src/experimental/riff-raff-yaml-file/index.ts, src/patterns/ec2-app/base.ts
Updates CDK to allow riff-raff.yaml auto-generation to work with managed (not uploaded by the consuming stack) lambda deploys. This is to allow CDK to reference a lambda S3 sources that are managed and uploaded by DevX (for example the [cognito auth lambda](https://github.com/guardian/cdk/blob/main/src/patterns/ec2-app/base.ts#L485)), to deploy successfully from a  generated riff-raff.yaml.
RiffRaff changes are also required to support this: https://github.com/guardian/riff-raff/pull/1129
This is being tested by the deployment of https://github.com/guardian/birthdays/pull/75
The `googleAuth` option in the `guEc2App` pattern can be used successfully by non-DevX teams.
=> feat: Allow riff-raff.yaml auto-generation to work with managed lambda deploys

docs/setting-up-a-gucdk-project.md
Update docs to include a `--package-manager` so that users don't think this is an optional argument
=> docs: Add missing `--package-manager` to example

src/constructs/core/stack.test.ts, src/constructs/core/stack.ts
Adds a new `repositoryName` field to a `GuStack`, returning the value of the GitHub repository that is already added as a `gu:repo` tag to the stack (see #537).
Initially, this is to address [a TODO in service-catalogue](https://github.com/guardian/service-catalogue/blob/baff2dc75744e847ae3ff437e78c2f5e2f30cfcb/packages/cdk/lib/ecs/task.ts#L90); it feels useful outside of that service, so adding it to GuCDK.
See added test.
Less work for consuming projects to do?
N/A
[^2]: If you are adding a new construct or pattern, has new documentation been added? If you are amending …
=> feat(GuStack): Add a getter for the repository name

src/patterns/ec2-app/base.test.ts, src/patterns/ec2-app/base.ts
This change allows the session length if `googleAuth` is set in `GuEc2App` or one of the classes which extend it. The value of 15 minutes set here is a compromise and represents the shortest possible time any service will allow a users access revoked via Cognito will persist.
A side effect of using the `googleAuth` configuration is that requests to Cognito domains that this pattern requires will result in CORS errors after the expiry period requiring client apps to deal with this error or require users to refresh their browsers. The cause of this is the ALB redirecting users to the Cognito domain when the expected cookies are missing or expired, resulting in a CORS failure as the Cognito endpoint lacks the appropriate CORS headers.
A longer session length will reduce (but not eliminate) …
=> feat: Allow ALB Google auth session length to vary up to 60 minutes

.github/workflows/cd.yaml
This change adds explicit permissions to the CD GitHub workflow in order to fix an issue with the build where these are required (see https://github.com/guardian/cdk/actions/runs/5090361143/jobs/9149327417#step:4:226).
`contents: write`: required to allow pushing the release tag
`id-token: write`: To allow authentication with NPM
Merge this to main and the build should be able to release a new version.
People can continue to release and use new versions of `guardian/cdk`.
=> fix: Add explicit permissions to cd.yaml

.github/workflows/ci.yaml
Explicitly list permissions for the approve and merge job, hoping to fix the failure in https://github.com/guardian/cdk/pull/1875.
=> ci: Set permissions for auto-merge job

.github/workflows/cd.yaml, .github/workflows/ci.yaml, docs/contributing.md, package-lock.json, package.json, typedoc.js
A redo of https://github.com/guardian/cdk/pull/1006, with an additional change to the TypeDoc configuration to drop [`includeVersion`](https://typedoc.org/options/input/#includeversion).
Though #1006 was reverted in #1027, the recent [permissions changes to GitHub workflows](https://github.com/guardian/cdk/pull/1876#issuecomment-1564529731) has prompted taking another look at this.
#1006 was originally reverted due to a concern that the value in `package.json` was used within `LibraryInfo`, however it looks like [this comment](https://github.com/guardian/cdk/pull/1027#pullrequestreview-844630521) is correct. To demonstrate this, I've [published this branch to `beta`](https://github.com/guardian/cdk/releases/tag/v50.6.1-beta.1). We can use this beta version to confirm everything is still …
=> chore: Forgo keeping version in package.json up to date (attempt 2)

src/constructs/ecs/__snapshots__/ecs-task.test.ts.snap, src/constructs/ecs/ecs-task.test.ts, src/constructs/ecs/ecs-task.ts, src/patterns/scheduled-ecs-task.ts
Adds a new optional prop to this pattern.
When attempting to synth a template, the command fails with this error message:
```
There are no 'Private' subnet groups in this VPC.
```
This is expected - it's not possible to know what kinds of subnets are in a given VPC at compile time if a context file isn't present. Passing in this prop should address the issue and make synth work.
I made this change to my local version of GuCDK and updated `package.json` to point to the version of GuCDK in my filesystem rather than the one from npm, so that I was able to test this change in my stack. After passing in private subnets obtained with `GuVpc.subnetsFromParameter` I was able to `synth` without errors. 
We don't have to commit a context file to version control when using this pattern.
[^1]: …
=> fix: add `subnets` prop to `GuScheduledEcsTask`

src/constructs/ecs/__snapshots__/ecs-task.test.ts.snap, src/constructs/ecs/ecs-task.test.ts, src/constructs/ecs/ecs-task.ts, src/patterns/scheduled-ecs-task.ts
Reverts #1891, which causes deployments to fail due to custom resources being generated by CDK. It is unclear whether it is a bug, but I've filed a bug report with AWS:
- https://github.com/aws/aws-cdk/issues/26013
[^1]: If you are adding a new construct or pattern, has new documentation been added? If you are amending defaults or changing behaviour, are the existing docs still valid?
=> revert: Revert #1891

src/constructs/ses/index.test.ts, src/constructs/ses/index.ts
This change adds a `GuEmailIdentity` construct to encode how to set up a [SES verified identity](https://docs.aws.amazon.com/ses/latest/dg/verify-addresses-and-domains.html) for a `gutools.co.uk` domain.
See https://github.com/guardian/image-syndication/pull/19/commits/0093e299b8c9d5c514c529e487792085342597fd for testing before merge.
This is usable in our projects, simplifying configuration where consumers need to send emails via SNS.
[^2]: If you are adding a new construct or pattern, has new documentation been added? If you are amending defaults or changing behaviour, …
=> feat: Add GuEmailIdentity

src/constructs/cloudwatch/lambda-alarms.test.ts, src/constructs/cloudwatch/lambda-alarms.ts
Adds props for `lengthOfEvaluationPeriod` and replaces `numberOfMinutesAboveThresholdBeforeAlarm` with `numberOfEvaluationPeriodsAboveThresholdBeforeAlarm`.
This allows `GuLambdaErrorPercentageAlarm` to monitor scheduled lambdas more effectively by taking into account the cadence with which the lambda runs.
For example, in this case for a lambda that runs every 15 minutes we want to know if it fails on twice concurrent runs, we would set:
```ts
const alarmProps = {
toleratedErrorPercentage: 1,
lengthOfEvaluationPeriod: Duration.minutes(15),
numberOfEvaluationPeriodsAboveThresholdBeforeAlarm: 2,
}
```
See https://github.com/guardian/pressreader/pull/42 for an example of where overriding the current behaviour was required to monitor effectively.
We may also be able to do this specifically …
=> feat!: Update GuLambdaErrorPercentageAlarm

.github/workflows/update-aws-cdk.yaml
The [workflow](https://github.com/guardian/cdk/blob/main/.github/workflows/update-aws-cdk.yaml) to automatically update AWS CDK libraries is [failing](https://github.com/guardian/cdk/actions/workflows/update-aws-cdk.yaml), with a lack of permissions:
Following a recent GitHub organisational change, we're now required to explicitly list the [permissions](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs) needed within a workflow.
This workflow runs on the 10th day of every month, bumping the version of AWS CDK libraries being used. It'll create a PR editing the `package.json` and `package-lock.json` files, therefore, grant these permissions.
I've triggered the workflow. It has succeeded, and raised the PR https://github.com/guardian/cdk/pull/1934.
Our automations …
=> ci: Explicitly grant permissions to updating workflow

src/constructs/lambda/lambda.test.ts, src/constructs/lambda/lambda.ts, src/experimental/patterns/kinesis-lambda.test.ts, src/experimental/patterns/kinesis-lambda.ts, src/experimental/patterns/sns-lambda.test.ts, src/experimental/patterns/sns-lambda.ts, src/experimental/riff-raff-yaml-file/index.test.ts, src/experimental/riff-raff-yaml-file/index.ts, src/patterns/api-lambda.test.ts, src/patterns/api-lambda.ts, src/patterns/api-multiple-lambdas.test.ts, src/patterns/api-multiple-lambdas.ts, src/patterns/scheduled-lambda.test.ts, src/patterns/scheduled-lambda.ts
This PR adds support for using Lambda [versions](https://docs.aws.amazon.com/lambda/latest/dg/configuration-versions.html) and [aliases](https://docs.aws.amazon.com/lambda/latest/dg/configuration-aliases.html). These features are not currently used at the Guardian, but they are necessary for teams who want to make use of features which rely on versioning (e.g. SnapStart or Provisioned Concurrency).
The primary motivation for this PR is unblocking @tomrf1, who is keen to start using SnapStart after confirming that it [offers very significant performance improvements for his project](https://github.com/guardian/support-frontend/pull/4869). There is some more general background on SnapStart [here](https://docs.google.com/document/d/1ZC9o70gfWoEgfmbd4C0w87SUYqzbMx5CID38EOqf8dA/edit#heading=h.d …
=> feat: add Lambda versioning support

src/experimental/riff-raff-yaml-file/deployments/lambda.ts, src/experimental/riff-raff-yaml-file/index.test.ts
Only sets an explicit value for `prefixStackToKey`, `prefixAppToKey`, and `prefixStageToKey` if they are set to false (as `true` is the default) in `riff-raff.yml`. RiffRaff complains if you explicitly set these with the default values.
I've edited the unit tests, and added a specific test case to check the behaviour.
Less noise when deploying auto-generated `riff-raff.yml`.
=> fix: Don't set prefix settings if using default values in `riff-raff.yml`

src/constructs/cloudwatch/__snapshots__/api-gateway-alarms.test.ts.snap, src/constructs/cloudwatch/__snapshots__/ec2-alarms.test.ts.snap, src/constructs/cloudwatch/__snapshots__/lambda-alarms.test.ts.snap, src/constructs/cloudwatch/api-gateway-alarms.ts, src/constructs/cloudwatch/ec2-alarms.ts, src/constructs/cloudwatch/lambda-alarms.ts
In the email we receive when these alarms happen, there is a link to the alarm. In that link, the percent sign is correctly url-escaped, but the search doesn’t appear to work.
For example, following [this link](https://eu-west-1.console.aws.amazon.com/cloudwatch/deeplink.js?region=eu-west-1#alarmsV2:alarm/High%205XX%20error%20%25%20from%20support-reminders%20%28ApiGateway%29%20in%20PROD) from a recent email shows an error with the following text:
> The alarm "High 5XX error %25 from support-reminders (ApiGateway) in PROD" was not found
Replacing the percent sign should fix this error, allowing easy navigation from the email to the alarm. However, the change does make the alarm name longer, which may mean it’s truncated sooner in the email subject lines, potentially obscuring the stage. …
=> fix: Remove percent sign from default alarm names

src/experimental/riff-raff-yaml-file/README.md, src/experimental/riff-raff-yaml-file/index.test.ts, src/experimental/riff-raff-yaml-file/index.ts
> **Note**
> This code change is negligible (changing `private` to `public`), so mainly looking for feedback on the docs and the resulting DX.
As an alternative to #1657, this change makes the `riffRaffYaml` property of `RiffRaffYamlFileExperimental` public. This means we can supply additional deployment types, if needed. This is more flexible than #1657.
The typical use-case is adding an `aws-s3` deployment type, which `RiffRaffYamlFileExperimental` does not currently support.
No validation is performed[^1] on the parameters you provide, so you might get deployment errors due to an invalid `riff-raff.yaml` file. For example, if an unrecognised parameter or deployment type is provided, an invalid `riff-raff.yaml` file will be created.
Usage of this feature should be uncommon. For this …
=> feat(riff-raff.yaml): Support user-added deployment types

docs/setting-up-a-gucdk-project.md, script/ci-project-generation, src/bin/commands/new-project/index.ts, src/bin/commands/new-project/utils/app.ts, src/bin/commands/new-project/utils/imports.ts, src/bin/index.ts, src/constructs/root.ts, src/experimental/constructs/index.ts, src/riff-raff-yaml-file/README.md, src/riff-raff-yaml-file/deployments/autoscaling.ts, src/riff-raff-yaml-file/deployments/cloudformation.ts, src/riff-raff-yaml-file/deployments/lambda.ts, src/riff-raff-yaml-file/group-by.ts, src/riff-raff-yaml-file/index.test.ts, src/riff-raff-yaml-file/index.ts, src/riff-raff-yaml-file/types.ts
Following https://github.com/guardian/cdk/pull/2042 GuCDK is now able to support any `riff-raff.yaml` file, and can therefore be considered stable!
This change renames `GuRootExperimental` to `GuRoot`, and `RiffRaffYamlFileExperimental` to `RiffRaffYamlFile`. The import paths have also been updated, removing the `experimental` directory:
From:
```ts
import { GuRootExperimental } from "@guardian/cdk/lib/experimental/constructs/root";
```
To:
```ts
import { GuRoot } from "@guardian/cdk/lib/constructs/root";
```
For this reason, this is deemed a breaking change.
As `GuRoot` is stable, it has been added to the project generator. Generation of a `riff-raff.yaml` file requires knowledge of a `GuStack`'s region. Therefore the project generator has also been updated, adding a `region` flag …
=> feat(riff-raff.yaml)!: Promote generator to stable

.github/workflows/cd.yaml
Following the changes in #2071, the release of the GitHub Pages site during CD has broken:
This change updates how `GITHUB_REPOSITORY` is referenced to fix the build. https://docs.github.com/en/actions/security-guides/automatic-token-authentication#example-2-calling-the-rest-api used for inspiration.
It's a bit difficult to test as this part of the workflow has a condition to only run on the main branch. The real test will happen upon merge.
I've run the workflow manually to ensure the syntax is valid.
CD works again.
N/A
[^2]: If you are adding a new construct or …
=> cd: Fix env var reference

docs/setting-up-a-gucdk-project.md
Link to the correct URL on the Node.js website: https://nodejs.org/en/about/previous-releases
Reminders that “[Cool URIs don’t change](https://www.w3.org/Provider/Style/URI)”
Clickity-click the linkity-link!
Prevent linkrot.
N/A
=> docs(setup): fix link to node versions

.github/workflows/cd.yaml
PRs raised by the standard GitHub Actions user do not have their workflows run (see https://github.com/guardian/cdk/pull/2084#issuecomment-1786770078). Therefore we need to use our own token to have CI run on PRs from changesets.
This is inspired by https://github.com/guardian/cdk/pull/1512.
N/A
Changeset PRs are mergeable.
N/A
=> cd: Use the `guardian-ci` user to author automatic PRs

.changeset/chatty-rabbits-cry.md, src/riff-raff-yaml-file/index.test.ts, src/riff-raff-yaml-file/index.ts
Currently the `riff-raff.yaml` generator is not able to create dependencies between `cloud-formation` deployments. This means each `cloud-formation` deployment could happen at the same time.
This does not work in the scenario where we have:
- Stack A containing a bucket
- Stack B CODE containing an app that uses A's bucket
- Stack B PROD containing an app that uses A's bucket
That is, we can't guarantee Stack A is deployed first.
In this change we add support for the scenario where we have a shared resources stack. The generated `riff-raff.yaml` file will describe that Stack B CODE, and Stack B PROD depend on Stack A.
It uses the AWS CDK mechanism to link CloudFormation stacks:
> Add a dependency between this stack and another stack.
> 
> This can be used to define dependencies between …
=> feat(riff-raff.yaml): Support cross stack dependencies

.changeset/lazy-wasps-repair.md, src/aspects/aws-backup.test.ts, src/aspects/aws-backup.ts, src/constructs/core/stack.ts
Adds a new property `withBackup` to `GuStack` to enable [backups provided by DevX](https://github.com/guardian/aws-backup). It is defaulted to `false`.
When `true`, all supported resources in the stack will receive a new tag `devx-backup-enabled`. To opt in/out an individual resource, you can manually apply this tag.
This change uses [Aspects](https://docs.aws.amazon.com/cdk/v2/guide/aspects.html).
Observe the added tests.
With this flag, one doesn't need to know the name of the tag. That is, the DX should be a little simpler.
N/A.
[^2]: If you are adding a new construct …
=> feat(backup): Support backups provided by DevX

docs/migration-guide-ec2.md
- Update migration guide to remove reference to a diff script that no longer exists
- Provide alternative guidance on viewing cfn change sets
Would close #2192 
- Are the new instructions clear?
- Do they represent the recommended way to check a cfn diff with cdk?
- There is `npm run diff`, as defined in the cdk template's package.json, which is a possible alternative. But I haven't been able to get this to work yet, myself.[^1]
This is purely a documentation change, and shouldn't require a new release of the cdk package, so I haven't added a changset.
[^1]: I get an error: `Unable to resolve AWS account to use. It must be either configured when you define your CDK Stack, or through the environment`. I've tried exporting an `AWS_PROFILE` variable before running `npm run diff` but this …
=> Remove reference to non-existent diff script from migration guide

.changeset/gold-maps-give.md, src/constructs/core/parameters/s3.ts, src/patterns/ec2-app/base.test.ts, src/patterns/ec2-app/base.ts
Use a singleton to reference the string parameter that contains the name of the S3 bucket used for load balancer access logs.
Previously, a new parameter was created per EC2 instance. This meant that only one EC2 in a given stack could have access logs enabled, as attempting to create another one would result in a synth failure due to a parameter with that name already existing.
This change makes it so a new parameter is only created if it doesn't exist in the stack. Subsequent invocations will reference the existing parameter instead of creating a new one.
I've added a new test case where 2 EC2 apps exist in the same stack, both with access logs enabled.
[^1]: Consider whether this is something that will mean changes to projects that have already been migrated, or to the CDK CLI tool. If …
=> feat: Support more than one EC2 app with load balancer access logs enabled in a given stack

.changeset/moody-needles-end.md, src/constructs/iam/policies/ssm-ssh.ts, src/constructs/iam/roles/__snapshots__/instance-role.test.ts.snap, src/constructs/iam/roles/instance-role.test.ts, src/constructs/iam/roles/instance-role.ts, src/patterns/ec2-app/__snapshots__/base.test.ts.snap
The [SSM+SSH capability](https://github.com/guardian/ssm-scala?tab=readme-ov-file#in-aws) requires an IAM Policy.
This change swaps the [AmazonSSMManagedInstanceCore](https://docs.aws.amazon.com/aws-managed-policy/latest/reference/AmazonSSMManagedInstanceCore.html) AWS Managed Policy with one of our own to more closely follow the principle of least privilege.
In addition to enabling SSM+SSH, AmazonSSMManagedInstanceCore adds permissions to read _all_ SSM Parameters.
<details><summary>AmazonSSMManagedInstanceCore policy statement</summary>
<p>
```json
{
"Version" : "2012-10-17",
"Statement" : [
{
"Effect" : "Allow",
"Action" : [
"ssm:DescribeAssociation",
"ssm:GetDeployablePatchSnapshotForInstance",
"ssm:GetDocument",
"ssm:DescribeDocument",
"ssm:GetManifest",
"ssm:GetParameter", …
```
=> fix(ec2)!: Tighten default EC2 access to SSM Parameters

.changeset/gentle-cups-dress.md, src/patterns/ec2-app/base.ts
- Switch hardcode `INFRA` stage in Cognito lambda config to use `PROD`
- Allow users to optionally use the `CODE` Cognito lambda environment.
Still figuring that out.
We've started merging dependabot PRs again for cognito-auth lambda, the problem with switching from INFRA to PROD is that users still on INFRA will start to slowly become more and more out of date. 
=> Switch from using `INFRA` stage of cognito-lambda to using `PROD` and allow users to optionally use `CODE`

.changeset/soft-bears-drum.md, src/constructs/core/stack.ts
Fixes a bug where `this.app` on a `GuStack` is always undefined, as it is never set. See https://github.com/guardian/cdk/pull/1497#issuecomment-1480997050.
Also included, is a refactor to reduce complexity - private properties and public getters are replaced with public properties.
=> fix(GuStack): Set app value 

src/constructs/cloudwatch/__snapshots__/lambda-alarms.test.ts.snap, src/constructs/lambda/lambda.test.ts, src/constructs/lambda/lambda.ts, src/experimental/patterns/__snapshots__/kinesis-lambda.test.ts.snap, src/experimental/patterns/__snapshots__/sns-lambda.test.ts.snap, src/patterns/__snapshots__/api-lambda.test.ts.snap, src/patterns/__snapshots__/api-multiple-lambdas.test.ts.snap, src/patterns/__snapshots__/scheduled-lambda.test.ts.snap
I think JSON log formatting is a more sensible default value.
There are two log formats in AWS Lambda, `Text`, and `JSON`. `Text` is the default (possibly for historical reasons?), but has disadvantages, such as not being as easily machine-readable.
Using `Text` means that any changes made to the ApplicationLogLevel will be flat out ignored (defaulting to `DEBUG` as far as I can tell). Application log filtering **only** works when the log format is `JSON`.
I've verified that Lambdas using this configuration are still compatible with Central ELK. [Repocop](https://github.com/guardian/service-catalogue/pull/769) has been using JSON logging for several weeks without issue.
Teams will be able to filter their application logs by severity level without having to do as much googling/asking …
=> feat: GuLambdaFunction should use JSON logging by default

.changeset/six-shrimps-jam.md, src/constructs/rds/instance.test.ts, src/constructs/rds/instance.ts
This PR adds support for DevX Backups to our RDS instance construct. Users are now forced to opt-in/out of backups when provisioning an RDS instance via this construct. This makes it less likely that we will forget to add protection to important backups. Users who choose to provision an RDS instance via an AWS construct (instead of the GuCDK one) can still currently forget to make this choice (we will improve this in a follow up PR by modifying [this aspect](https://github.com/guardian/cdk/blob/main/src/aspects/aws-backup.ts) to check for the presence of the correct tag).
Additionally, we help to avoid conflicts by preventing users who opt-in to this feature from setting native RDS backup properties that cannot be managed via CloudFormation once AWS Backup is enabled. Users who opt-out of …
=> feat!: Add DevX Backups support to RDS instance construct

docs/contributing.md
It looks like we are using changesets now (see https://github.com/guardian/cdk/pull/2071) so I've updated the docs to reflect this.
=> docs: update release documentation

.changeset/grumpy-socks-divide.md, src/constructs/dynamodb/dynamodb.test.ts, src/constructs/dynamodb/dynamodb.ts, src/constructs/dynamodb/index.ts
This PR adds a construct for dynamoDB tables
This construct will enable deletion protection by default.
It also adds a mandatory opt-in/opt-out field for aws backups.
This last forces a decision on whether or not to use the AWS backup vault to protect backup data from accidental or malicious deletion.
This decision should almost always be yes, however there are circumstances in which a team might need to use a different form of storage for their backup. The important thing is that the decision is made explicitly.
If users opt-out, they will need to provide a reason for their decision. This is to allow this information to be captured in security audits.
This is a new construct, so will not be a breaking change.
Unit tests added to cover main scenarios.
New stacks created in CDK have …
=> Add Dynamodb construct with default deletion protection and mandatory opt-in/opt-out setting for DevX-backup

.changeset/nice-cups-study.md, src/constructs/autoscaling/asg.ts, src/patterns/ec2-app/__snapshots__/base.test.ts.snap
When diagnosing performance issues with EC2 apps, it's really useful to know the historic context of how many EC2 instances have been present in the Auto-Scaling Group - like, [_"how long have we been running MAPI mobile-fronts with 29 instances?"_](https://github.com/guardian/mobile-apps-api/pull/2865#issuecomment-2000014076) - unfortunately, by default, ASGs don't record these metrics and they need to be explicitly enabled.
There's a cost associated with every CloudWatch metric recorded, and I understand there's always a pressure for costs to be kept down. But it's not really possible to know in advance when we're going to need these metrics, and when we need them, we really do need them - otherwise performance diagnosis is missing crucial parts of the puzzle.
To minimise the cost here, …
=> feat: Add useful ASG group metrics (`TOTAL_INSTANCES`, etc) by default

.changeset/grumpy-experts-divide.md, src/constructs/autoscaling/asg.ts, src/patterns/ec2-app/base.test.ts, src/patterns/ec2-app/base.ts
We want to try to replace some of riffraffs scaling behaviour by using UpdatePolicies to rotate instances in an ASG whenever a deployment happens instead of "manually" rotating the instances with RiffRaff.
We used `npm link` to test these changes in cdk-playground and found them to work as we expect. We've also added a test to this PR to ensure that the update policy is correctly passed through to the Cloudformed ASG.
=> feat(asg): Allow setting the UpdatePolicy on ASGs provisioned by our EC2 patterns

.changeset/thick-owls-remain.md, src/constructs/autoscaling/asg.test.ts, src/constructs/autoscaling/asg.ts, src/constructs/autoscaling/user-data.ts, src/patterns/ec2-app/__snapshots__/base.test.ts.snap, src/patterns/ec2-app/base.test.ts, src/patterns/ec2-app/base.ts, src/patterns/ec2-app/framework.test.ts
Updates our EC2 Pattern to require an explicit `UserData` prop instead of a `string`. This is part of our work to enable Cloudformation Replace deployments in our ASG.
This is a BREAKING change as applications relying on the type being a `string` will need to make a code change in order to update their GuCDK version.
Details on this change can be found in the included changeset file: [.changeset/thick-owls-remain.md](https://github.com/guardian/cdk/blob/24a6171cfb9e720817bfb2d461bfab5e5f4a4965/.changeset/thick-owls-remain.md)
=> feat(ec2): Require explicit `UserData` type instead of `string` in Pattern props.

.changeset/fresh-icons-vanish.md, src/constructs/autoscaling/asg.ts, src/patterns/ec2-app/base.test.ts, src/patterns/ec2-app/base.ts
This PR adds the ability to set the `detailedMonitoring` attribute on an auto scaling group's launch template when either creating one directly or via the Gu EC2 App pattern.
This option provides greater levels of metric gathering: 
> All metrics, including status check metrics, are available in 1-minute periods. To get this level of data, you must specifically enable it for the instance. For the instances where you've enabled detailed monitoring, you can also get aggregated data across groups of similar instances.
This was motivated by a requirement in Ophan to have certain metrics at a higher granularity to facilitate scaling policies. 
I've added a unit test for this case, let me know if anything else would be useful. 
We can have CPU Utilisation at a minute interval for scaling …
=> Add detailed monitoring option to GuEC2App pattern

.changeset/perfect-hats-allow.md, src/constructs/loadbalancing/alb/application-listener.ts
SslPolicy is not valid on HTTP listeners, and if set causes deploy to fail - see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-listener.html#cfn-elasticloadbalancingv2-listener-sslpolicy
Uses the same condition as the protocol switcher to disable the sslPolicy if a certificate isn't defined, meaning we're building an HTTP listener.
Create and deploy a stack using an HTTP listener is now possible
=> Only set an SSL policy on HTTPS application listeners

.changeset/cold-coins-flow.md, src/constructs/autoscaling/asg.ts, src/patterns/ec2-app/__snapshots__/base.test.ts.snap
https://github.com/guardian/instance-tag-discovery recommends enabling tags on instance metadata, but that option isn't available to users of the EC2 patterns in gucdk. This doesn't have any real problems, [aside from an error log on startup](https://logs.gutools.co.uk/goto/61f12e30-613d-11ef-9d32-0b00a291b047) that currently can't be resolved and can cause confusion.
This PR enables the option for all users of the EC2 patterns. I could have made it a configurable option, but I've neither thought up nor discovered a reason _not_ to have it enabled, so I opted to hard-code it to true. I'd be happy to relax that back to a configurable option if there's any objection though! 
See the updated snapshots.
Error logs from `instance-tag-discovery` should fall as users adopt the new version.
Could …
=> enable InstanceMetadataTags on EC2 patterns

.changeset/sweet-olives-refuse.md, src/patterns/__snapshots__/scheduled-lambda.test.ts.snap, src/patterns/scheduled-lambda.test.ts, src/patterns/scheduled-lambda.ts
Currently the `GuScheduledLambda` pattern lets you pass in schedules, but you cannot associate an input with each schedule.
This PR changes the props to optionally take a `RuleTargetInput` value with each scheduled rule.
=> Allow inputs in GuScheduledLambda

.changeset/rare-geese-wait.md, src/constructs/autoscaling/asg.ts, src/patterns/ec2-app/__snapshots__/base.test.ts.snap
Extends on https://github.com/guardian/cdk/pull/2255 to collect all ASG level metrics as standard. These metrics _should_ come at no extra cost, at least the docs state:
> Group metrics are available at one-minute granularity at no additional charge, but you must enable them.
> – https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-metrics.html.
UPDATE: After raising an AWS have responded to a support ticket about this:
> Amazon EC2 Auto Scaling Group Metrics have no additional charge to enable. They are similar to EC2 basic monitoring metrics, which is also sent for free to Cloudwatch.
> 
> Amazon EC2 Auto Scaling fleet management for EC2 instances carries no additional fees. The dynamic scaling capabilities of Amazon EC2 Auto Scaling are enabled by Amazon CloudWatch …
=> feat(asg): Collect all ASG level metrics

.changeset/happy-badgers-compare.md, src/experimental/patterns/__snapshots__/ec2-app.test.ts.snap, src/experimental/patterns/ec2-app.test.ts, src/experimental/patterns/ec2-app.ts, src/riff-raff-yaml-file/index.test.ts, src/riff-raff-yaml-file/index.ts
Reduce the “time spent broken” after failed deploys, making [these manual steps](https://github.com/guardian/riff-raff/blob/fc88a4ca485c93423e62724cea4cbc266daa9f00/riff-raff/public/docs/howto/fix-a-failed-deploy.md) redundant, by adding a new [experimental](https://github.com/guardian/cdk/blob/main/docs/architecture-decision-records/005-x01-package-structure.md) pattern `GuEc2AppExperimental` to provision an EC2 based service with an [`AutoScalingRollingUpdate` update policy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html#cfn-attributes-updatepolicy-rollingupdate). The configuration is based on a number of [tests](https://github.com/guardian/testing-asg-rolling-update) we ran; we've [documented some various …
=> feat(experimental-ec2-pattern): Pattern to deploy ASG updates w/CFN

.changeset/popular-laws-thank.md, src/experimental/patterns/__snapshots__/ec2-app.test.ts.snap, src/experimental/patterns/ec2-app.ts
When deploying Prism with the `GuEc2AppExperimental` for the first time, the deployment [failed](https://riffraff.gutools.co.uk/deployment/view/dab404bb-30aa-49f0-9be0-361f88a44490?verbose=1) with the cloud-init-output logs stating:
```log
An error occurred (AccessDenied) when calling the DescribeTargetHealth operation: User: arn:aws:sts::000000000000:assumed-role/prism-CODE-InstanceRolePrism/i-0cee86d64de253ca4 is not authorized to perform: elasticloadbalancing:DescribeTargetHealth because no identity-based policy allows the elasticloadbalancing:DescribeTargetHealth action
```
This suggests the instance update was started before the policy that grants these permissions was created.
Make the ASG [depend on](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-depend …
=> fix(experimental-ec2-pattern): Create Policy first

.changeset/wise-starfish-prove.md, CHANGELOG.md, package.json
v59.5.3 was published by mistake whilst trying to publish a beta build from the `beta` branch.
Instead of unpublishing 59.5.3 which would leave a hole in our NPM versions as per https://docs.npmjs.com/policies/unpublish instead publish a new 59.5.4 version which reverts the changes that were made in 59.5.3.
Also include the latest version bumps.
=> fix: Publish new version reverting 59.5.3

.changeset/brave-pots-act.md, package.json, src/constructs/ecs/__snapshots__/ecs-task.test.ts.snap, src/constructs/ecs/ecs-task.ts
Previously we could only launch x86 ecs tasks. This resolves that.
Note - @akash1810 suggested pulling the ecs task out of GuCDK since it's only used by investigations. V happy to do this but in the short term it would be helpful to have this extra configuration property
I've tested this by deploying to a project in the investigations account.
=> Parameterise cpuArchitecture for GuEcsTask

.changeset/bright-lamps-repair.md, src/constructs/ec2/vpc.ts, src/constructs/ecs/__snapshots__/ecs-task.test.ts.snap, src/constructs/ecs/ecs-task.test.ts, src/constructs/ecs/ecs-task.ts, src/patterns/scheduled-ecs-task.test.ts
I ran into an issue when working with the ecs-task role where I found it only worked if you provided a cdk context file. This was because, by default an EcsRunTask will try to assign itself to the 'PRIVATE' subnets identified by the cdk context file. This works for lurch (which was the project the Ecs task role was created for) because that project is a private repo, with a [checked in context file](https://github.com/guardian/lurch/blob/main/packages/infra/cdk.context.json#L8).
Relying on a context file isn't ideal. This PR removes the need for a context file by requiring consumers to either specify which subnets to use directly, or falling back to using `GuVpc.subnetsFromParameterFixedNumber`
But what is `GuVpc.subnetsFromParameterFixedNumber`?
Unfortunately, when I tried to use just …
=> feat: Require subnet property for ecs task, new subnetsFromParameter property

.changeset/yellow-chefs-laugh.md, src/experimental/patterns/ec2-app.test.ts, src/experimental/patterns/ec2-app.ts, src/riff-raff-yaml-file/deployments/cloudformation.ts, src/riff-raff-yaml-file/index.test.ts, src/riff-raff-yaml-file/index.ts, src/riff-raff-yaml-file/types.ts, src/utils/test/index.ts, src/utils/test/template.ts
Updates the `riff-raff.yaml` generator to add the newly added `minInstancesInServiceParameters` property. See also https://github.com/guardian/riff-raff/pull/1383.
To support this change, a number of refactor changes have also been made. For that reason reviewing [commit by commit](https://github.com/guardian/cdk/pull/2476/commits) is advised.
This completes the changes in #2417, specifically addressing [these comments](https://github.com/guardian/cdk/pull/2417#discussion_r1759408280).
See added unit tests.
Full support for the new ASG deployment mechanism (AutoScalingRollingUpdate).
N/A.
[^1]: Consider whether this is something that will mean changes to projects that have already been migrated, or to the CDK CLI tool. If changes are required, consider adding a checklist here and/or …
=> feat(riff-raff.yaml): Add `minInstancesInServiceParameters` when applicable

package-lock.json, package.json
Reverts guardian/cdk#2517. v0.27.0 moved to ESM, which we're not yet ready for as evidenced in the [cd.yaml workflow](https://github.com/guardian/cdk/blob/main/.github/workflows/cd.yaml) failing on `main`:
I hadn't read the release notes closely enough; I saw it was a minor version change and thought it'd be safe. I forgot that in the semver spec _any_ minor change in the 0 major can be breaking!
=> Revert "chore(deps): bump typedoc from 0.26.11 to 0.27.0"

.changeset/soft-scissors-turn.md, src/constructs/rds/instance.test.ts, src/constructs/rds/instance.ts
Hello my old friends 👋 
While doing some DB work, I got curious and noticed that `GuDatabaseInstance` defaults to the older class of SSD storage `gp2`, which is outclassed by the newer `gp3` in terms of both performance and costs.
There is really no reason to use `gp2` these days, but I'm going to be cynical and assume that Amazon defaults to that because they can charge more for it and get away with it.
Even the official AWS docs say you should default to `gp3`: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html#Concepts.Storage.GeneralSSD
I've added a couple of tests to verify that you can still override the storage type, if you wish to do so.
Cheaper AWS bill (roughly 35% cheaper with the same storage requirements and IOPS - …
=> feat: Default to GP3 storage type in RDS for better performance and cost saving

.changeset/friendly-trainers-cry.md, src/constructs/iam/roles/__snapshots__/github-actions.test.ts.snap, src/constructs/iam/roles/github-actions.ts
This significantly changes the resources constructed by `GuGithubActionsRole`, specifically, **the construct will no longer instantiate a `GitHubOidcProvider`**. This is because you can only ever have one `GitHubOidcProvider` per provider domain (ie `token.actions.githubusercontent.com`) - while we may want multiple instances of `GuGithubActionsRole` in an AWS account, we can't have the `GuGithubActionsRole` construct trying to make a new `GitHubOidcProvider` with each instance.
Consequently, you will need to instantiate the `GitHubOidcProvider` elsewhere as a singleton. At the Guardian, we do this with https://github.com/guardian/aws-account-setup.
Fixes https://github.com/guardian/cdk/issues/2529.
=> Support multiple usages of `GuGithubActionsRole` in a single AWS account

.changeset/nasty-parrots-mix.md, src/constructs/iam/roles/github-actions.test.ts, src/constructs/iam/roles/github-actions.ts
Apply the standard `Stack`, `Stage`, `App` and `gu:repo` tags to the `AWS::IAM::OIDCProvider` resource created by the `GitHubOidcProvider` construct.
This was previously absent as we're creating `AWS::IAM::OIDCProvider` via a level 1 construct; AWS CDK only automatically tags level 2 constructs.
See the added unit test. The test uses the [`hasGuTaggedResource`](https://github.com/guardian/cdk/blob/5f483a0abe04e4f962729f5fa43ba1a7f3afb664/src/utils/test/assertions.ts#L67) assertion helper.
Tagging resources makes it easier to identify their origin, and to allocate costs, etc.
N/A.
[^1]: Consider whether this is something that will mean changes to projects that have already been migrated, or to the CDK CLI tool. If changes are required, consider adding a checklist here and/or linking to …
=> fix(GitHubOidcProvider): Ensure `AWS::IAM::OIDCProvider` resource is tagged

.changeset/neat-roses-smell.md, src/constructs/iam/policies/index.ts, src/constructs/iam/policies/kcl.test.ts, src/constructs/iam/policies/kcl.ts
The new `GuKCLPolicy` construct creates an `AWS::IAM::Policy` to grant all the required permissions for the [Kinesis Client Library](https://github.com/awslabs/amazon-kinesis-client) - specifically for KCL **v3**, which requires [many additional permissions](https://docs.aws.amazon.com/streams/latest/dev/kcl-iam-permissions.html) over KCL v2 (largely because KCL 3.x introduced **two** new DynamoDB tables for metadata: [worker metrics](https://docs.aws.amazon.com/streams/latest/dev/kcl-dynamoDB.html#kcl-worker-metrics-table) & [coordinator state](https://docs.aws.amazon.com/streams/latest/dev/kcl-dynamoDB.html#kcl-coordinator-state-table)).
This PR is an example of swapping out existing KCL v2 policy code to use the new `GuKCLPolicy` construct:
* …
=> Add `GuKCLPolicy`, a IAM-policy construct for the Kinesis Client Library (KCL)

.changeset/dirty-kids-camp.md, src/constructs/iam/policies/kcl.test.ts, src/constructs/iam/policies/kcl.ts
This fixes up a problem with this recent PR:
* https://github.com/guardian/cdk/pull/2578
Construct ids can not have unresolved tokens - but projects like `apple-news` load the name of the Kinesis stream from an SSM parameter, then [use it](https://github.com/guardian/apple-news/blob/79ac5e951ed37c5840d8b56212d5fffd3382deb6/cdk/lib/apple-news.ts#L103) as part of the 'application name':
```yaml
applicationName: `${crierStreamName}_apple-news-${this.stage}-LIVE`
```
This means that sadly we _can't_ use the application name as part of the construct id for the `GuKCLPolicy` (an alteration made with 5ab19bc6e49af3413b84f3a3b1da4cf51eb81dfc)...
https://github.com/guardian/cdk/blob/5ab19bc6e49af3413b84f3a3b1da4cf51eb81dfc/src/constructs/iam/policies/kcl.ts#L54
...if we do, with `apple-news`, we …
=> Fix construct id for `GuKCLPolicy`

.changeset/rare-plums-fix.md, src/constructs/autoscaling/asg.ts, src/patterns/ec2-app/base.ts
When this property was set to `true`, launched instances would not meet the [FSBP EC2.8 control](https://docs.aws.amazon.com/securityhub/latest/userguide/ec2-controls.html#ec2-8). Removing this property reinforces that GuCDK provides a paved path, following best practice by default.
If for whatever reason one needs to disable IMDSv2, the escape hatch patten can be used:
```typescript
import { CfnLaunchTemplate } from "aws-cdk-lib/aws-ec2";
declare const asg: GuAutoScalingGroup;
// Set the value to "optional", allowing IMDSv1 and IMDSv2.
// See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-metadataoptions.html#cfn-ec2-launchtemplate-metadataoptions-httptokens.
launchTemplate.addPropertyOverride("LaunchTemplateData.MetadataOptions.HttpTokens …
```
=> feat: Remove `withoutImdsv2` property from `GuEc2App` and `GuAutoScalingGroup`

.changeset/social-streets-rescue.md, src/constructs/ecs/ecs-task.test.ts, src/constructs/ecs/ecs-task.ts, src/patterns/ec2-app/base.ts, src/patterns/scheduled-ecs-task.test.ts
Addresses two deprecation warnings from AWS CDK:
- In a `Cluster` [`containerInsights` is deprecated in favour of `containerInsightsV2`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs.Cluster.html#containerinsightsspan-classapi-icon-api-icon-deprecated-titlethis-api-element-is-deprecated-its-use-is-not-recommended%EF%B8%8Fspan). This requires a new (patch) release as the props for the `GuEcsTask` construct have changed too.
- In an AutoScalingGroup [`healthCheck` is deprecated in favour of `healthChecks`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_autoscaling.AutoScalingGroup.html#healthcheckspan-classapi-icon-api-icon-deprecated-titlethis-api-element-is-deprecated-its-use-is-not-recommended%EF%B8%8Fspan). This does not require a release, as this option …
=> fix: Resolve two deprecation warnings from AWS CDK

.changeset/cyan-worlds-grab.md, src/constructs/autoscaling/asg.test.ts, src/constructs/autoscaling/asg.ts, src/constructs/autoscaling/user-data.test.ts, src/experimental/patterns/__snapshots__/ec2-app.test.ts.snap, src/experimental/patterns/ec2-app.test.ts, src/patterns/ec2-app/__snapshots__/base.test.ts.snap, src/patterns/ec2-app/base.test.ts, src/patterns/ec2-app/base.ts, src/patterns/ec2-app/framework.test.ts, src/riff-raff-yaml-file/index.test.ts
Replaces the `enabledDetailedInstanceMonitoring` optional property from the `GuEc2App` pattern with a mandatory `instanceMetricGranularity` property. There are two values: `1Minute`, `5Minute`. By default, AWS produces metrics every 5 minutes.
Adding a mandatory property aims to encourage teams to enable granular metrics in production as it allows for earlier horizontal scaling and provides more detail during incident triage.
> [!NOTE]
> - This change will cost roughly $3 per instance per month. We might want to consider disabling it for non-production environments.
> - These are not the same as metrics from the [CloudWatch Agent](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/metrics-collected-by-CloudWatch-agent.html), which services might also be using.
See also:
- …
=> feat(GuEc2App): Replace `enabledDetailedInstanceMonitoring` optional property with mandatory `instanceMetricGranularity` property

.changeset/better-eels-judge.md, src/experimental/patterns/__snapshots__/ec2-app.test.ts.snap, src/experimental/patterns/ec2-app.test.ts, src/experimental/patterns/ec2-app.ts
Adds [slow start mode](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/edit-target-group-attributes.html#slow-start-mode) support to the new/experimental deployment mechanism (which was added in https://github.com/guardian/cdk/pull/2417).
I've used `cdk-playground` to test this.
There is a successful deployment example [here](https://github.com/guardian/cdk-playground/pull/703).
I've also created a special build that starts failing the healthcheck _whilst the instance is in slow start mode_, to demonstrate the new failure case - an example for that can be found [here](https://github.com/guardian/cdk-playground/pull/704).
This allows high-traffic services to warm-up instances before sending them a full share of requests. The Ophan team have recently found this to be a …
=> feat: add slow start support to new deployment mechanism

.changeset/lovely-onions-relate.md, src/constructs/ecs/ecs-task.ts
Updates the import path to resolve the following in clients CI builds:
```
error TS2307: Cannot find module 'aws-cdk-lib/aws-ecs/lib/cluster' or its corresponding type declarations.
```
Observe CI, it should pass.
N/A.
N/A.
=> fix(GuEcsTask): Update import path of `ContainerInsights`

.changeset/sharp-snakes-glow.md, src/experimental/patterns/ec2-app.test.ts, src/experimental/patterns/ec2-app.ts, src/utils/test/template.ts
We recently [attempted](https://github.com/guardian/mobile-apps-api/pull/3610) to use the new deployment mechanism (introduced in https://github.com/guardian/cdk/pull/2417) with a service which [scales horizontally (based on CPU)](https://github.com/guardian/mobile-apps-api/blob/d20ad7030afcc07c86c64aef54e413611a60a8e1/cdk/lib/microservice.ts#L208-L210).
Although testing in `CODE` worked as expected and the [snapshot tests looked correct](https://github.com/guardian/mobile-apps-api/blob/32da5bb899d007e1720291d4f859d6911bf155bf/cdk/lib/__snapshots__/microservice.test.ts.snap#L16871-L16875), the deployment to `PROD` did not work as desired because:
a) I had forgotten to add [some important Riff-Raff config](https://github.com/guardian/mobile-apps-api/pull/3818/commits/df56488afac795ddf6e4f97 …
=> feat(experimental-ec2-pattern): Improve safety of new deployment mechanism

.changeset/yummy-points-clap.md, src/constants/regex-pattern.test.ts, src/constants/regex-pattern.ts
The regex [isn't used](https://github.com/search?q=org%3Aguardian%20RegexPattern.S3ARN&type=code) (other than within tests of this repository), so we can safely remove it.
N/A.
Resolves https://github.com/guardian/cdk/security/code-scanning/1.
N/A.
- ~[ ] I have listed any breaking changes, along with a migration path [^1]~
=> fix: Remove unused `RegexPattern.S3ARN`

.changeset/great-eyes-tan.md, src/constructs/cloudwatch/__snapshots__/ec2-alarms.test.ts.snap, src/constructs/cloudwatch/ec2-alarms.test.ts, src/constructs/loadbalancing/alb/application-listener.test.ts, src/constructs/loadbalancing/alb/application-load-balancer.test.ts, src/constructs/loadbalancing/alb/application-load-balancer.ts, src/experimental/patterns/__snapshots__/ec2-app.test.ts.snap, src/experimental/patterns/ec2-app.test.ts, src/patterns/ec2-app/__snapshots__/base.test.ts.snap, src/patterns/ec2-app/base.test.ts, src/patterns/ec2-app/base.ts, src/patterns/ec2-app/framework.test.ts
> [!NOTE]
> - This is an alternative to https://github.com/guardian/cdk/pull/2739. This change does not default the region as there were a bit too many edge-cases to this at the moment.
> - Easiest to review [commit by commit](https://github.com/guardian/cdk/pull/2742/commits).
The `access_logs.s3.enabled` Application Load Balancer attribute is now explicitly set, with a default value of `true`, enabling access logs by default. Previously this was opt-in behaviour. These logs are written to an S3 bucket in the same AWS account as the ALB and are queryable with Athena.
Consequently, the optional `accessLogging` object property for a `GuEc2` app (and it subclasses) has been removed. In its place is a `withAccessLogging` boolean property with a default value of `true`.
The `accessLogging` …
=> feat!: Enable access logging by default on Application Load Balancers 
