guardian/cdk

package-lock.json
package.json

This bumps the package version to 0.1.1, taking in changes made to the repository. cc @jorgeazevedo 
In the future, we should decide on how we would like to go about safely bumping the package.
No.

Bump npm version to 0.1.1

---

package.json

Well, it looks like https://github.com/guardian/cdk/pull/20 is totally wrong! So this removes an entry in `peerDependencies` that is duplicated in `dependencies` for brevity.
No.
n/a
DRYer `package.json`?
n/a
n/a

remove peer deps which are duplicated in dependencies

---

README.md
package-lock.json
src/constructs/autoscaling/asg.test.ts
src/constructs/autoscaling/asg.ts

This PR adds unit tests for the `GuAutoScalingGroup` component. These tests each cover a specific piece of functionality and assert it directly, rather than making use of snapshots. 
This is different to how many of our tests work so far so I'm interested to hear thoughts on whether it's an approach we should or shouldn't take going forward (either instead or as well as snapshots of our constructs). Below are some thoughts on the pros and cons of each method. 
**Snapshots**
[+] Quick and easy to write
[+] Pick up any changes to the output cloudformation (particularly useful for unintended side effects)
[-] A change to the component may cause many unrelated tests to also fail
[-] When testing different permutations of a component, a number of snapshots will be created, each of which …

Add tests for GuAutoScalingGroup

---

README.md
package-lock.json
package.json

Uses [`np`](https://www.npmjs.com/package/np) to orchestrate the release steps, reducing the amount of manual work needed.
The biggest wins are that `np` will:
- ensure we're on the release branch (`main`)
- ensure we're up to date with release branch
- run tests
- push tags
It also:
> Warns about the possibility of extraneous files being published
This was yielding output similar to that below. Although this is related to [this issue](https://github.com/sindresorhus/np/issues/577), we can take this as an opportunity to simplify our `package.json` as the `files` setting was only ever temporary IIUC.
In the ideal world, we'd use something like [semantic-release](https://github.com/semantic-release/semantic-release) for a fully automated publishing process, however this requires an npm …

Use np to orchestrate release steps

---

src/constructs/core/identity.ts

This PR creates a new identity interface which can be used Where there a places that take stack, stage and app params as input to save typing them out every time.
No.
n/a
Reduced duplication of the stack, stage and app type definitions.
n/a
n/a

Add an identity interface

---

src/constructs/iam/policies.test.ts
src/constructs/iam/policies.ts
src/constructs/iam/roles.test.ts

This PR adds tests for the IAM constructs. 
No.
Run the new test suite.
IAM constructs have good coverage.
n/a
n/a

Add tests for IAM constructs

---

src/constructs/rds/instance.test.ts

This PR adds tests for the RDS constructs. 
No.
Run the new test suite.
RDS constructs have good coverage.
n/a
n/a

Add tests for RDS instance

---

src/constructs/loadbalancing/elb.test.ts
src/constructs/loadbalancing/elb.ts

This PR adds tests for the loadbalancing constructs. 
No.
Run the new test suite.
Loadbalancing constructs have good coverage.
n/a
n/a

Add tests for loadbalancing constructs

---

src/constructs/iam/policies/log-shipping.test.ts
src/constructs/iam/policies/log-shipping.ts
src/constructs/iam/policies/s3-get-object.test.ts
src/constructs/iam/policies/s3-get-object.ts
src/constructs/iam/policies/ssm.ts
src/patterns/__snapshots__/instance-role.test.ts.snap
src/patterns/instance-role.test.ts
src/patterns/instance-role.ts

Extending multiple interfaces yields a simpler interface and consistent variable names.
No.
Observe CI?
Simpler code?
n/a
n/a

simplify interface InstanceRoleProps

---

src/constructs/core/stack.ts

This provides a slightly nicer API, very slightly! Also applies tags to launched instances by default.
No.
n/a
An ever so slightly nicer API.
n/a
n/a

add helper function to add tags

---

package.json

The [semver spec](https://semver.org/#spec-item-4) says:
> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.
We can use this to simplify our release numbers into 0.Y.0 as patch numbers hold little meaning at the moment. Update the [call to `np`](https://www.npmjs.com/package/np#usage) accordingly (annoyingly an inline comment cannot be added to package.json).
No.
n/a
Simpler version numbers.
We forget to remove revert this change once on v1.0.0 and we break semver (hopefully we won't though!).
n/a

minor releases only

---

src/constructs/autoscaling/asg.test.ts
src/constructs/core/parameters.test.ts
src/constructs/ec2/security-group.test.ts
src/constructs/iam/policies/base-policy.test.ts
src/constructs/iam/policies/log-shipping.test.ts
src/constructs/iam/policies/s3-get-object.test.ts
src/constructs/iam/policies/ssm.test.ts
src/constructs/iam/roles.test.ts
src/constructs/lambda/lambda.test.ts
src/constructs/loadbalancing/elb.test.ts
src/constructs/rds/instance.test.ts
src/patterns/instance-role.test.ts
test/utils/simple-gu-stack.ts

Adds a helper function to dry out tests.
No.
n/a
DRYer code.
n/a
n/a

add helper function to dry out tests

---

script/release

This PR ensures that old files are not released by clearing the lib directory before building and releasing the latest.

Clears the lib directory before build and releasing the latest

---

src/constructs/iam/policies/index.ts

This just makes it simpler to import as it becomes available on `@guardian/cdk/lib/constructs/iam`. This is similar to https://github.com/guardian/cdk/pull/94 - not sure how to catch this "issue" early?
https://github.com/guardian/deploy-tools-platform/pull/322 would need updating.
n/a
Simpler imports.
n/a

export the assume-role construct

---

src/constructs/core/parameters.test.ts
src/constructs/core/parameters.ts
src/constructs/iam/policies/log-shipping.ts
src/patterns/__snapshots__/instance-role.test.ts.snap

Reverting to rebase and fix all tests

Revert "Allow all parameters to be from SSM"

---

src/patterns/__snapshots__/instance-role.test.ts.snap
src/patterns/instance-role.test.ts
src/patterns/instance-role.ts

For naming consistency, `InstanceRole` becomes `GuInstanceRole`.
Yes.
Covered by existing test suite.
Consistent naming conventions.
n/a

rename InstanceRole to GuInstanceRole

---

script/release-docs

D'oh! We definitely want to install dependencies in the GH Action!

install dependencies!

---

package-lock.json
package.json

This PR replaces [http-server](https://www.npmjs.com/package/http-server) with [serve](https://www.npmjs.com/package/serve).
No.
Run the `./script/docs` command locally and ensure the docs are still served correctly.
We can continue to serve the docs locally.

Replace http-server with serve

---

README.md

Adds a note about the release numbers for this library for transparency.

add note about release numbers

---

src/constructs/loadbalancing/elb.test.ts
src/constructs/loadbalancing/elb.ts

This PR introduces a new `GuHttpsApplicationListener` construct which abstracts away some of the complexity of the `GuApplicationListener`. The two key abstractions are as follows:
* It omits the `defaultAction` prop and instead takes the `targetGroup` prop. The `defaultAction` value is then set to `ListenerAction.forward([props.targetGroup])`
* It omits the `certificates` prop and instead takes a single `certificate` value. The `certificates` value is then set to `[{ certificateArn: props.certificates }]`. The certificate prop is optional and if not provided a parameter will be created.
No but projects that use the `GuApplicationListener` might be able to move to the `GuHttpsApplicationListener` to reduce the complexity of their stack slightly.
New unit tests are added to cover the new …

Add new GuHttpsApplicationListener construct

---

.github/workflows/ci.yaml

In order for [machines](https://github.com/semantic-release/semantic-release) to automatically create releases for us, we need to structure the git history in standard way.
By default, [semantic-release](https://github.com/semantic-release/semantic-release) will enforce _individual commits_ are well structured.
The [prosemirror-typerighter](https://github.com/guardian/prosemirror-typerighter) repository uses semantic-release and after speaking with @jonathonherbert and @SHession about it, they recommend PR linting over commit linting as there is less friction.
Also removes CI from `main` as branch protection is enabled on `main`, so commits will only reach it via merging a PR. The repository is also configured for PRs to pass CI before they can be merged. These two combined, we can be …

docs: Adds GitHub Action to lint PRs.

---

.github/workflows/cd.yaml

Following #225, add a GHA workflow for continuous delivery. Where continuous deliver is:
- build
- test
- release (TODO!)
No.
n/a
CD is on for the `main` branch.
n/a

chore: Add a GHA for continuous delivery

---

.github/dependabot.yml

Prefix commits with "chore(deps): " to indicate the type of change. This is to help the robots understand history and automate the creation of release notes and new release version numbers.
See:
- https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines
- http://karma-runner.github.io/6.0/dev/git-commit-msg.html
- https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#commit-message
- #225 
No.
n/a
We're closer to automating releases - structured commits help robots parse history.
n/a

tweak dependabot's commit messages

---

src/constants/__mocks__/library-info.ts
src/constants/library-info.ts
src/constructs/cloudwatch/__snapshots__/lambda-alarms.test.ts.snap
src/constructs/core/stack.test.ts
src/constructs/core/stack.ts
src/constructs/iam/policies/__snapshots__/ses.test.ts.snap
src/constructs/iam/roles/__snapshots__/instance-role.test.ts.snap
src/constructs/lambda/__snapshots__/lambda.test.ts.snap
src/constructs/rds/instance.test.ts
src/patterns/__snapshots__/scheduled-lambda.test.ts.snap
src/patterns/__snapshots__/sns-lambda.test.ts.snap
test/utils/alphabetical-tags.ts
test/utils/index.ts

Follow the AWS tag name convention of `org:something`: `X-Gu-CDK-Version` becomes `gu:cdk:version`.
Also adds a test helper `alphabeticalTags` to sort tags alphabetically by tag name as the test matcher checks two arrays are the same order.
The would library need bumping, but no real impact.
See tests.
> convention (noun)
>   1. a way in which something is usually done.
n/a

refactor!: follow aws tag name convention of `org:something`

---

src/constructs/core/stack.ts

Marking it readonly makes usage a little clearer. This is basically a no-op.
No.
n/a
Easier to read?
n/a

fix: be explicit about access to migratedFromCloudFormation

---

src/constructs/autoscaling/user-data.test.ts
src/constructs/autoscaling/user-data.ts

In reality, we'll always specify the distribution bucket as a parameter, so make the type reflect that.
Yes.
See tests.
Types!
n/a

fix: update type in user data

---

src/constructs/core/stack.ts

Simplify GuStack's definition of stage. Calling `getParam` for a parameter we've just created is a redundant as we can simply use it!
This should be a no-op.
n/a
See pre-existing tests.
Simpler code.
n/a

refactor: simplify GuStack's definition of stage

---

README.md

We're seeing the build sporadically fail for odd reasons such as:
```console
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/runner/work/cdk/cdk/node_modules/npm/node_modules/umask/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/runner/work/cdk/cdk/node_modules/npm/node_modules/umask/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-04-06T10_58_18_551Z-debug.log
Error: Process completed with exit code 254.
```
This change adds a badge to the README to make it quick to see this, as the alternative is view the log here https://github.com/guardian/cdk/actions/workflows/cd.yaml.
No.
n/a …

chore: add CD status badge to README

---

src/patterns/__snapshots__/ec2-app.test.ts.snap
src/patterns/ec2-app.test.ts
src/patterns/ec2-app.ts

@stephengeller - perhaps we can merge this into your branch and then continue working from there?

Continue work on EC2 App pattern

---

docs/001-general-usage.md

This change:
- adds a couple of links
- formats some paragraphs into lists
- adds emoji ✨
See it [here](https://github.com/guardian/cdk/blob/aa-update-gen-usage/docs/001-general-usage.md).
No.
n/a
n/a
n/a

docs: update general usage doc

---

package-lock.json

When running `./script/setup` (or `npm install` or `npm ci`), npm reports:
> found 51 moderate severity vulnerabilities
>   run `npm audit fix` to fix them, or `npm audit` for details
This is the result of running `npm audit fix`.
No.
n/a
No vulnerabilities?
n/a

chore: Fix 51 severity vulnerabilities

---

src/constructs/cloudwatch/__snapshots__/lambda-alarms.test.ts.snap
src/constructs/cloudwatch/alarm.test.ts
src/constructs/cloudwatch/lambda-alarms.test.ts
src/constructs/lambda/__snapshots__/lambda.test.ts.snap
src/constructs/lambda/lambda.test.ts
src/constructs/lambda/lambda.ts
src/patterns/__snapshots__/kinesis-lambda.test.ts.snap
src/patterns/__snapshots__/scheduled-lambda.test.ts.snap
src/patterns/__snapshots__/sns-lambda.test.ts.snap
src/patterns/kinesis-lambda.test.ts
src/patterns/scheduled-lambda.test.ts
src/patterns/scheduled-lambda.ts
src/patterns/sns-lambda.test.ts

Update the props for `GuLambdaFunction` to provide a similar API to `GuUserData`.
This should produce a simpler API.
This also means the lambda's code get's downloaded from the path `bucket/stack/stage/app/fileName`.
BREAKING CHANGE: `GuLambdaFunction` props have changed.
The `code` prop is replaced with the string prop of `fileName`.
We go from:
```typescript
new GuLambdaFunction(stack, "lambda", {
code: { key: "folder/to/key" },
handler: "handler.ts",
runtime: Runtime.NODEJS_12_X,
app: "testing",
});
```
To:
```typescript
new GuLambdaFunction(stack, "lambda", {
fileName: "my-app.zip",
handler: "handler.ts",
runtime: Runtime.NODEJS_12_X,
app: "testing",
});
```
Yes. See breaking change notes above.
See tests?
The API to a lambda and EC2 look similar to each other, thus easier to use?
n/a

feat: Update `GuLambdaFunction` props to match `GuUserData` 

---

src/constructs/lambda/lambda.test.ts
src/constructs/lambda/lambda.ts
src/patterns/__snapshots__/api-lambda.test.ts.snap
src/patterns/api-lambda.test.ts
src/patterns/api-lambda.ts
src/patterns/kinesis-lambda.ts
src/patterns/scheduled-lambda.ts
src/patterns/sns-lambda.ts

Refactor the props to `GuLambdaFunction` to create an explicit pattern for an API Gateway executed lambda.
BREAKING CHANGE: Define an API Gateway executed lambda with the explicit `GuLambdaFunction` pattern
Yes, see notes above.
See tests.
The API to create a lambda is cleaner.
n/a

feat: Add `GuApiLambda` pattern

---

src/constructs/core/parameters/s3.ts
src/constructs/lambda/lambda.ts

This PR adds some docs for our `GuLambdaFunction` construct.
No.
This _is_ a documentation change.
Run ./script/docs and have a look at the changes?
It should be easier for users to understand the `GuLambdaFunction` construct and the defaults it provides.
N/A

docs: Add docs for GuLambdaFunction

---

.github/PULL_REQUEST_TEMPLATE.md

Add a reminder about https://github.com/guardian/cdk-playground to the PR template under the "how to test" section.
No.
Nope.
n/a
Reminder of a shiny new toy?
n/a

chore: Add note on cdk-playground to PR template

---

src/constructs/cloudwatch/__snapshots__/ec2-alarms.test.ts.snap
src/constructs/loadbalancing/alb/application-load-balancer.test.ts
src/constructs/loadbalancing/alb/application-load-balancer.ts
src/patterns/__snapshots__/ec2-app.test.ts.snap

Creates a Cloudformation output for the DNS value of an ALB.
This is useful in two scenarios:
1. When creating a new stack, as it saves you clicking around the AWS console
2. An early warning that something stateful will change across versions of GuCDK as the snapshot will differ
No.
No.
See tests?
Hopefully it makes spotting breaking changes to DNS easier.
n/a

feat: Output an ALB's DNS entry

---

README.md

A no-op change to the main README. The main reason for this change is to make the file easier to read in it's raw format:
- Links have been switched to reference style links
- A (somewhat arbitrary) line width is being followed (I was horizontal scrolling on my 25" screen with 12pt font before...)
No.
No.
[Read it?](https://github.com/guardian/cdk/blob/35b1451a822cfce26d042c6a940ae3418061aec8/README.md)
The README is easier to read in it's raw format.
n/a

chore: Tidy README a little

---

src/patterns/ec2-app.test.ts
src/patterns/ec2-app.ts

This allows users to access and modify constructs baked into the EC2 pattern with ease.
No, as this will be an extra feature and the EC2 pattern isn't being used in production yet.
`./script/test`. A test has been added to test this functionality.
* Users can access constructs to make changes as they please, unblocking users that can't achieve everything with the limitations of the EC2 pattern
* Users have more flexibility in general
I can't think of any at the moment.

feat(ec2-app-pattern): allow in-pattern constructs to be accessible from within the pattern

---

docs/006-testing.md

A few notes on testing changes in an ad-hoc manner. @jacobwinch and I paired yesterday and it took a little too long to get the integration test project set up to test API changes, so documenting the steps for next time!
No.
No.
Does the document read well?
n/a
n/a

docs: Adds advice on how to ad-hoc test changes

---

.github/workflows/cd.yaml
.github/workflows/ci.yaml

We're seeing builds fail sporadically with a stacktrace similar to this:
```console
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/runner/work/cdk/cdk/node_modules/npm/node_modules/spdx-expression-parse/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/runner/work/cdk/cdk/node_modules/npm/node_modules/spdx-expression-parse/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-05-05T07_21_06_708Z-debug.log
Error: Process completed with exit code 254.
```
Although re-running the build is usually enough, it seems more frequent in recent days so we should fix it.
The NPM docs sort of hint …

chore: Use GitHub Action caching

---

package-lock.json
package.json
src/constants/__mocks__/tracking-tag.ts
src/constants/context-keys.ts
src/constants/tag-keys.ts
src/constants/tracking-tag.ts
src/constructs/acm/__snapshots__/certificate.test.ts.snap
src/constructs/cloudwatch/__snapshots__/ec2-alarms.test.ts.snap
src/constructs/cloudwatch/__snapshots__/lambda-alarms.test.ts.snap
src/constructs/core/stack.test.ts
src/constructs/core/stack.ts
src/constructs/iam/policies/__snapshots__/log-shipping.test.ts.snap
src/constructs/iam/policies/__snapshots__/ses.test.ts.snap
src/constructs/iam/roles/__snapshots__/instance-role.test.ts.snap
src/patterns/__snapshots__/api-lambda.test.ts.snap
src/patterns/__snapshots__/ec2-app.test.ts.snap
src/patterns/__snapshots__/kinesis-lambda.test.ts.snap
src/patterns/__snapshots__/scheduled-lambda.test.ts.snap
src/patterns/__snapshots__/sns-lambda.test.ts.snap
src/utils/test/jest.ts

Adds a new `gu:repo` tag to the GuStack and any resource added to it.
The purpose of this tag is to provide information on where to find  an
application.
The value of the tag comes from one of two places:
1. CDK context
2. Git config
If we cannot find the repository name from either, we log a message.
A Git URL can be in two main formats:
1. https, for example `https://github.com/guardian/cdk.git`
2. ssh, for example `git@github.com:guardian/cdk.git`
Use `git-url-parse` to handle the parsing of a Git URL and present it in the form `owner/name`. For example, `guardian/cdk` or `guardian/prism`.
This can be useful when using Prism to find lambdas running deprecated versions of Node, for example.
See:
- https://docs.aws.amazon.com/cdk/latest/guide/context.html
Yes - they need to bump the …

feat: Add new tag for repository info

---

src/patterns/ec2-app.test.ts
src/patterns/ec2-app.ts

At the moment, users of the GuEC2App have no way of configuring their scaling policies. This is something we can do [at the AutoScalingGroup construct level](https://github.com/guardian/cdk/blob/9b9a91bc03f507ba4d688024b4fc8059a617f9d0/src/constructs/autoscaling/asg.ts#L33), but have not wired up to the pattern.
This PR adds a `scaling` prop, allowing users to optionally specify minimum and maximum instance scaling policies for their applications. Like `GuAutoScalingGroup`, this prop only requires users to specify the minimum instance count and multiplies it by 2 unless otherwise specified.
None yet as it's an optional default, but this will further unlock AMIable's migration.
Docs have been added alongside the other props.
Users can control their application scaling …

feat(ec2-app-pattern): allow users to optionally configure scaling policies per stage

---

jest.config.js
tsconfig.test.json

By default, `ts-jest` will use [`tsconfig.json`](https://github.com/guardian/cdk/blob/6eb791548e727e9115991fbd53fa0931a4665c6f/tsconfig.json) for TypeScript configuration.
Our `tsconfig.json` sets [`noUnusedLocals`](https://www.typescriptlang.org/tsconfig#noUnusedLocals) to `true`. This means compilation will fail if we import something and don't use it.
If you're running tests locally (using [`script/start`](https://github.com/guardian/cdk/blob/6eb791548e727e9115991fbd53fa0931a4665c6f/script/start), for example) and comment out a block of code that results in an import not being used, a compile error will result and the tests will not run until resolved.
In reality you are going to use it, so you end up temporarily commenting out the import (once you've expanded them as the IDE collapses …

chore: Use custom `tsconfig` for `ts-jest`

---

src/constructs/iam/policies/s3-get-object.ts

This makes the [documentation site](https://guardian.github.io/cdk/classes/constructs_iam.gugetdistributablepolicy.html) more useful.
This is after https://github.com/guardian/amigo/pull/596 where I wanted to link to a place that described the policy this construct would create for extra clarity.
Side note: I've just discovered [`yq`](https://mikefarah.gitbook.io/yq/) via [Stack Overflow](https://stackoverflow.com/a/62798787/3868241).
No.
I am the documentation mwuhahaha!
n/a
n/a
n/a

chore: Add basic docs for `GuGetDistributablePolicy`

---

package.json
script/update-aws-cdk

This PR attempts to fix some of the problems that we noticed in https://github.com/guardian/cdk/pull/641.

chore: Attempt to fix update-aws-cdk script

---

bin/gu-cdk
package-lock.json
package.json
script/cli
src/bin/commands/aws-cdk-version.ts
src/bin/index.ts
src/constants/__mocks__/tracking-tag.ts
src/constants/library-info.ts
src/constants/tracking-tag.ts

#675 was just released on the `beta` channel. It's proven to work as expected, so we can release this to the main channel now for general availability.
I _think_ this is a `chore`? `semantic-release` should create a new release on `main` as there is a `feat` commit being merged 🤞🏽 .
n/a
n/a
n/a
n/a
n/a

chore: Bring `main` up to date with `beta` (adds PR 675)

---

README.md

Updates the README - we don't enforce squashing anymore; you're free to merge however you like 🎉 .

docs: Update commit style

---

package-lock.json
package.json
src/bin/commands/account-readiness.ts

This improves the output of the account-readiness cli tool so that it is more legible by the user. It uses [chalk](https://www.npmjs.com/package/chalk) to easily format the output, helping users identify what SSM parameters need to be added.
Before:
After:
I'm not 100% sure on the wording used for the output, but it gets the message across.
Nope.
Don't think so.
In the repo, run `./script/cli account-readiness --profile <PROFILE>` to see if a given AWS account has the correct SSM parameters. You will need access keys for said profile.
Users can quickly and easily identify the missing SSM parameters required to use GuCDK efficiently.
None that have been introduced by this PR.

feat(cli): improve account-readiness cli output

---

src/bin/commands/account-readiness.ts

Not a massive change, use a `forEach` instead of a `map` which is slightly more readable. As a result we can use fewer newlines to achieve the same output. That is, this is a no-op.
No.
No.
n/a
Simpler code?
n/a

refactor: Simplify `account-readiness` a little

---

src/patterns/ec2-app.ts

Add a `,` to produce a code snippet that compiles when copy pasted.

chore: Fix typo in code snippet

---

.github/PULL_REQUEST_TEMPLATE.md

Favour checklist items for the yes/no questions being asked in the PR template as it's faster to respond.
See it [here](https://github.com/guardian/cdk/blob/aa-update-pr-template/.github/PULL_REQUEST_TEMPLATE.md).
No!
No!
n/a
It's that much easier to raise a PR.
n/a

docs: Simplify PR template

---

.github/workflows/cd.yaml
.github/workflows/ci.yaml
script/check-aws-cdk

Clean up some changes from https://github.com/guardian/cdk/pull/885 that [I didn't anticipate](https://github.com/guardian/cdk/pull/885#issuecomment-964646275) being merged.
Namely:
- Reverting change to AWS CDK version tolerance
- Configuring of `additional-changes`
This change also moves to a released version of `guardian/actions-merge-release-changes-to-protected-branch`.
Depends on https://github.com/guardian/actions-merge-release-changes-to-protected-branch/pull/218, this PR will fail until that PR is merged.
CI should pass.
Accidental changes are removed!
n/a
[^2]: …

chore: Use released version of `guardian/actions-merge-release-changes-to-protected-branch`

---

src/patterns/scheduled-ecs-task.test.ts

chore: Fix a linting error

---

tools/integration-test/tsconfig.json

CI for the `integration-test` project is currently failing with:
```console
Error: node_modules/@types/jsdom/base.d.ts(24,40): error TS2304: Cannot find name 'DocumentFragment'.
Error: node_modules/@types/jsdom/base.d.ts(41,28): error TS2304: Cannot find name 'Node'.
Error: node_modules/@types/jsdom/base.d.ts(172,19): error TS2304: Cannot find name 'HTMLScriptElement'.
Error: node_modules/@types/jsdom/base.d.ts(172,39): error TS2304: Cannot find name 'HTMLLinkElement'.
Error: node_modules/@types/jsdom/base.d.ts(172,57): error TS2304: Cannot find name 'HTMLIFrameElement'.
Error: node_modules/@types/jsdom/base.d.ts(172,77): error TS2304: Cannot find name 'HTMLImageElement'.
Error: node_modules/@types/jsdom/base.d.ts(181,38): error TS2304: Cannot find name 'Window'.
Error: …
```

ci: Explicitly add DOM types

---

tools/integration-test/package.json
tools/integration-test/tsconfig.json

This change reverts #949 which wasn't the most desirable solution and instead updates to the latest version of Jest.
See https://github.com/facebook/jest/issues/12098#issuecomment-983669113.
Simpler config?

chore(deps): Update Jest in integration-test to 27.4.3 

---

src/constructs/cloudwatch/__snapshots__/ec2-alarms.test.ts.snap
src/constructs/cloudwatch/ec2-alarms.ts

AWS's [docs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/AlarmThatSendsEmail.html#alarm-evaluation) around CloudWatch Alarms are quite confusing, at least for me. Specifically this part:
> When you configure Evaluation Periods and Datapoints to Alarm as different values, you're setting an "M out of N" alarm. Datapoints to Alarm is ("M") and Evaluation Periods is ("N"). The evaluation interval is the number of data points multiplied by the period. For example, if you configure 4 out of 5 data points with a period of 1 minute, the evaluation interval is 5 minutes. If you configure 3 out of 3 data points with a period of 10 minutes, the evaluation interval is 30 minutes.
This change adds a bit more clarity to how things are calculated.
N/A
Increased clarity?
n/a
[^1]: …

fix: Derive unhealthy instance alarm description from other values

---

src/constructs/ecs/__snapshots__/ecs-task.test.ts.snap
src/constructs/ecs/ecs-task.test.ts
src/constructs/ecs/ecs-task.ts
src/patterns/scheduled-ecs-task.test.ts

We do not need to specify `stack` and `stage` at the component/pattern level as these properties are available on `GuStack`. Using the `GuStack` values also increases the type-safety as `stage` is _not_ a `string`.
This change also refactors to use destructing of the `props` object, which yields simpler code for default values.
Increased type-safety and consistency.
n/a

fix: `GuEcsTask` uses `stack` and `stage` from parent `GuStack` for consistency

---

src/constructs/iam/roles/__snapshots__/github-actions.test.ts.snap
src/constructs/iam/roles/github-actions.ts

https://github.com/guardian/deploy-tools-platform/pull/567

fix: update GitHub Actions thumbprint

---

src/patterns/ec2-app.ts

Using destructuring with default values makes things a little clearer as we can co-locate things. This follows a pattern introduced in https://github.com/guardian/cdk/pull/1019.
This is a no-op as demonstrated by the existing tests continuing to pass.
This is actually part of a wider change to allow the EC2 pattern to support the `INFRA` stage - it currently supports `CODE` and `PROD` only.

refactor: Make default values for EC2 pattern more obvious

---

package-lock.json
package.json
src/constructs/core/custom-resources/runtime/lambda.ts
src/constructs/core/identity.ts
src/constructs/iam/fastly-logs-iam.ts
src/types/migrating.ts
src/utils/mixin/app-aware-construct.ts
src/utils/mixin/migratable-construct-stateful.ts
src/utils/mixin/migratable-construct.ts
tools/integration-test/package.json

- Update `@guardian/eslint-config-typescript` to v1.0.0
- Update `eslint` to v8.8.0
Closes:
- #1068
- #1069
Keeping dependencies up to date.
n/a

chore(deps): Update linter

---

src/patterns/ec2-app/base.test.ts
src/patterns/ec2-app/base.ts
src/types/access.test.ts
src/types/access.ts

Part of an ongoing effort to reduce the LOC in `ec2-app` (see #1105 and #1108 for previous work).
This is a no-op in terms of functionality. Hopefully it's as clear, if not more clear, to understand as before.
This change moves some CIDR validation logic away into it's own file for increased readability and testing.
A simpler codebase.
n/a

refactor: Move `AppAccess` validation out of EC2 pattern file

---

docs/architecture-decision-records/006-stage-awareness.md

Converting [our discussions](https://docs.google.com/document/d/1YCuOYsBVdO1eB80t6j0ElTCtoRc3doqmH-v4v6sC9B4/edit#) on stage awareness into an ADR for prosperity.
I've found this fairly hard to write, please don't hold back on the review!
View it [here](https://github.com/guardian/cdk/blob/aa-stage-adr/docs/architecture-decision-records/006-stage-awareness.md).
Does it read well? Is it clear?

docs: Add ADR for stage awareness

---

README.md
docs/best-practices.md

This PR adds a best practices document. It outlines how GuCDK builds in best practices and then lists best practice recommendations to follow when using CDK.

docs: Add best practices doc

---

docs/architecture-decision-records/006-stage-awareness.md

Update ADR following #1134 and release of v39.0.0.

docs: Update status of stage awareness ADR

---

src/bin/commands/new-project/utils/init.ts
src/constants/library-info.ts

There are a few changes here:
- Removing of redundant scripts in generated `package.json`
- Moving all dependencies as `devDependencies` in `package.json`
- Derive the version of deps for a GuCDK project from GuCDK itself, on the basis that GuCDK's own deps will stay up to date more regularly (via Dependabot)
See CI?
New GuCDK projects will use more up-to-date version of dependencies, and thus yield fewer Dependabot PRs in repositories immediately after committing the project to a repository.
n/a
[^2]: If you are adding a new construct or pattern, has new documentation …

fix(project generator): Update version of dependencies

---

package-lock.json
package.json
src/bin/commands/new-project/index.ts

Replace `cli-ux` with `@oclif/core` per https://github.com/oclif/core/blob/main/src/cli-ux/README.md. It could also be argued that we should drop this dependency entirely and simply use `console.log`...
As this is a no-op, CI should continue to pass.
Removal of a deprecated dependency.
n/a

chore(deps): Remove deprecated dependency `cli-ux`

---

README.md
docs/setting-up-a-gucdk-project.md

This PR improves the setting-up-a-new-project docs and moves some information from the main repo into this section of the docs.
N/A
It's more obvious which pattern to pick and where to find the list of patterns.

docs: improve setting up a new project docs

---

.github/workflows/snyk.yml

This adds a github action that triggers snyk monitor every day at 6am.

ci: Add snyk monitoring

---

docs/migration-guide.md

Describing the [red/green refactor](https://blog.cleancoder.com/uncle-bob/2014/12/17/TheCyclesOfTDD.html) cycle of a migration.
[Read the update](https://github.com/guardian/cdk/blob/aa-migration/docs/migration-guide.md) - does it make sense?

docs: Update migration guide with a workflow for stateful resources

---

docs/setting-up-a-gucdk-project.md

Just to make it clear that step doesn't update the snapshot, but uses it as an expected value

docs: clarify purpose of snapshot tests

---

package-lock.json
package.json
script/ci
tools/integration-test/package.json

A few changes made in this PR:
- Run `tsc` once in CI
The `prepare` script runs `tsc`, as does the `build` script. We only need to compile once in CI, so ignore the `prepare` script. This should reduce build times.
- Update `@guardian/eslint-config-typescript` to include https://github.com/guardian/csnx/pull/60
Observe CI.
A faster build.
n/a

ci: Attempt to improve build time

---

src/constants/ssm-parameter-paths.ts

Builds on #1451.
`/account/services/anghammarad.topic.arn` is used to integrate with Anghammarad. Use-cases for Anghammarad is almost exclusively [within DevX](https://github.com/search?q=org%3Aguardian+GuAnghammaradSenderPolicy&type=code); it should be optional.
See: https://github.com/guardian/anghammarad
CI should suffice.
Less work for an account to become GuCDK ready. Though https://github.com/guardian/aws-account-setup is used to simplify that process now too.
n/a
[^2]: If you are adding a new construct or pattern, has new documentation been added? If you are …

fix: Mark `/account/services/anghammarad.topic.arn` SSM Parameter as optional

---

src/experimental/riff-raff-yaml-file/deployments/lambda.ts
src/experimental/riff-raff-yaml-file/index.test.ts

The generated `riff-raff.yaml` file requires CI to upload artifacts to the following pattern:
```
.
├── cdk.out
│   └── MyApplication.template.json
├── my-application
│   └── my-application.deb
├── my-other-application
│   └── my-other-application.jar
│   └── my-other-application.service
└── my-lambda
└── my-lambda.zip
```
Where `cdk.out` holds all CloudFormation templates, and each other directory name corresponds to each app.
In this change we correct an issue when building the deployments for lambdas to match this pattern.
See CI.
A closer following of the described directory structure.
n/a
[^1]: Consider whether this is something that will mean changes to projects that have already been migrated, or to the CDK CLI tool. If changes are required, consider adding a checklist here and/or …

fix(riff-raff.yaml): Use app for `contentDirectory` for lambda deployments

---

src/constructs/cloudwatch/__snapshots__/lambda-alarms.test.ts.snap
src/constructs/lambda/lambda.test.ts
src/constructs/lambda/lambda.ts
src/experimental/patterns/__snapshots__/kinesis-lambda.test.ts.snap
src/experimental/patterns/__snapshots__/sns-lambda.test.ts.snap
src/patterns/__snapshots__/api-lambda.test.ts.snap
src/patterns/__snapshots__/api-multiple-lambdas.test.ts.snap
src/patterns/__snapshots__/scheduled-lambda.test.ts.snap

Update the policy for `GuLambdaFunction`s, granting S3 read to the exact object of the lambda, rather than the entire bucket.
This follows the principle of least privilege.
s/o @Fweddi for pointing this out!
See updated tests.
A close following of the principle of least privilege.
None. Riff-Raff will upload to this path already and a lambda should not need to read from elsewhere in the bucket. In the unlikelihood that it does, an additional explicit permission should be added by end-users.
Any lambda that is relying on this side-effect would have to be updated to regain permissions to any additional objects in the bucket being accessed.
[^1]: Consider whether this is something that will mean changes to projects that have already been migrated, or to the CDK CLI tool. If changes are …

fix(GuLambdaFunction): Tightly scope S3 permission

---

jest.config.js
package-lock.json
package.json
src/bin/commands/new-project/utils/utils.ts

Bump:
- jest to 29.1.2
- @types/jest to 29.1.1
- ts-jest to 29.0.3
Also included in this change are some Jest configuration changes.
The `transform` change resolves this deprecation warning:
```console
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
<transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
```
The `snapshotFormat` allows us to retain the snapshot format from Jest 28 (we'll remove in a follow-up PR). See:
- https://jestjs.io/docs/upgrading-to-jest29#snapshot-format
- https://jestjs.io/blog/2022/08/25/jest-29
See CI.
Keeping up-to-date.
n/a
[^1]: Consider whether this is something that will mean changes to projects that have already been migrated, or to the CDK CLI tool. If changes are …

chore(deps): Update Jest to v29

---

src/aspects/cfn-parameter-reporter.test.ts
src/aspects/cfn-parameter-reporter.ts
src/constructs/core/stack.ts

If a CFN Parameter references a value in SSM Parameter store, the SSM Parameter must exist prior to deployment.
In this change, we Annotate the stack with a message to remind users of this.
See added tests, and observe CI.
Providing more help to ensure a stack can be provisioned successfully first time.
N/A

feat: Add reminders for CFN Parameters

---

package-lock.json
package.json
tools/integration-test/package.json

Batches multiple Dependabot changes for expediency in build and review.
- https://github.com/guardian/cdk/pull/1598
- https://github.com/guardian/cdk/pull/1597
- https://github.com/guardian/cdk/pull/1596
- https://github.com/guardian/cdk/pull/1595
- https://github.com/guardian/cdk/pull/1594
- https://github.com/guardian/cdk/pull/1593

chore(deps): Various dependabot

---

src/constants/metadata-keys.ts
src/patterns/ec2-app/base.ts

(Purely for testing via the `beta` branch/release.)

feat: add support for Google auth

---

README.md
src/patterns/ec2-app/base.ts

feat: google auth (to beta)

---

src/constants/metadata-keys.ts
src/patterns/ec2-app/__snapshots__/base.test.ts.snap
src/patterns/ec2-app/base.test.ts
src/patterns/ec2-app/base.ts

The `gu:cdk:pattern-name` tag was added (#603) to patterns to aid usage tracking[^1].
In #1394 more exhaustive tracking was added via CFN Metadata. That is, we no longer need to apply the `gu:cdk:pattern-name` tag.
❓ Should we remove this field from Prism too? See https://github.com/guardian/prism/pull/224.
[^1]: It was only added to the EC2 pattern, so tracking was only partial.
Observe CI.
Less code!
n/a
[^2]: Consider whether this is something that will mean changes to projects that have already been migrated, or to the CDK CLI tool. If changes are required, consider adding a checklist here and/or linking to related PRs.
[^3]: If you are adding a new construct or pattern, has new documentation been added? If you are amending defaults or changing behaviour, are the existing docs still …

fix(pattern-tracking): Remove `gu:cdk:pattern-name` tag

---

script/update-aws-cdk

It appears that the latest version of `npm-check-updates` is not bumping `peerDependencies` in `package.json`. We want this behaviour, so in this change we pin `ncu` to a known version, whilst we investigate the underlying cause.
See https://github.com/guardian/cdk/pull/1642 for undesired behaviour.
n/a
After this change, an invocation of the [`update-aws-cdk` script](https://github.com/guardian/cdk/blob/main/script/update-aws-cdk) should work properly, updating all the relevant parts in `package.json`. See https://github.com/guardian/cdk/pull/1647.
n/a
[^2]: If you are …

chore(deps): Pin version of `npm-check-updates`

---

docs/best-practices.md

Documentation change to show how to update snapshot tests.

docs: Note about test-update

---

src/constructs/iam/roles/__snapshots__/github-actions.test.ts.snap
src/constructs/iam/roles/github-actions.ts

Follows the update in https://github.blog/changelog/2023-06-27-github-actions-update-on-oidc-integration-with-aws/.
See updated snapshot test.
From the GitHub blog, this update should reduce the change of seeing the token exchange fail.
N/A

fix(GuGithubActionsRole): Update thumbprints

---

.changeset/fuzzy-poets-approve.md
package-lock.json
package.json

Make dependency `@changeset/cli` development only
`npx changeset` locally still works
A much smaller package
Fixes #2148 
None!

Make `@changeset/cli` development only

---

.changeset/breezy-countries-bake.md
src/constructs/autoscaling/asg.ts
src/patterns/ec2-app/__snapshots__/base.test.ts.snap

Apply the `App` tag to the launch template created in the EC2 App pattern.
See snapshot updates.
More tags!
n/a

fix(ec2-app): Apply the `App` tag to the launch template

---

.changeset/light-experts-refuse.md

Adds a changeset, a step that was missed in #2260

add changeset that was missed in #2260

---

CHANGELOG.md

Updates the release notes for v61.5.0 and the changes in https://github.com/guardian/cdk/pull/2561. When using [Riff-Raff's `autoscaling` deployment type](https://riffraff.gutools.co.uk/docs/magenta-lib/types#autoscaling), upgrading needs to be performed in two stages.
Do the docs make sense?
A simpler upgrade path.
N/A.

docs: Add detailed notes for v61.5.0

---

docs/migration-guide-api-with-lambda.md
docs/migration-guide-ec2.md
docs/migration-guide-scheduled-lambda.md
docs/migration-guide.md

This PR updates our migration docs following a recent review.

docs: attempt to improve GuCDK migration docs
